### ISSUE TITLE
Echo device not accessible through smartapps

### ISSUE THREAD

**Issue by raulpandey** [tonesto7/echo-speaks#10]
Thanks, I am finally able to see echo devices in the smarthings app. However, when I tested them in a few smart apps, like announcing a contact sensor open or close, they don’t announce anything.

On the other side, I can see the echo devices, control playback, play weather report and sent tts message by clicking the button on the echo device interface inside the smartthings app. See picture below. 

Please help in debugging this. I have also turned on [2-factor] authentication on Amazon. (Do I need to rebuild Heroku app after turning it on to help?)

Picture of echo device interface from within smarthings app:

![2c638496a011a304e25ba3ea638053fc8dcc62f9](https://user-images.githubusercontent.com/19899303/48763324-e0111980-ec61-11e8-8aff-e369298e0c9e.png)

**Comment by rickydg** [comment]
What smartapps are you using to announce? It states in the wiki that webcore is the suggested method.

**Comment by merrick777** [comment]
I have identical issue as @raulpandey and I've tried with webcore with this simple piston.

![webcoretest](https://user-images.githubusercontent.com/22691436/48855806-d3381700-ed82-11e8-8058-65babfa41b65.png)

**Comment by TonyFleisher** [comment]
No updates in awhile. Is this still an issue?

**Comment by raulpandey** [comment]
@TonyFleisher, I was able to get it working, by uninstalling and re-installing everything.
It's not the most intelligent solution but somehow it worked.
