### ISSUE TITLE
(BUG) 

### ISSUE THREAD

**Issue by jnewbury2280** [tonesto7/echo-speaks#101]
Have some new Echo Dots that are not recognized properly. 

DeviceType IDs:

![CDB0661F-1573-421D-9DCE-A30CA81BAFD6](https://user-images.githubusercontent.com/5819158/62431169-ef9e9880-b6f2-11e9-8108-9cecff5e2e0c.jpeg)
![6ABBB050-7EA4-4AA6-9930-F16529E70C23](https://user-images.githubusercontent.com/5819158/62431170-ef9e9880-b6f2-11e9-90f1-881cc3d768f0.jpeg)
![EF90B712-D127-48A5-981C-9567383B9D1F](https://user-images.githubusercontent.com/5819158/62431171-ef9e9880-b6f2-11e9-9386-217c9c317624.jpeg)

Model Name: Echo Dot
Generation of the device: Gen 3

**Comment by tonesto7** [comment]
Thanks for reporting... Just open the smart app and press done and it should download the latest device data and correct it's self.

**Comment by jnewbury2280** [comment]
Fixed! Is there a way to do announcements on multi room WHA devices? I see this functionality is currently disabled.

**Comment by tonesto7** [comment]
There will be support in the upcoming v3 release in the new actions app.
