### ISSUE TITLE
(BUG) Newest ecobee smart thermostat (aka ecobee 5) features not enabled 

### ISSUE THREAD

**Issue by jaredhouck** [tonesto7/echo-speaks#115]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Hubitat
-  How many devices are detected?: 4
-  iOS or Android?: ios
-  Mobile App Version(Not required):
-  App/SmartApp Version: 2.6.0
-  Device Handler/Driver Version: 2.6.0
-  Heroku Server Version: 2.2.3

## Expected Behavior
Should fully recognize newest ecobee smart thermostat (aka ecobee 5) and all available features

## Current Behavior
Not recognizing all features of the newest ecobee smart thermostat (aka ecobee 5). They show up as Echo Unknown A2X8WT9JELC577=2 with TTS&Announcement = false.

## Steps to Reproduce (for bugs)
1. Autodetect devices 
2. Ecobees are detected
3. Device details show tts&announcement: false
4. Family: unknown

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

Can't do TTS or announcements with ecobee 5 even though ecobee 4 can.

![echo speaks ecobee smart thermo](https://user-images.githubusercontent.com/54729926/64057708-60a86300-cb6e-11e9-9050-1eadfc00bd64.PNG)
---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
If you open the Echo Speaks app and press Done you should see the device start to work

**Comment by rodwilson2** [comment]
I’m not seeing that done button your talking about . I see a next button and then save but it doesn’t change anything I’m still getting this page when I try to login my amazon credentials.     
  

  
  
  

  
  

  
  
>

**Comment by tonesto7** [comment]
@rodwilson2 I'm not sure what you're referring to.  This issue has to do with support for Ecobee 5

**Comment by jaredhouck** [comment]
TTS/announcement still not working with ecobees. Music test did work with ecobees.

TTS test, TTS rule, and music test definitely working with echo dots. 

Checkout how the ecobee4 for another user. 

![ecobee4](https://user-images.githubusercontent.com/54729926/64058151-b849cd00-cb74-11e9-9dec-9b2f763f2947.PNG)
 
The 5 definitely does announcements via normal alexa functions.

**Comment by rodwilson2** [comment]
I’m talking about echo speaks
  

  
  

  
  
>

**Comment by rodwilson2** [comment]
I’ve verified everything and it’s still not working   
  

  
  

  
  
>

**Comment by surf404** [comment]
Same problem with the Ecobee Switch+, announcments can be done from the alexa app, but not enabled (false) in echo speaks
![IMG_0677](https://user-images.githubusercontent.com/31177849/64088697-ac930d80-cd10-11e9-9471-2e3f6406f23a.jpg)
