### ISSUE TITLE
Echo Speaks Login Bug

### ISSUE THREAD

**Issue by Rudejedi122** [tonesto7/echo-speaks#1155]
-  [X ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [X] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [X] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Hubitat C-8 Platform 2.3.7.146
-  How many devices are detected?: All
-  iOS or Android?: iOS and Windows
-  Echo Speaks App Version: v4.2.3.0
-  Echo Speaks App  Version: v2.8.0
-  Heroku Server Stack Version: 22

## Expected Behavior
When deploying Heroku server after build, clink open app and sign-in to Amazon account to link Amazon and Heroku to Echo Speaks..

## Current Behavior
When deploying Heroku server, I am unable to logon to my Amazon account to give access to the server and Echo Speak app. The link appears to be broken. tried both on my iPhone and Windows computer.

## Steps to Reproduce (for bugs)
Step 6-8 in Server Configuration Guide. https://tonesto7.github.io/echo-speaks-docs/configuration/config_server/#step_6

## Context
Unable to employ Echo Speaks app in Hubitat. Not sure if the issue is with Heroku or if the app can create a separate login to connect all 3. tried uninstalling and reinstalling Echo Speaks App/drivers in Hubitat to clear any issues.

---
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:22:23.879[error](http://192.168.2.13/logs#)EchoApp (v4.2.3.0) | wakeupServerResp Exception: java.lang.Exception: No response data exists for async request
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:22:23.875[error](http://192.168.2.13/logs#)EchoApp (v4.2.3.0) | wakeupServerResp | Stack Trace: java.lang.Exception: No response data exists for async request
at hubitat.scheduling.AsyncResponse.getData(AsyncResponse.groovy:71)
at user_app_tonesto7_Echo_Speaks_693.wakeupServerResp(user_app_tonesto7_Echo_Speaks_693.groovy:2232)
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:22:23.868[error](http://192.168.2.13/logs#)EchoApp (v4.2.3.0) | wakeupServerResp Server may be down / unreachable
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:22:23.865[warn](http://192.168.2.13/logs#) EchoApp (v4.2.3.0) | wakeupServerResp: 404
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:20:09.731[warn](http://192.168.2.13/logs#) EchoApp (v4.2.3.0) | Echo Speaks Authentication is no longer valid... Please login again and commands will be allowed again!!! | Method: (getEchoDevices)
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:20:09.725[warn](http://192.168.2.13/logs#) EchoApp (v4.2.3.0) | Echo Speaks Authentication is no longer valid... Please login again and commands will be allowed again!!! | Method: (checkGuardSupport)
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:17:52.530[warn](http://192.168.2.13/logs#) EchoApp (v4.2.3.0) | Echo Speaks Authentication is no longer valid... Please login again and commands will be allowed again!!! | Method: (getEchoDevices)
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:16:40.773[warn](http://192.168.2.13/logs#) EchoApp (v4.2.3.0) | Echo Speaks Authentication is no longer valid... Please login again and commands will be allowed again!!! | Method: (getEchoDevices)
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:16:38.046[warn](http://192.168.2.13/logs#) EchoApp (v4.2.3.0) | Echo Speaks Authentication is no longer valid... Please login again and commands will be allowed again!!! | Method: (checkGuardSupport)
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:14:14.035[warn](http://192.168.2.13/logs#) EchoApp (v4.2.3.0) | Amazon Cookie Has Expired or is Missing!!! Please login again using the Heroku Web Config page...
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:11:04.185[warn](http://192.168.2.13/logs#) EchoApp (v4.2.3.0) | Echo Speaks Authentication is no longer valid... Please login again and commands will be allowed again!!! | Method: (getEchoDevices)
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:07:23.427[error](http://192.168.2.13/logs#)EchoApp (v4.2.3.0) | wakeupServerResp Exception: java.lang.Exception: No response data exists for async request
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:07:23.419[error](http://192.168.2.13/logs#)EchoApp (v4.2.3.0) | wakeupServerResp | Stack Trace: java.lang.Exception: No response data exists for async request
at hubitat.scheduling.AsyncResponse.getData(AsyncResponse.groovy:71)
at user_app_tonesto7_Echo_Speaks_693.wakeupServerResp(user_app_tonesto7_Echo_Speaks_693.groovy:2232)
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:07:23.406[error](http://192.168.2.13/logs#)EchoApp (v4.2.3.0) | wakeupServerResp Server may be down / unreachable
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:07:23.400[warn](http://192.168.2.13/logs#) EchoApp (v4.2.3.0) | wakeupServerResp: 404
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:05:11.522[warn](http://192.168.2.13/logs#) EchoApp (v4.2.3.0) | Echo Speaks Authentication is no longer valid... Please login again and commands will be allowed again!!! | Method: (getEchoDevices)
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:05:11.472[info](http://192.168.2.13/logs#) EchoApp (v4.2.3.0) | sendMsg: Message Skipped Notification not configured or During Quiet Time (Echo Speaks Amazon Login Issue: Amazon Cookie Has Expired or is Missing!!! Please login again using the Local Server Web Config page...)
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:05:11.464[warn](http://192.168.2.13/logs#) EchoApp (v4.2.3.0) | Amazon Cookie Has Expired or is Missing!!! Please login again using the Local Server Web Config page...
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:05:11.452[warn](http://192.168.2.13/logs#) EchoApp (v4.2.3.0) | Cookie Data has been cleared and Device Data Refreshes have been suspended...
[app:1754](http://192.168.2.13/logs#)2024-02-04 12:05:11.391[error](http://192.168.2.13/logs#)EchoApp (v4.2.3.0) | The last 3 Authentication Validations have failed | Clearing Stored Auth Data | Please login again using the Echo Speaks service...

**Comment by tonyshor** [comment]
I am having the same problem where I get " 404 we couldn't find that page" when attempting to goto login page

![image](https://github.com/tonesto7/echo-speaks/assets/34520425/1cb75bae-7a77-4dfc-85d4-782c181aee92)

![image](https://github.com/tonesto7/echo-speaks/assets/34520425/346eb4f3-85dc-4318-bb97-1da283794a70)


I was able to deploy app to HEROKU successfully

![image](https://github.com/tonesto7/echo-speaks/assets/34520425/7ff3953e-fbb7-4baa-b553-b79499f9cd5a)

I deleted the app and re-added multiple times with no success. Not sure what i am doing wrong, Any suggestion? thanks

**Comment by tonyshor** [comment]
![image](https://github.com/tonesto7/echo-speaks/assets/34520425/fb47ddc2-9345-4330-8dc5-e338fec20045)
