### ISSUE TITLE
Fire Stick(s) Ignored 

### ISSUE THREAD

**Issue by Plados2** [tonesto7/echo-speaks#118]
This is probably not a "bug" but I'm stuck. Tried everything that I can imagine and need a little direction.
Have an Echo Show 5, two Fire Sticks (Gen 3) and an android mobile. All were working at one time, then it became sporadic among all TTS devices. Today I updated Echo Speaks (app/actions/device code) and redeployed the server. I only see the Echo Show as an "Installed Device". Both Fire Sticks show as "Unused Devices". When I expand on the tab it shows:

Bedroom TV
Status: (online)
Style: Fire TV Stick 4K (Gen3)
Family: Fire_TV
Type: AKPGW064G19HE
Volume Control: (True)
Text to Speech: (True)
Music Player: (False)
Reason Ignored: (Other Devices Not Enabled)

"Device Detection Preferences" are:
Auto Create: (Enabled)
Auto Rename

How do I add the Fire Sticks as "Installed Devices" and use as TTS devices?

-   [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-   [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-   [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-   [x] That ALL App/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

## About Your Setup:

-   Hub Platform: Hubitat)
-   How many devices are detected?:  1
-   Mobile App Version(Not required):
-   App/SmartApp Version: v3.0.2.0
-   Device Handler/Driver Version: v2.3.0
-   Heroku Server Version: v2.0

## Expected Behavior
Fire TV Sticks should be available as devices

## Current Behavior
Only showing one installed device

**Comment by tonesto7** [comment]
You just need to enable other devices under the device settings page
