### ISSUE TITLE
This Device Does NOT Support Volume Control!!!

### ISSUE THREAD

**Issue by tmleafs** [tonesto7/echo-speaks#12]
Currently cant change volume one any of my 2nd gen echos and 1st gen echos, I have no other echos to test with

`3c9148a2-7c13-4133-aa2f-3bbc5c6023b5  11:29:59 PM: warn This Device Does NOT Support Volume Control!!!
`

**Comment by tonesto7** [comment]
That means your server is not current.  The latest version of 1.3.0 server contains the volumeControl key based on the Amazon capability "VOLUME_SETTING"

**Comment by tmleafs** [comment]
Seems to take a while for all the new features of a updated server to take effect

**Comment by tonesto7** [comment]
Should just be a single refresh of the data (1 poll)
