### ISSUE TITLE
(BUG) 

### ISSUE THREAD

**Issue by mikeb0981** [tonesto7/echo-speaks#120]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): smartthings 
-  How many devices are detected?: 17
-  iOS or Android?:iOS 
-  Mobile App Version(Not required):
-  App/SmartApp Version: v3.1.0.1
-  Device Handler/Driver Version: v3.1.0.2
-  Heroku Server Version:v2.3.0

## Expected Behavior
When ONLY using SHM mode “armed home” as an event trigger no other SHM modes (armed away, disarmed) should trigger events

## Current Behavior
Even though only “Armed Home” is selected, both Armed away and disarmed trigger the speak event

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
When SHM is set to Armed Home I would like Echo speaks to notify if a garage door is open, however the notification occurs when SHM is set to Armed Home, Armed Away and Disarmed

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
I will verify this is resolved and if it’s not will get the fix out in the today’s maintenance release.
