### ISSUE TITLE
(BUG) Once per day per device is failing

### ISSUE THREAD

**Issue by benflux** [tonesto7/echo-speaks#122]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Hubitat
-  How many devices are detected?: 15
-  iOS or Android?: n/a
-  Mobile App Version(Not required): n/a
-  App/SmartApp Version: 3.1.0.2
-  Device Handler/Driver Version: 3.1.0.2
-  Heroku Server Version: v2.3.0

## Expected Behavior
Actions should only run once per day

## Current Behavior
Runs every time

## Steps to Reproduce (for bugs)

1. Create an action
2. Choose motion sensor as trigger
3. Select once per day
4. Choose action of compliment

## Context
I want the first person in the morning to get a good morning message in the kitchen, all other motion for the rest of the day will not get this message

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
I’m investigating this
