### ISSUE TITLE
(BUG) 

### ISSUE THREAD

**Issue by abernajb** [tonesto7/echo-speaks#126]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Smarththings
-  How many devices are detected?:20+
-  iOS or Android?:iOS
-  Mobile App Version(Not required):2.17.1(1442)
-  App/SmartApp Version: 3.2.0.5
-  Device Handler/Driver Version: 3.2.0.3
-  Heroku Server Version: 2.3.0

## Expected Behavior
When opening an action to edit that has the day of week restrictions added it would present the interface to edit the action. 

## Current Behavior
When attempting to open an action that has a day of week restriction added, the Smarththings app just spins

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Create new Action
2. Add Day of week action
3. Go back and edit.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

groovy.lang.MissingMethodException: No signature of method: script_app_29d5c6af872602c43b0afc5eaa9dccf97404432227e9ac8af19342d03771da3d.isMonthOfYear() is applicable for argument types: (org.codehaus.groovy.grails.web.json.JSONArray) values: [[January, February, March, April, May, October, November, December]] @line 2381 (dateCondOk)

**Comment by tonesto7** [comment]
Thanks for reporting.  I will review and get out the fix in the next release.
