### ISSUE TITLE
[Feature] Add Nest Thermostat presence as an option for enabling Alexa Guard

### ISSUE THREAD

**Issue by suprax** [tonesto7/echo-speaks#127]
For the Automate Guard Control feature within Echo Speaks, I'm not able to add my Nest Thermostat's presence as an option for the "Set Guard using Presence" setting.  Within SmartThings activity/messages, I see activity recorded for when the Nest presence changes (multiple phones have left the house and there is no motion detected within), so it would be great for Guard to be enabled and disabled based on this available data.

Thanks!

**Comment by tonesto7** [comment]
If you are using NST Manager then it should have created a presence device that can be used as a presence sensor

**Comment by suprax** [comment]
Great, I'll give this a try.  Thanks!
