### ISSUE TITLE
No Discovered Devices

### ISSUE THREAD

**Issue by tmleafs** [tonesto7/echo-speaks#13]
Message No Devices Available appears in the app 
But appear in the logs fine

**Comment by Mythris29** [comment]
I seem to be having the same issue. I haven't had it installed until today so maybe us new users are having issues?

**Comment by tonesto7** [comment]
@tmleafs @Mythris29 

I'm looking at this right now.  I'm trying to figure out why I'm not seeing the same issue

**Comment by Mythris29** [comment]
Let me know if I can provide anything that could be helpful in troubleshooting this...I should have known that the developer of the Nest bridging app would be involved in the coolest thing I've seen for Smartthings in a while :)

**Comment by tmleafs** [comment]
If I have all Tablets, Multiroom and other devices sliders off I get no devices appear i seem to have to turn them all on to get them to appear

**Comment by tonesto7** [comment]
What settings do you have enabled under the Echo Speaks smartapp in regards to auto device creation

**Comment by Mythris29** [comment]
Just "Auto Create New Devices" and "Rename Devices to Match Amazon Echo name" for me.

**Comment by tmleafs** [comment]
![screenshot_20181122-020646 1](https://user-images.githubusercontent.com/8752233/48877517-85132a00-edfb-11e8-910e-8a6c0ef1d477.jpg)

The sliders control what devices show up in decovered devices

**Comment by tonesto7** [comment]
I believe I may see the issue... 
Please overwrite your SmartApp code with this:
https://gist.github.com/tonesto7/0d2b6c923c9947375084be91bc4942b9

**Comment by tmleafs** [comment]
Still the same

**Comment by Mythris29** [comment]
That new code fixed it for me.

**Comment by tonesto7** [comment]
@tmleafs What are you seeing in the logs?

**Comment by tmleafs** [comment]
Okay it took its time but now only my Echo devices so up by default I take it this is how you intend it to be

**Comment by naseemr** [comment]
Same issue her, only device  echo speaks app is discovering is echo ( amazon alexa).

**Comment by glenmm** [comment]
I am seeing this issue today - I installed the latest software (automatically via your ST-Community-Installer app) -- all SmartApps (3) and DHs (1) show published in ST IDE.

After pressing Save, in the app I see (0) Installed devices 

There is a livelogging NullPointer exception from checkGuardSupport response: cannot get property LambdaBridge_AAA/OnGuardSmartHomeBridgeService
