### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by sgnihttrams** [tonesto7/echo-speaks#130]
Requesting device support from the following device(s):
type: ATH4K2BAIXVHQ
family: AMAZONMOBILEMUSIC_ANDROID

**Comment by sgnihttrams** [comment]
Sorry....I didn't customize this entry....just clicked the option within the SmartApp  lol

Another funny thing is that I'm not even exactly sure what this is. (I know)

I have a few different ES devices that were created for 'real' devices that aren't 'normal'. I think I have identified the others. Some are ones I still want to deal with and get them working if possible, but this one is just bugging me since I have no idea what it actually is.

If you're willing to work on it, let me know what else you need as far as info, screenshots, or whatever.

**Comment by tonesto7** [comment]
More than likely this will not be controllable.  
If you see other devices let me know and I can add them to the global json file the clients download every 6 hours.

**Comment by tonesto7** [comment]
I'm not sure how you are even seeing this.  AMAZONMOBILEMUSIC_ANDROID is on the global family block list.

Have you been modifying the code when trying to get the other devices working?

**Comment by sgnihttrams** [comment]
Do you mean the code for the Echo Speaks SmartApp? 
No. Well, nor any other code.  lol

It's funny, because that unit shows as 'Active' when I check on it in the IDE.
Well, it's also possible that I'm misunderstanding what that stuff means in there.  lol

**Comment by sgnihttrams** [comment]
In case it matters, the name it was created with by Echo Speaks is 
Name's Alexa Apps

I'm also attaching a screenshot of it in Echo Speaks...

![Screenshot_20191114-202356_SmartThings](https://user-images.githubusercontent.com/15355240/68912250-3ef65b00-071d-11ea-84cd-21368240dd93.jpg)

**Comment by tonesto7** [comment]
Yea this will not work like we hoped so it's been added to the block list again.
