### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by TonyFleisher** [tonesto7/echo-speaks#131]
Requesting device support from the following device(s):
type: A2ZOTUOF1IBEYI
family: UNKNOWN

Voyager 5200 Bluetooth headset
(Tap for Alexa)

Device status is always offline; doesn't appear to have any useable capabilities.

**Comment by tonesto7** [comment]
I'm adding this device to the global block list so it will no longer show up.  You should see the change in the next hour.  When you go into the smart app you will likely see a notice to remove unused devices.
