### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by mphel** [tonesto7/echo-speaks#132]
Requesting device support from the following device(s):
type: A1Q7QCGNMXAKYW
family: TABLET

**Comment by tonesto7** [comment]
What model tablet is this device?

**Comment by tonesto7** [comment]
I've added to the block list for now until more testing is performed

**Comment by mike-oconnor** [comment]
This is an Amazon Fire Table 7 (9th Generation).  I'm using one as a wall-mounted sharptool'ed control panel. 

I've tried it out - giving it the same capabilities as other Fire tablets - caps["a",  "t"] -  and it works just fine.  It would be nive to edit this in the main line so I won't have to go patch it up in my private copy each time there's a new release.
