### ISSUE TITLE
[ADD DEVICE SUPPORT] (2) Devices

### ISSUE THREAD

**Issue by phrankc** [tonesto7/echo-speaks#133]
Requesting device support from the following device(s):
type: A3NWHXTQ4EBCZS
family: MSHOP

type: A3VRME03NAXFUB
family: ECHO

**Comment by tonesto7** [comment]
What type of Echo device is this?  Model/generation?

**Comment by phrankc** [comment]
Both of these are the Alexa app on Windows 10 PS's.
See attached screen capture.

Frank
________________________________
