### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by rickydg** [tonesto7/echo-speaks#135]
Requesting device support from the following device(s):
type: A1W2YILXTG9HA7
family: ALEXA_AUTO

**Comment by rickydg** [comment]
Unlikely to be supported, but worth a go 😬

It’s the Nextbase 522GW dashcam

**Comment by tonesto7** [comment]
It's been added.  Just open the app and press done/save
