### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by therainkin** [tonesto7/echo-speaks#136]
Requesting device support from the following device(s):
type: A16MZVIFVHX6P6
family: ECHO

**Comment by tonesto7** [comment]
Can you tell me what kind of echo device this is?  Model, generation?

**Comment by therainkin** [comment]
Honestly, I'm it sure at this point.  The app asked me to report it, so I did.  I was goi g to mess with it today, so I'll try to figure out what it is.

- Chuck Miotla
717-552-8027

________________________________

**Comment by tonesto7** [comment]
I've added it to the detection file as a Generic Echo because the family is listed as ECHO which only applies to those types of devices.
