### ISSUE TITLE
[ADD DEVICE SUPPORT] (2) Devices

### ISSUE THREAD

**Issue by Shimitu** [tonesto7/echo-speaks#138]
Requesting device support from the following device(s):
type: A3TCJ8RTT3NVI7
family: UNKNOWN

type: A2JKHJ0PX4J3L3
family: FIRE_TV_CUBE - This is the second generation and has a built-in speaker so can function as a standard Echo Device.

**Comment by tonesto7** [comment]
Device 1 was added to the block list and device 2 was added the device matrix.  
Just open the smartapp and press done.
