### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by willima6** [tonesto7/echo-speaks#139]
Requesting device support from the following device(s):
type: A27VEYGQBW3YR5
family: ECHO

**Comment by tonesto7** [comment]
what kind of device is this? Model and Generation?

**Comment by willima6** [comment]
Amazon Echo Link - I am fairly certain there is only one generation for
this device

Thanks!

Mark

**Comment by tonesto7** [comment]
Thanks for reporting I will add the detection info this morning

**Comment by willima6** [comment]
First of all - I can't tell you how much I have enjoyed working with
Echo-Speaks - really cool stuff.  I recently built a fairly large home with
16 different audio zones and 30+ various echo devices located throughout
the house.  I am using Echo-Speaks extensively throughout my house - like a
kid in a candy store - love it!

Anyway - I wanted to give you a quick enhancement request.  Would love to
see a shuffle function for playlists.  Currently, when I play a Spotify
playlist on a particular zone it always starts from the top of the list.  I
would love the option to mix it up a bit more and shuffle the playlist.  Is
that possible?  Happy to pay you something to add this to your list.

Again - thank you for your work on this.  Can't tell you how much fun I am
having - endless possibilities!

Mark

**Comment by willima6** [comment]
Hey - wanted to reach out and say excellent job with Echo Speaks on Hubitat
- really cool stuff!

I know you probably get hit with a ton of support questions and I want to
be respectful of your time.  Just to be clear, I am more than willing to
pay you for your time to fix an issue that I have been struggling with
on my Hubitat environment.  Here is the situation:

I have a bunch of Echo Link devices throughout my home – basically one for
each audio zone in my house. I use them so I can have voice-controlled
music throughout my house via Alexa. They enable me to say things like
“Echo, play Sheryl Crow in Kitchen” and have higher quality sound come
through my whole house audio system instead of a dot for example. It works
fantastic for that application.

Now, I am trying to tie these Echo Link devices into my Hubitat environment
via Echo Speaks but I am having some problems. ES recognizes the Echo Links
and creates a device for each of them – no problem (same as all the other
Echo devices I have set up – dots, shows, flexes, etc).

The problem is when I create an Action in ES and try to select an Echo Link
as the audio destination nothing happens – no sound at all. I know the
event is getting triggered, because when I change the audio destination to
a dot, show or any other echo device it works perfectly. It just does not
like my Echo Links for some reason. I know the Echo Links are working
properly because they work perfectly when I push audio to them via Alexa
directly. It feels like maybe there is an ES driver issue with these Echo
Links. I am pulling my hair out trying to figure it out. Any suggestions?

Happy to provide you with whatever documentation you need (screen shots,
logs, video recordings, etc).

Thanks so much for your consideration - I will definitely contribute to
your program if you can help me solve this issue.

Mark
