### ISSUE TITLE
Speaker companion and 'Play a notification'

### ISSUE THREAD

**Issue by barabba9174** [tonesto7/echo-speaks#14]
Hi,
I was trying the Speaker Companion smartapp using Echo instead of Sonos. 
'Control - play/stop/pause/skip' sub-app can find the device, 'Play a notification' not. I had a look to the code (I guess the second is https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/61b864535321a6f61cf5a77216f1e779bde68bd5/smartapps/smartthings/speaker-notify-with-sound.src/speaker-notify-with-sound.groovy) compared with the first https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/61b864535321a6f61cf5a77216f1e779bde68bd5/smartapps/smartthings/speaker-control.src/speaker-control.groovy. 
The capabilities are identical and the 'speak' method is available. Do you have any idea about why the first can find the device and the second not at all?

**Comment by barabba9174** [comment]
I've checked again, both the linked apps work perfectly, but not Speaker Companion.

**Comment by golanremi** [comment]
@barabba9174 How did you get it fixed, I still have this problem. BTW, Speaker companion works perfectly with Sonos
