### ISSUE TITLE
[ADD DEVICE SUPPORT] (2) Devices

### ISSUE THREAD

**Issue by DarcRanger** [tonesto7/echo-speaks#144]
Requesting device support from the following device(s):
type: A29L394LN0I8HN
family: UNKNOWN

type: A2XPGY5LRKB9BE
family: UNKNOWN

**Comment by tonesto7** [comment]
Thanks for reporting these.

These are unknown devices that have been blocked in the AppData file.  They will automatically be hidden from the app next time the appdata file is updated
