### ISSUE TITLE
[ADD DEVICE SUPPORT] (2) Devices

### ISSUE THREAD

**Issue by bob5731** [tonesto7/echo-speaks#145]
I'm now getting a network server error can't reach server.
How long with it not speaking any of my actions.

Requesting device support from the following device(s):
type: A1VS6XVTGTLC00
family: UNKNOWN

type: A2C8J6UHV0KFCV
family: UNKNOWN

**Comment by tonesto7** [comment]
Thanks for reporting!

These are unknown devices that have been blocked in the AppData file.  They will automatically be hidden from the app next time the appdata file is updated
