### ISSUE TITLE
[Feature Request] Add Playback/Volume Control Action

### ISSUE THREAD

**Issue by andyjkr** [tonesto7/echo-speaks#147]
There is no location to input a desired volume. I get that with webCore it goes in as an integer, and that has yet to work in any way shape or form either. But within the echo speaks smart app, when setting up an action, there is no place to tell the app what volume to set. Seems pretty much like a gigantic oversight.

**Comment by tonesto7** [comment]
I’m not really sure how to respond to this as volume control is very much there in actions.  Maybe you should include more details as to what type of action you are creating.

**Comment by RichardaBeck** [comment]
I think I am having the same issue. I created an action specifically to lower the volume of my echo devices at a certain time. My config is:
Action Type: Playback/Volume Control
Triggers: 12pm every day
Conditions: none
**Execution Config: All Echos - Select Playback Action: Volume**
There isn't a field to set the volume of the device on this page. (or any other page/setting). Your examples show a volume % but I do not see it here.

**Comment by andyjkr** [comment]
Yes. There is a volume ACTION, but no command. It just says volume. Not up, not down, not mute, not lower by percentage, not set to level. Nothing. Maybe be less sure of yourself and be more willing to look into issues. Even bigger issue. Volume set commands do nothing. They are received by the individual devices. I see that in the logs. The volume commands make no difference, as they don't change the volume.

**Comment by andyjkr** [comment]
[Video of attempts to set volume through app](https://drive.google.com/open?id=1HUV7JUa_eg0SR8bj9fPtJQs0iubPx92a)

**Comment by tonesto7** [comment]
I’m tied up with work travel today but will take a look this weekend

**Comment by RichardaBeck** [comment]
tonesto7,

I greatly appreciate it! Thanks for taking the time to make cool stuff like this!

**Comment by andyjkr** [comment]
Well right on. I am accustomed to no response so I appreciate you even taking that time. 

> On Nov 22, 2019, at 5:31 AM, Tonesto7 <notifications@github.com> wrote:
> 

﻿
I’m tied up with work travel today but will take a look this weekend

**Comment by andyjkr** [comment]
Ok. Addition to initial bug report. As far as triggering a routine, or to play music through webCoRE, that appears to be a no go as well. At least with how I have it setup, which is to play a routine or to search amazon music directly after a volume command has been sent. No matter what, webCoRE registers the event and the logs say the piston executed, the device logs say the routine executed, but the routine or song does not execute. In my attempts to get yes to work, I’m finding scheduled pistons do not reach amazon. All the behavior I just described takes place for certain on the first click of test in webCoRE. The second click returns desired results. 

Lastly, I did update all the codes to the latest version. I can set volume through the app now for an action, but I prefer to have all of my Logic for SmartThings happen on webCoRE for simplicity. I have only been with echo speaks for about a week and don’t know If actions can be triggered by web core, or if echo speaks actions are more stable, since I’ve been determined to build Be easily edited distance for Alexa routines that your app provide functions I’ve wanted for quite some time. I will look into that myself. Another reason for using webCoRE to test the features of echo speaks, is that in the music testing section of the echo speaks app, when selecting which device to test on, I am given the message that I have no devices with this functionality. I do arbor have several echo classes, echo dots, echo shows, and some other echo nonsense. So I’m sure this is a bug. 

Sorry this is so long, but one last thing. And if I should file a new feature request for this, just let me know. I’m also building something of a interactive Alexa routine on webCoRE Thanks to echo speaks. It would be great if there a way to trigger Alexa to listen after Speaking some text, and use the response given as a selector got the next statement. I’m sure this Be possible with the Alexa skills building kit or whatever it is, but that is so far beyond my capabilities.

**Comment by RichardaBeck** [comment]
I see that you've made a ton of updates over the last month but I dont thinknyou added this feature (to lower the device level). Is that correct? 

Also, appreciate all the new stuff. Very nice!

**Comment by tonesto7** [comment]
@andyjkr @RichardaBeck I've corrected this issue and will be deploying the update this evening.

**Comment by RichardaBeck** [comment]
NICE!

**Comment by tonesto7** [comment]
I had some surprises at work that put me behind so I'm not 100% certain I will be releasing anything tonight.
I have a couple more features I want to deploy with the next release so hopefully, I can nail those down quickly
