### ISSUE TITLE
[ADD DEVICE SUPPORT] (2) Devices

### ISSUE THREAD

**Issue by MikeGuest** [tonesto7/echo-speaks#148]
Requesting device support from the following device(s):
type: AVE5HX13UR5NO
family: ALEXA_AUTO

type: AVE5HX13UR5NO
family: ALEXA_AUTO

I believe these are two Logitech zerotouch devices. I don't actually user then any more but I pass on the details in case they are of use to other users

**Comment by tonesto7** [comment]
These device identifiers have been added to the AppData file.  They will automatically be detected the next app time the appdata file is updated by the app
