### ISSUE TITLE
[ADD DEVICE SUPPORT] (2) Devices

### ISSUE THREAD

**Issue by kofseattle** [tonesto7/echo-speaks#149]
Requesting device support from the following device(s):
type: A2Y04QPFCANLPQ
family: UNKNOWN

type: ATH4K2BAIXVHQ
family: AMAZONMOBILEMUSIC_ANDROID

**Comment by tonesto7** [comment]
These are unknown devices that have been blocked in the AppData file.  They will automatically be hidden from the app next time the appdata file is updated
