### ISSUE TITLE
TLS on authentication page

### ISSUE THREAD

**Issue by slonob** [tonesto7/echo-speaks#15]
https://github.com/tonesto7/echo-speaks/blob/79727ddc94d4fe8a5dac4bcde594a26ec069eee8/smartapps/tonesto7/echo-speaks.src/echo-speaks.groovy#L484

I don't have the time to chase this down as well as I could, but I believe that the way the hostUrl is being constructed results in calling the Amazon authentication page using cleartext (from Heroku).  These envs are added as params here: https://github.com/tonesto7/echo-speaks/blob/79727ddc94d4fe8a5dac4bcde594a26ec069eee8/smartapps/tonesto7/echo-speaks.src/echo-speaks.groovy#L1522

I wonder if you could simply prepend "https://" to hostUrl. Might require encoding to be properly handled as a param.

Of course, this results in exposure of Amazon credentials if the plaintext call is made.  Anyone who has tried this app should 1) change your Amazon password and 2) enable MFA to be ensure that this kind of exposure won't be useful to anyone who captures your credentials.  

Note that I'm not sure if there's variability in who experiences this based on configurations outside of the author's control.  I'm certain it happened to me.

In the mobile context, this is difficult to spot so you (the user) might think you're fine but you could have missed it.

**Comment by TonyFleisher** [comment]
I think the proper fix for this is both ensuring the link from app uses https and for the echo-speaks-server to ensure that the connection is secure using both redirect and hsts

**Comment by tonesto7** [comment]
This has been corrected as of v2.0.2 of the server
