### ISSUE TITLE
Heroku service page reports a bogus update

### ISSUE THREAD

**Issue by robross0606** [tonesto7/echo-speaks#150]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [X] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [X] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): SmartThings
-  How many devices are detected?: 6
-  iOS or Android?: Android
-  Mobile App Version(Not required): 
-  App/SmartApp Version: 3.2.1.0
-  Device Handler/Driver Version: 3.2.1.0 
-  Heroku Server Version: 2.3.0

## Expected Behavior
Service page would properly report that I am on the latest version or an update to a valid new version.

## Current Behavior
The Echo Speaks Service reports v2.3.0 but then in big red letters says "(Update Available: 2.2.3)".  This is reporting an update that is older than my current version.  As far as I can tell, I have the latest version.
![screenshot-echo-speaks-nlteklt9p herokuapp com-2019 11 22-00_35_07](https://user-images.githubusercontent.com/2965467/69400522-fc55f500-0cbf-11ea-8a55-8ba23fc1925c.png)

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Follow installation and configuration instructions precisely.
2. Visit deployed app page on heroku

## Context
Unclear if I have a problem or not.  From what I can tell via this site, 2.3.0 is the latest service code for heroku.

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
Thanks for reporting this.  I've pushed out a new server version 2.3.1 to address this
