### ISSUE TITLE
Echo Speaks does not work on devices shared in a "Household" setup

### ISSUE THREAD

**Issue by robross0606** [tonesto7/echo-speaks#151]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [X] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [X] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
Hub Platform (SmartThings or Hubitat): SmartThings
How many devices are detected?: 6
iOS or Android?: Android
Mobile App Version(Not required):
App/SmartApp Version: 3.2.2.1
Device Handler/Driver Version: 3.2.2.1
Heroku Server Version: 2.3.0

## Expected Behavior
Ability to use Echo speakers as output devices through SmartThings using shared "household" setup.

## Current Behavior
I've tried walking through the full set of instructions twice.  My Amazon account is in a family shared setup with my wife who "owns" the Echo devices.  When using my account, all the devices appear in Echo Speaks.  It reports zero problems during setup or in the smart app.  It detects all devices and shows correct information about them including make, model, version, capabilities, etc.  However, it is impossible to control any of them.  All buttons tiles are black instead of red.  No actions or triggers work at all.  I switched it to log into Amazon with my wife's account and everything started working.  There's clearly something not working properly when devices are shared among several family members in a household.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Stepped through setup from scratch using latest documentation. Confirmed every part of every step matched instructions.  No errors at all during setup process.
2. When logging into Amazon, use an account which has full secondary access to the Echo devices shared in a "household" setup.
3. Smart app reports everything is "OK", with successful login, valid cookies, oauth, etc.
4. Attempt to test a device or trigger an action manually from a tile in the SmartThings app.

## Context
Lack of actual error messages of any kind made this very difficult to debug.  I simply figured it out on a hunch.

**Comment by kreene1987** [comment]
Just wanted to add to this for more insight, ONE of my owned devices is working perfectly, and the other (also owned by my amazon account) is not working at all. I have not yet tested from scratch ensuring both are in my account **mode**, but my amazon account is the owner of both devices. 
My logs for the non-working device (Echo Show v2) show the following:

> 1fdf4bba-6ab6-4316-93f7-085889f5e6c7 10:16:06 AM: error Echo (v3.3.0.1) | SequenceCommand (sayGoodNight) | Status: (400) | Message: Bad Request | Data: [message:Input failed to validate.]
> 1fdf4bba-6ab6-4316-93f7-085889f5e6c7 10:15:56 AM: error Echo (v3.3.0.1) | SequenceCommand (sayGoodNight) | Status: (400) | Message: Bad Request | Data: [message:Input failed to validate.]
> 1fdf4bba-6ab6-4316-93f7-085889f5e6c7 10:15:46 AM: error Echo (v3.3.0.1) | SequenceCommand (sayGoodNight) | Status: (400) | Message: Bad Request | Data: [message:Input failed to validate.]
> 1fdf4bba-6ab6-4316-93f7-085889f5e6c7 10:15:36 AM: error Echo (v3.3.0.1) | SequenceCommand (sayGoodNight) | Status: (400) | Message: Bad Request | Data: [message:Input failed to validate.]
> 1fdf4bba-6ab6-4316-93f7-085889f5e6c7 10:15:26 AM: error Echo (v3.3.0.1) | SequenceCommand (sayGoodNight) | Status: (400) | Message: Bad Request | Data: [message:Input failed to validate.]
> 1fdf4bba-6ab6-4316-93f7-085889f5e6c7 10:15:16 AM: error Echo (v3.3.0.1) | SequenceCommand (sayGoodNight) | Status: (400) | Message: Bad Request | Data: [message:Input failed to validate.]
> 1fdf4bba-6ab6-4316-93f7-085889f5e6c7 10:15:06 AM: error Echo (v3.3.0.1) | SequenceCommand (sayGoodNight) | Status: (400) | Message: Bad Request | Data: [message:Input failed to validate.]
> 1fdf4bba-6ab6-4316-93f7-085889f5e6c7 10:14:56 AM: error Echo (v3.3.0.1) | SequenceCommand (sayGoodNight) | Status: (400) | Message: Bad Request | Data: [message:Input failed to validate.]
> 1fdf4bba-6ab6-4316-93f7-085889f5e6c7 10:14:46 AM: error Echo (v3.3.0.1) | SequenceCommand (sayGoodNight) | Status: (400) | Message: Bad Request | Data: [message:Input failed to validate.]
> 1fdf4bba-6ab6-4316-93f7-085889f5e6c7 10:14:36 AM: error Echo (v3.3.0.1) | SequenceCommand (sayGoodNight) | Status: (400) | Message: Bad Request | Data: [message:Input failed to validate.]
> 1fdf4bba-6ab6-4316-93f7-085889f5e6c7 10:10:54 AM: error Echo (v3.3.0.1) | SequenceCommand (VolumeCommand) | Status: (400) | Message: Bad Request | Data: [message:Input failed to validate.]
> 1fdf4bba-6ab6-4316-93f7-085889f5e6c7 10:09:59 AM: error Echo (v3.3.0.1) | PlayCommand Response Exception | Status: (404) | Msg: Not Found
> 1fdf4bba-6ab6-4316-93f7-085889f5e6c7 10:09:42 AM: error Echo (v3.3.0.1) | SequenceCommand (sayGoodNight) | Status: (400) | Message: Bad Request | Data: [message:Input failed to validate.]
> 1fdf4bba-6ab6-4316-93f7-085889f5e6c7 10:05:14 AM: error Echo (v3.3.0.1) | SequenceCommand (sayGoodMorning) | Status: (400) | Message: Bad Request | Data: [message:Input failed to validate.]

Unsure if related or not, just wanted to add my data point since it might be related.

**Comment by abeezarburhan** [comment]
it seems my Echo were registered to my wife's account. Changed the login to hers and it started working

**Comment by Dogbreath6861** [comment]
Ok, what if you want to use both devices and one is registered to me and the other registered to my wife?
