### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by hogieaz** [tonesto7/echo-speaks#152]
Requesting device support from the following device(s):
type: A1Z88NGR2BK6A2
family: KNIGHT

**Comment by tonesto7** [comment]
What type of Echo Device is this?
The KNIGHT family is usually an Echo Show

**Comment by hogieaz** [comment]
I have 2 echo show 1st Gen so not sure if this is one.

I have 2 1st Gen Taps that seem to have an issue as well.

But what you have built here is awesome.

Steve Holgerson
Schphx@cox.net

________________________________
