### ISSUE TITLE
(BUG) error creating sequence action

### ISSUE THREAD

**Issue by TonyFleisher** [tonesto7/echo-speaks#153]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):
-  How many devices are detected?:
-  iOS or Android?:
-  Mobile App Version(Not required):
-  App/SmartApp Version: v3.2.2.1
-  Device Handler/Driver Version: v3.2.2.1
-  Heroku Server Version:

## Expected Behavior
**tell us what should happen**
Able to create sequence action
## Current Behavior
**What happens instead of the expected behavior?**
App goes to white screen while creating action
## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Create action
2. Type: Sequence
3.  Trigger: Switch ....
4. Go to Part 4 config
5. Select echo speaks device
Result is blank screen with save button that fails and log as below.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

groovy.lang.MissingMethodException: No signature of method: script_app_3cf36bda88d3134058356802098225a21d97ea1af8e25b81e0cbdad2fbaa391b.pTS() is applicable for argument types: (java.lang.String, null, java.lang.Boolean, java.lang.Boolean, java.lang.String) values: [Enter the command in a format exactly like this:
volume::40,, speak::this is so silly,, wait::60,, weather,, cannedtts_random::goodbye,, traffic,, amazonmusic::green day,, volume::30

Each command needs to be separated by a double comma `,,` and the separator between the command and value must be command::value., ...]

**Comment by tonesto7** [comment]
this will be resolved in todays v3.3 release.
