### ISSUE TITLE
[Feature Request] Support Amazon Sounds in sequence

### ISSUE THREAD

**Issue by TonyFleisher** [tonesto7/echo-speaks#154]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Amazon routines now allow sound effects to be selected from a 2-tiered list. would be nice if we can add these in sequences like the cannedtts
**Describe alternatives you've considered**

Some use cases could be handled with alexa routines, but the sequence is a little more flexible.

**Additional context**

Example Payload (sounds -> scifi -> sirens) ("Play Sirens"):
```
					{
						"@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
						"type": "Alexa.Sound",
						"skillId": "amzn1.ask.1p.sound",
						"operationPayload": {
							"customerId": "XXXXXXXXXX",
							"deviceType": "ALEXA_CURRENT_DEVICE_TYPE",
							"deviceSerialNumber": "ALEXA_CURRENT_DSN",
							"soundStringId": "amzn_sfx_scifi_alarm_01",
							"locale": "en-US"
						},
						"name": null
					}
```

**Comment by tonesto7** [comment]
Will be v3.3 release
