### ISSUE TITLE
[ADD DEVICE SUPPORT] (3) Devices

### ISSUE THREAD

**Issue by andyjkr** [tonesto7/echo-speaks#155]
Requesting device support from the following device(s):
type: A1ORT4KZ23OY88
family: HENDRIX

type: A25EC4GIHFOCSG
family: THIRD_PARTY_AVS_MEDIA_DISPLAY

type: A25EC4GIHFOCSG
family: THIRD_PARTY_AVS_MEDIA_DISPLAY

**Comment by tonesto7** [comment]
These are unknown devices that have been blocked in the AppData file.  They will automatically be hidden from the app next time the appdata file is updated.
