### ISSUE TITLE
(BUG) phantom zone persisting and refuses to be deleted

### ISSUE THREAD

**Issue by zuhairmahd** [tonesto7/echo-speaks#156]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):
-  How many devices are detected?:
-  iOS or Android?:
-  Mobile App Version(Not required):
-  App/SmartApp Version:
-  Device Handler/Driver Version:
-  Heroku Server Version:

## Expected Behavior
**tell us what should happen**

## Current Behavior
**What happens instead of the expected behavior?**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug
When the Zones companion app was first released, I created a zone named “test” which I subsequently deleted.  Now on the main app screen, the Zones app is showing the active zone as “test”, but when I go into the Zones app, “test” is not there. Attempting to create a zone with the name “test” creates a “test (suffix added)”. I assume that the earlier versions didn’t fully delete the zone, but I now can’t find it to delete it. Thx.

**Comment by zuhairmahd** [comment]
Forgot to mention I’m running the latest release dated 11-18 on the Smartthings platform with a V2 hub running the latest release firmware.  I’m using the Smartthings Classic app on iOS 13.2.3 on an iPhone 8.

**Comment by tonesto7** [comment]
I'm trying to duplicate this but can't. 

Under the IDE goto > My Locations > SmartApps > Scroll down to the echo speaks section and look for the child app.  Scroll back to the top and click on edit and scroll back down to the app you need to remove and click uninstall.  (BE CAREFUL: It's easy to accidentally click on other apps and remove them)

**Comment by zuhairmahd** [comment]
I will try that and report back today.

**Comment by zuhairmahd** [comment]
@tonesto7 I did, but the only child app I found was an action named "Test" which I created earlier today.  I guess I expected to see the other child apps (Zone Companion, Action Companion, etc.).  Also strangely enough, when I created the "Test" action earlier today, it was renamed to Test (a), suggesting that the app think there is already an action named "Test", but no action named "Test" shows up in the Action Companion app.  I'm sure I previously created and deleted an "Test" action before.  Any other ideas?  Can I uninstall the Zone and Action apps from the IDE and redownload them from GitHub?  Would that clean up their data?  Does the application implement any "cleanup" mechanism?  Thanks a bunch.

**Comment by tonesto7** [comment]
@zuhairmahd  Sorry i've been MIA i'm working on this now.  It seems to be an issue in the zones reporting and checkin methods in the app.

**Comment by zuhairmahd** [comment]
@tonesto7  no worries — it’s the holiday season. :-)  it seems to happen in both zones and actions, although I first noticed it in Zones. Thx a bunch.

**Comment by tonesto7** [comment]
It's a cleanup bug when the zones get removed there was a typo in the name for event.  
I have it fixed and will have the patch out tonight.

**Comment by zuhairmahd** [comment]
@tonesto7  I downloaded 3301 and made sure the app update went through, but I am still seeing my phantom zone. In the release notes, it states “   • ADDED: Zone Maintenance section to pause/unpause all zones as well as clear all stored zone data and force all zones to report in.” but for the life of me I can’t find where that is. Thanks.

**Comment by tonesto7** [comment]
@zuhairmahd  Sorry, I never replied! Were you able to solve this?

**Comment by zuhairmahd** [comment]
Sort of. The feature to clean up zones does not show up unless you have at least one zone created (which sort of makes sense, because why would you clean up zones if you don't have any in the first place?) except that was not the case here.  The phantom zone was the only one I created.  Creating a new zone made the button appear, but it did not erase the phantom zone.  I had to reinstall the app.  Given this case, would it make sense to be able to update all zones even if none seem to exist?

**Comment by tonesto7** [comment]
Just to clarify.  Are you seeing the phantom zone under the Echo Speaks app or Echo Speaks - Actions?

**Comment by zuhairmahd** [comment]
The app, not the actions.

**Comment by zuhairmahd** [comment]
This has certainly been fixed. Thanks for the hard work.
