### ISSUE TITLE
Adding a new Echo device removed my Echo devices

### ISSUE THREAD

**Issue by rabramov1** [tonesto7/echo-speaks#157]
Hi,

My system had 4 echo devices, when I have installed Echo Speaks couple of weeks ago all 4 were identified. Each one appeared on my SmartThings app and could be accessed and controlled by ST and webcore.
Today I have added a new Echo dot 3rd gen to my home. It was added by the Echo app and works fine.
What happened in smartthings however was that all my previous 4 devices were effected by this addition. Each of the older Echo devices are now called "Tiles Missing" and the new device doesn't show anywhere in ST.

My code was very recent but I still updated it to the latest, I have rebooted the hub. So far no luck, 5 devices are now not accessible to ST. 

BTW Kudos for a very nice tool

Thanks,
Ron

**Comment by tonesto7** [comment]
This happens when you overwrite the device handler code with something else like the smart app code

**Comment by rabramov1** [comment]
Thanks, that was the issue
Appreciate your fast responce
Ron

 
 
  On Mon, Nov 25, 2019 at 2:35 PM, Tonesto7<notifications@github.com> wrote:   
This happens when you overwrite the device handler code with something else like the smart app code
