### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by alextheangel** [tonesto7/echo-speaks#159]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS) facebook portal
family: MMSDK
name: Dining Room Portal
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode
type: A2HZENIFNYTXZD

**Comment by tonesto7** [comment]
added... thanks for reporting
