### ISSUE TITLE
Data refresh issue notification where there is no issue

### ISSUE THREAD

**Issue by rickydg** [tonesto7/echo-speaks#16]
Currently running 1.3.0 on both app and Heroku on UK account. Was one of the users with the cookie expiration issue.

I now have it working consistently, but am still receiving notifications claiming the contrary!

**Comment by tmleafs** [comment]
How have you managed to get it working consistently?

**Comment by tonesto7** [comment]
This issue should be resolved in V2.0

**Comment by tonesto7** [comment]
duplicate of #5
