### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by tmleafs** [tonesto7/echo-speaks#160]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: TABLET
name: Steven's 2nd Fire
permissions: volumeControl, spotify, alarms, reminders, microphone
type: A1ZB65LA390I4K

**Comment by tonesto7** [comment]
i had to add this to the block list because it doesn't support any features required.
