### ISSUE TITLE
(BUG) 

### ISSUE THREAD

**Issue by mightybuffalo2000** [tonesto7/echo-speaks#161]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):
-  How many devices are detected?:
-  iOS or Android?:
-  Mobile App Version(Not required):
-  App/SmartApp Version:
-  Device Handler/Driver Version:
-  Heroku Server Version:

## Expected Behavior
**tell us what should happen**

## Current Behavior
**What happens instead of the expected behavior?**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

The notifications portion of the smartapp doesn't work for me anymore. It just says something went wrong. It happened about 3 updates ago. 
---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
@mightybuffalo2000 are we talking about the main app or actions app?

I'm not able to duplicate this in any way?

**Comment by adidamty** [comment]
@tonesto7 Echo Speaks not working anymore, since 8 of September 2020 - i am getting popup message in SmartThing app when trying to add smartApp - "Something went wrong. Please try to install the smartApp again". Same as described here - https://community.smartthings.com/t/cant-add-echo-speaks-as-a-smartapp/206570
