### ISSUE TITLE
[ADD DEVICE SUPPORT] (3) Devices

### ISSUE THREAD

**Issue by BC5280** [tonesto7/echo-speaks#165]
Requesting device support from the following device(s):
description: What kind of device/model?
Bose SoundTouch 30
family: THIRD_PARTY_AVS_MEDIA_DISPLAY
name: Living Room Bose
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, reminders
type: A1H0CMF1XM0ZP4

description: What kind of device/model? Bose SoundTouch 10
family: THIRD_PARTY_AVS_MEDIA_DISPLAY
name: Master Bedroom Speaker
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, reminders
type: A1H0CMF1XM0ZP4

description: What kind of device/model? Bose SoundTouch 10
family: THIRD_PARTY_AVS_MEDIA_DISPLAY
name: Kitchen Bose
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, reminders
type: A1H0CMF1XM0ZP4

**Comment by tonesto7** [comment]
this has been added to manifest as blocked for now until more testing can be achieved.
