### ISSUE TITLE
(ACTIONS BUG) 

### ISSUE THREAD

**Issue by cbarth3** [tonesto7/echo-speaks#166]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):smartthings 
-  How many devices are detected?:26
-  iOS or Android?:android 
-  Mobile App Version(Not required):
-  App/SmartApp Version:3.3.0.0
-  Device Handler/Driver Version:3.3.0.0
-  Heroku Server Version:2.3.0

## Expected Behavior
**tell us what should happen**
Action is created successfully 
## Current Behavior
**What happens instead of the expected behavior?** first time trying to save it days an unexpected error occured. I can hit save again and it will save but the action doesn't seem to work.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
@cbarth3  Can you provide more details on this?

**Comment by cbarth3** [comment]
![Screenshot_20191208-211615_SmartThings](https://user-images.githubusercontent.com/27602300/70404601-3fbe9c00-1a00-11ea-82cb-664eff48a42c.jpg)
![Screenshot_20191208-211633_SmartThings](https://user-images.githubusercontent.com/27602300/70404604-42b98c80-1a00-11ea-98d8-e6d332a83d5b.jpg)

When I try to create an action I get this unexpected error when saving

**Comment by tonesto7** [comment]
Let it sit for a second after entering the label and see if it still errors.
