### ISSUE TITLE
[Actions Feature Request]

### ISSUE THREAD

**Issue by jaconde2** [tonesto7/echo-speaks#167]
**Is your feature request related to a problem? Please describe.**
Hi tony, I'm an old user of your NST Manager for Smartthings. I moved from Los Angeles to Madrid (Spain) a year ago, and also moved to Hubitat. Today I installed your echo-speaks app and found there was no option for my new domain amazon.es and my locale es-ES. I inserted them into your code, and it's working like a charm. :-)

**Describe the solution you'd like**
If you don't mind, would you be so kind to include domain amazon.es and locale es-ES in your next upgrade, please? Thank you.

Again, thank you for your good work!

**Comment by tonesto7** [comment]
Yes I will definitely get this added

**Comment by tonesto7** [comment]
Ok this was just added and pushed out
