### ISSUE TITLE
Play track not working

### ISSUE THREAD

**Issue by rp1783** [tonesto7/echo-speaks#169]
![image](https://user-images.githubusercontent.com/228389/70363730-d3e50380-1846-11ea-9efd-b86ebd8a9fba.png)

I cannot get ES to play a file from a url. I've tried multiple hosting platforms and different file types, but nothing happens. the logs appear to show the action taking place, but nothing plays on the echo. The Speak argument works fine and it will speak any text I type. 

filename obfuscated for security reasons.

**Comment by tonesto7** [comment]
This will never work because amazon doesn’t allow us to play third party media.  
The only reason you see that command is because it comes standard with the Media Player Capability

**Comment by rp1783** [comment]
Oh interesting, I thought I’d seen others using ES for hosted files. Is there a way to accomplish this with local media?

**Comment by tonesto7** [comment]
If there is I haven't seen a way to do it.
