### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by morristonm36** [tonesto7/echo-speaks#170]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: UNKNOWN
name: Mark's Home Remote
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, doNotDisturb, microphone, followUpMode
type: A81PNL0A63P93

**Comment by tonesto7** [comment]
added to list as a blocked device
