### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by tasi333** [tonesto7/echo-speaks#172]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: THIRD_PARTY_AVS_SONOS_BOOTLEG
name: Tariq's Sonos One Second Edition
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode
type: AVD3HM0HOJAAL

**Comment by tonesto7** [comment]
added to list
