### ISSUE TITLE
(BUG) Search Music Command with MRM group caused devices out of sync

### ISSUE THREAD

**Issue by jamesguitar3** [tonesto7/echo-speaks#173]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): SmartThings
-  How many devices are detected?: 2
-  iOS or Android?: Android
-  Mobile App Version(Not required):
-  App/SmartApp Version: v3.3.0.1
-  Device Handler/Driver Version: v3.3.0.1
-  Heroku Server Version: v2.3.1

## Expected Behavior
Send command `searchSpotify("Beatles on All Speakers")` where 'All Speakers' is the MRM group name --> Correct music is played on all devices in MRM group 
Then send another command `searchSpotify("Eagles")` to one of the echo device -> Correct music is played but should be only on this specific device

When mixed the search music commands with and without "on the MRM group name" argument, the music is expected to play on all MRM devices or specific device explicitly.  

And the playback and audioData should be correctly reported on either devices based on the commands.

## Current Behavior
Send command `searchSpotify("Beatles on All Speakers")` where 'All Speakers' is the MRM group name --> Correct music played on all devices in MRM group 
Then send another command `searchSpotify("Eagles")` to one of the echo device -> Correct music played but **still on all devices in MRM group**

And the playback & audioData are out of sync between echos and reported in Echo Speaks.

## Steps to Reproduce (for bugs)
1. Create a MRM group called "All speakers" in Alexa app and add multiple echo devices in the group
2. Send a `searchSpotify("Beatles on All speakers") from any of the Echo Speaks devices
3. Music should play on all echo devices defined in the MRM
4. Send another command `searchSpotify("Eagles") from a specific Echo Speaks device
5. Music supposed to be played only on this echo device, but instead it will play on all devices still
6. Go to ST app and stop the MRM (WHA) device and individual Echo Speaks device
7 Send command in step4 again, and music is played on the specific Echo Speaks device, but now the playback and audioData is out of sync on the Echo Speaks device from the real echo.

## Context
**How has this issue affected you? What are you trying to accomplish?
Incorrect command execution results in certain cases. 
**Providing context helps us come up with a solution that is most useful in the real world**
User creates different webCoRe or SharpTools rules to play music on MRM or specific echo, but the result may be different than expected.
---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
@jamesguitar3 I don't think this is something that I can fix.  I see this happen all the time using the native alexa app.  
Honestly, amazon's multiroom design is a mess.

I'm open to PR's and such if you would like to try it on your own.
