### ISSUE TITLE
[ISSUE] No Devices are Showing Up in SmartThings

### ISSUE THREAD

**Issue by plasterer41** [tonesto7/echo-speaks#176]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):
-  How many devices are detected?:
-  iOS or Android?:
-  Mobile App Version(Not required):
-  App/SmartApp Version:
-  Device Handler/Driver Version:
-  Heroku Server Version:

## Current Behavior
Echo devices won’t show up on SmartThings app. 

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.echo devices won’t show up in Smartthings app. I have fully installed echo speaks and all seems to install perfectly but no echo devices will show up in my SmartThings home list of devices. Using classic app. 
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by plasterer41** [comment]
I’m in the UK if that makes a difference 🤔

**Comment by tonesto7** [comment]
@plasterer41 I'm going to need way more context beyond devices aren't showing up.

**Comment by glenmm** [comment]
> @plasterer41 I'm going to need way more context beyond devices aren't showing up.

Yo Ton,

See #171 -- same issue
