### ISSUE TITLE
(BUG) The playSoundByName Command Not Working with Alexa Sounds Library Items 

### ISSUE THREAD

**Issue by shelhart** [tonesto7/echo-speaks#177]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ X] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ X] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ X] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):   ST
-  How many devices are detected?: 80+
-  iOS or Android?: Android
-  Mobile App Version(Not required):
-  App/SmartApp Version: 3.3.0.1
-  Device Handler/Driver Version: 3.3.0.1
-  Heroku Server Version:  2.2.0

## Expected Behavior
PlaySoundbyName should play from the full sound list like
playSoundByName("amzn_sfx_bear_groan_roar_01")

## Current Behavior
Only a short list of sounds work like "aircraft" . or "zap" and they are case sensitive

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.  Webcore piston available (5p6x)
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**
Just trying to make a noise when the front door opens.
---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
@shelhart  I'm not sure what to do with this.  You barely provided any details.  What exactly is the issue?

**Comment by shelhart** [comment]
Sorry.  Didn 't mean to be vague.  Its the following command that seems to be 'buggy'
playSoundByName("amzn_sfx_bear_groan_roar_01")
This sound, and any others by long name, don't seem to work for me (and some others)

But sounds like
playSoundByName("zap") or playSoundByName("aircraft")
seem to work.

**Comment by tonesto7** [comment]
Yea i'm not sure exactly which ones work.  I randomly picked 10-15 of them and tested and they seemed to work.

**Comment by shelhart** [comment]
I swear I'm not trying to be a pest (I was a coder in a past life)

Can you tell me any of theser that you got to work with the full long name . (The names that start with amzon_sfx?  I just wonder if I'm doing something wrong with the syntax from Webcore?  I also wonder if I am missing something that you have.   Just trying to get it to work for a handful of us.

Thanks man...

**Comment by gaocallag** [comment]
I would be interested also...I have not found any that worked.n  Thanks !!

**Comment by tonesto7** [comment]
@shelhart Sorry I've been silent.  I'm back from break and ready to get this stuff resolved. 
I found the JSON file amazon uses to get the audio files: https://m.media-amazon.com/images/G/01/mobile-apps/dex/ask-tech-docs/ask-soundlibrary._TTH_.json

Do a search for the `amzn_sfx_` and try some of the items listed there

**Comment by tjodork1960** [comment]
the example does not work for me
playSoundByName("amzn_sfx_bear_groan_roar_01"), although when I look at it there is single quotes instead of double quotes

whereas the simple sound "zap" does

**Comment by tonesto7** [comment]
You are right that item doesn't work anymore.  
I created a piston to help test them by using the execute Url and passing a name param like this: https://graph.api.smartthings.com/api/token/82eddasdadasd/smartapps/installations/285549b7-cc48-xxxxxxxxxxxxx/execute/:pistonId:/?name=amzn_sfx_electronic_beep_01
![image](https://user-images.githubusercontent.com/1835933/71684156-a5cde300-2d62-11ea-9d23-0f9c7072fe85.png)

This may help you find the ones to use:

Here are the items that are available to routines:
```
       // Bells and Buzzer
        bells: "bell_02",
        buzzer: "buzzers_pistols_01",
        church_bell: "amzn_sfx_church_bell_1x_02",
        doorbell1: "amzn_sfx_doorbell_01",
        doorbell2: "amzn_sfx_doorbell_chime_01",
        doorbell3: "amzn_sfx_doorbell_chime_02",
        // Holidays
        xmas_bells: "christmas_05",
        halloween_door: "horror_10",
        // Misc
        air_horn: "air_horn_03",
        boing1: "boing_01",
        boing2: "boing_03",
        camera: "camera_01",
        squeaky_door: "squeaky_12",
        ticking_clock: "clock_01",
        trumpet: "amzn_sfx_trumpet_bugle_04",
        // Animals
        cat_meow: "amzn_sfx_cat_meow_1x_01",
        dog_bark: "amzn_sfx_dog_med_bark_1x_02",
        lion_roar: "amzn_sfx_lion_roar_02",
        rooster: "amzn_sfx_rooster_crow_01",
        wolf_howl: "amzn_sfx_wolf_howl_02",
        // Scifi
        aircraft: "futuristic_10",
        engines: "amzn_sfx_scifi_engines_on_02",
        red_alert: "amzn_sfx_scifi_alarm_04",
        shields: "amzn_sfx_scifi_sheilds_up_01",
        sirens: "amzn_sfx_scifi_alarm_01",
        zap: "zap_01",
        // Crowds
        applause: "amzn_sfx_crowd_applause_01",
        cheer: "amzn_sfx_large_crowd_cheer_01"
```

**Comment by tjodork1960** [comment]
thank you sooo much !  I'm anxious to try when I get home : )

**Comment by gaocallag** [comment]
![image](https://user-images.githubusercontent.com/59234340/71705374-0c73f080-2da5-11ea-8c66-790fd3139dfa.png)

it tells the joke but won't play the sound  : (

**Comment by pittbull** [comment]
Confirmed. My playAnnouncement is working, but playSoundByName is not working.

**Comment by tonesto7** [comment]
@pittbull refer to my reply a few posts up

**Comment by tjodork1960** [comment]
are all the items in  "Here are the items that are available to routines:"  working ?  
As noted I could not get amzn_sfx_trumpet_bugle_04 to work.
thank!

**Comment by tonesto7** [comment]
@tjodork1960 Try creating an Alexa routine that plays the sound on the specific Alexa device and see if that works

**Comment by gaocallag** [comment]
I was able to create an alexa routine and have it do the lion roaring ...but the following will still do joke but not sound
![image](https://user-images.githubusercontent.com/59234340/72077479-ee365500-32bc-11ea-8ad6-7f85ad888e51.png)

**Comment by tjodork1960** [comment]
FYI ,,, i have 2 accounts so gaocallag and tjodork1960 are the same

**Comment by shelhart** [comment]
> https://m.media-amazon.com/images/G/01/mobile-apps/dex/ask-tech-docs/ask-soundlibrary._TTH_.json

This is what I suspected.  The "audio file path" vs "name" .  I'll tinker with these as I wonder if the syntax of spaces and parenthesis are part of the problem.   THX for this.  :)

**Comment by tonesto7** [comment]
Have fun.  Let me know what you find out

**Comment by tjodork1960** [comment]
I tried all different options of names and paths ,etc and no go

**Comment by shelhart** [comment]
Ok,  I can't find what's wrong.  I took all three Lion roars as my test:

- animals/amzn_sfx_lion_roar_01
- animals/amzn_sfx_lion_roar_02 (works)
- animals/amzn_sfx_lion_roar_03

Only 02 works via the webcore/echospeaks API.  The only thing I can see from the JSON that was different was the duration of the sound.   (02 is shorter than the others)   So I also tried another short sound:

- amzn_sfx_monkey_calls_3x_01 .   This one also failed. 

So I'm not sure what other properties determine if a sound plays or not, but it truly seems to be something on the Amazon side.    I still love Echo Speaks, and this feature.  I just thought I would share what I've tested to save others some time.  :)

**Comment by tjodork1960** [comment]
so do you input into webcore   animals/amzn_sfx_lion_roar_02  or amzn_sfx_lion_roar_02

**Comment by tonesto7** [comment]
just ```playSoundByName(amzn_sfx_lion_roar_02)```

**Comment by Its2loud1** [comment]
This may be a dumb question but where do you enter the name of the sound?
