### ISSUE TITLE
[ADD DEVICE SUPPORT] (3) Devices

### ISSUE THREAD

**Issue by ddavewoods42** [tonesto7/echo-speaks#178]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: THIRD_PARTY_AVS_MEDIA_DISPLAY
name: Catservatory 1
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode, bluetoothControl
type: A21X6I4DKINIZU

description: What kind of device/model?(PLEASE UPDATE THIS)
family: THIRD_PARTY_AVS_MEDIA_DISPLAY
name: Dave's 2nd Voice One
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode, bluetoothControl
type: A21X6I4DKINIZU

description: What kind of device/model?(PLEASE UPDATE THIS)
family: TBIRD_ANDROID
name: Dave's Ford/Lincoln+Alexa App
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, doNotDisturb, microphone, followUpMode
type: A2S24G29BFP88

**Comment by tonesto7** [comment]
These have all been added to the block list since they are all media player devices.
