### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by Colmrenault** [tonesto7/echo-speaks#181]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: THIRD_PARTY_AVS_MEDIA_DISPLAY
name: Colm's webOS TV
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, doNotDisturb, microphone, followUpMode
type: A112LJ20W14H95

**Comment by tonesto7** [comment]
Added to the list
