### ISSUE TITLE
(BUG) Typo on Zone Configuration field

### ISSUE THREAD

**Issue by seanchilds** [tonesto7/echo-speaks#182]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ ]x That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings)
-  How many devices are detected? :5
-  Android
-  Mobile App Version(Not required):
-  App/SmartApp Version: 3.3.1.0
-  Device Handler/Driver Version:3.3.0.1
-  Heroku Server Version:2.3.1

## Expected Behavior
**tell us what should happen**
when the "require all selected" switch is turned on during the zone setup. it should not state "any condition allowed" on the main page.

## Current Behavior
**What happens instead of the expected behavior?**
see attached screenshots

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. creat zone with multiple conditions.
2. turn on "require all selected" switch at the top
3. save
4. now go back and view the new zone 

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**
I am trying to figure out why my zones are not working "this is just one of the issues"
![Screenshot_20191218-171814_SmartThings](https://user-images.githubusercontent.com/18430391/71134344-22858c80-21bb-11ea-853a-758484b727de.jpg)
![Screenshot_20191218-171809_SmartThings](https://user-images.githubusercontent.com/18430391/71134348-274a4080-21bb-11ea-95f5-6b075c1c367f.jpg)

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
@seanchilds I'm working on correcting the zone issues right now I should have a fix out in the next couple hours.
