### ISSUE TITLE
(BUG) Zones not working

### ISSUE THREAD

**Issue by seanchilds** [tonesto7/echo-speaks#183]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):SmartThings
-  How many devices are detected?:5
-  iOS or Android?:Android
-  Mobile App Version(Not required):
-  App/SmartApp Version:3.3.1.0
-  Device Handler/Driver Version:3.3.0.1
-  Heroku Server Version:2.3.1

## Expected Behavior
**tell us what should happen**
if I select any of a motion sensor or a light switch to activate a zone that only if the light is on or if there is motion then the zone is active.

## Current Behavior
**What happens instead of the expected behavior?**
zone is always active

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. create a zone with more than one condition
2. set for any condition
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**
I have attached a screenshot of the zone.
Note: this is set to any condition NOT ALL like it says (see my other bug report for details)

I have also tried to set this to "all conditions needed" and this is the only way I can get any zone to work, but I wanted more than 1 way to trigger the zone.
I have also tried having only 1 condition but this also will not work!

FYI the Zone tasks and Notifications are also not working...
I wanted this just to help troubleshoot but your new history work
![Screenshot_20191218-175701_SmartThings](https://user-images.githubusercontent.com/18430391/71135853-17812b00-21c0-11ea-88d4-98931eba44c9.jpg)
s great for this!
Thank you

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
@seanchilds  Thanks for reporting I will investigate this right now and get out some fixes
