### ISSUE TITLE
I would like to be able to select an Echo device as a Siren for SHM alarm. 

### ISSUE THREAD

**Issue by garhun** [tonesto7/echo-speaks#185]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tonesto7** [comment]
@garhun  I don't see much benefit as there is nothing useful we could do with them.

**Comment by garhun** [comment]
My use for the siren/alarm functionality is to wake me up at night if SHM detects alarm is triggered. I had been using the similar function provided by Lannouncer application, and is the only function from that app that is not fulfilled in Echo Speaks. Thanks for this great work.

**Comment by tonesto7** [comment]
you can use the echo speaks devices as a speaker under SHM alerts

**Comment by garhun** [comment]
I tried using the audio notification feature,  in the Alarms and Notification section of the security set up, and selected the Fire Alarm sound to be played. When the alarm trips, Echo speaker just says the word "alarm" one time. Is there something more I should be doing?

**Comment by tonesto7** [comment]
You can not use them with sounds but can use them for speech under SHM.
Amazon does not allow the playback of MP3's
