### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by dds82** [tonesto7/echo-speaks#186]
Requesting device support from the following device(s):
description: What kind of device/model? Bose home speaker 450
family: THIRD_PARTY_AVS_SONOS_BOOTLEG
name: Daniel's Bose Home Speaker 450
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode
type: A3BRT6REMPQWA8

**Comment by tonesto7** [comment]
Added to the list
