### ISSUE TITLE
(BUG) 

### ISSUE THREAD

**Issue by mhanan99** [tonesto7/echo-speaks#188]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):ST
-  How many devices are detected?:27
-  iOS or Android?:iOS
-  Mobile App Version(Not required):
-  App/SmartApp Version:3.3.1.2
-  Device Handler/Driver Version:3.3.0.1
-  Heroku Server Version:2.3.1

## Expected Behavior
**tell us what should happen**
Under “Device Testing” / “Speech Test”, testing fails to WHA’s (but works to individual devices).  I have the same problem within Webcore (can not speak text to WHA’s)

## Current Behavior
**What happens instead of the expected behavior?**
Nothing

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Create a Speaker Group in Alexa 
2. Ensure Group appears in Echo Speaks
3. Go to  “Device Testing” / “Speech Test”
4. test speech to Group
(In my case there is no output.  I have multiple groups I have tested with.  I have also tested with Webcore.  Speech works fine when sent to an individual device)

## Context
**How has this issue affected you? What are you trying to accomplish?  send alerts and announcements to groups of devices.  I can work around this by listing out each device in a group (in Webcore), but would prefer working with groups 
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
@mhanan99  Amazon doesn't allow me to send speech to speaker groups.  
Create a zone in echospeaks and create an action to speak to the zone like a broadcast
