### ISSUE TITLE
Does not allow/support Echo Tap devices

### ISSUE THREAD

**Issue by SANdood** [tonesto7/echo-speaks#19]
Needs to include the following device signature:

`    case 'A38949IHXHRQ5P': return [name: 'Echo Tap', image: 'echo_gen1', playerSupport: true, ttsSupport: true]`

Note that there isn't currently an 'echo_tap' icon/image, so I used 'echo_gen1' above.

**Comment by tonesto7** [comment]
I merged it.  Plus the changes will be in the new v2.0

**Comment by SANdood** [comment]
Note that I provided a bad name for the image file – (‘echo_gen’) – you either need to create an ‘echo_tap’ icon, or change the image file name to ‘echo_gen1’.

 

Thanks!

**Comment by tonesto7** [comment]
This will be in v2.0 that's released in the next few days
