### ISSUE TITLE
Restriction condition on smart home alarm is not working 

### ISSUE THREAD

**Issue by alextheangel** [tonesto7/echo-speaks#192]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): smartthings
-  How many devices are detected?: 5
-  iOS or Android?: android
-  Mobile App Version(Not required):
-  App/SmartApp Version: 3.3.1.2
-  Device Handler/Driver Version: 3.3.0.1

-  Heroku Server Version: 2.3.0

## Expected Behavior
**tell us what should happen**
Echo device would play warning on doors windows opening / locks unlocking when smarthome alarm setting as "Alarmed (stay)" only
## Current Behavior
**What happens instead of the expected behavior?**
Echo devices warning on every doors opening even when system was setting "Disalarmed"

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish? 
Yes, as I don't want echo speakers out everytime I open the windows or doors.
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
Sorry I haven't replied... I'm looking at this right now

**Comment by tonesto7** [comment]
I pushed out a fix for this...

**Comment by alextheangel** [comment]
Thanks for the reply. I did the update 3.3.2.0, but the issue seems still there. As seen on the screen shot the condition part on alarm modes is x instead of v
[Image]



Get Outlook for Android<https://aka.ms/ghei36>
________________________________
