### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by CosInf** [tonesto7/echo-speaks#194]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: THIRD_PARTY_AVS_MEDIA_DISPLAY
name: Cosmin's ecobee Switch+
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, doNotDisturb, microphone, followUpMode
type: AUPUQSVCVHXP0

**Comment by tonesto7** [comment]
added the device to the ignore list as there is not much we can do with the device
