### ISSUE TITLE
(BUG) 

### ISSUE THREAD

**Issue by ikilimnik** [tonesto7/echo-speaks#195]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):
-  How many devices are detected?:
-  iOS or Android?: iOS
-  Mobile App Version(Not required):
-  App/SmartApp Version:
-  Device Handler/Driver Version:
-  Heroku Server Version:

## Expected Behavior
Require ALL should work with virtual switches

## Current Behavior
Require ALL doesn’t work with virtual switches. Have two virtual switches in my Action. If one of them is turned on it triggers the action ignoring Require All condition

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
@ikilimnik This was a bug from 2 revisions ago that should be resolved.  Are you running the latest code for all smartapps and devices

**Comment by ikilimnik** [comment]
Sent from my iPhone.
Sorry for typos. 

> On Jan 2, 2020, at 7:53 AM, Tonesto7 <notifications@github.com> wrote:
> 

﻿
@ikilimnik This was a bug from 2 revisions ago that should be resolved. Are you running the latest code for all smartapps and devices

**Comment by ikilimnik** [comment]
Could you please test an action with two virtual switches within new ST app. 


Sent from my iPhone.
Sorry for typos. 

> On Jan 2, 2020, at 7:53 AM, Tonesto7 <notifications@github.com> wrote:
> 

﻿
@ikilimnik This was a bug from 2 revisions ago that should be resolved. Are you running the latest code for all smartapps and devices

**Comment by ikilimnik** [comment]
Could you please test an action with two virtual switches within new ST app. 
![FF1B1E69-B0A0-4206-A721-1EA14C45D471](https://user-images.githubusercontent.com/18468199/71706146-f9a6ef00-2d97-11ea-91f8-0c421b8eed32.jpeg)
![18DC0E04-7522-4E6E-9B1F-0C1145353227](https://user-images.githubusercontent.com/18468199/71706147-f9a6ef00-2d97-11ea-891b-5b0b827b9796.png)

**Comment by ikilimnik** [comment]
Could you please test an action with two virtual switches within new ST app.

**Comment by ikilimnik** [comment]
Will you fix the bug?!


Sent from my iPhone.
Sorry for typos. 

> On Jan 2, 2020, at 7:53 AM, Tonesto7 <notifications@github.com> wrote:
> 

﻿
@ikilimnik This was a bug from 2 revisions ago that should be resolved. Are you running the latest code for all smartapps and devices

**Comment by tonesto7** [comment]
@ikilimnik I need you relax a bit please.  I home with my family trying to enjoy the last couple days remaining for my kids new year break.  I will look at it tomorrow when i get into the office.   
I can tell you this that I have definitely tell you that it works with virtual switches...

**Comment by ikilimnik** [comment]
Thank you. I appreciate it. 


Sent from my iPhone.
Sorry for typos. 

> On Jan 5, 2020, at 7:13 AM, Tonesto7 <notifications@github.com> wrote:
> 

﻿
@ikilimnik I need you relax a bit please. I home with my family trying to enjoy the last couple days remaining for my kids new year break. I will look at it tomorrow when i get into the office.
I can tell you this that I have definitely tell you that it works with virtual switches...

**Comment by tonesto7** [comment]
@ikilimnik  I tracked down the issue and I'm about to push out a new release in about 10 minutes

**Comment by ikilimnik** [comment]
Thank you very much sir! 


Sent from my iPhone.
Sorry for typos. 

> On Jan 7, 2020, at 4:50 PM, Tonesto7 <notifications@github.com> wrote:
> 

﻿
@ikilimnik I tracked down the issue and I'm about to push out a new release in about 10 minutes

**Comment by ikilimnik** [comment]
Hi,

Even after today’s  update Require all switches feature still doesn’t work. I can trigger an action by one virtual switch, despite “Require All Switches” is on. 


Sent from my iPhone.
Sorry for typos. 

> On Jan 7, 2020, at 4:51 PM, Igor Kilimnik <kilimnik@icloud.com> wrote:
> 

﻿Thank you very much sir! 


Sent from my iPhone.
Sorry for typos. 

> On Jan 7, 2020, at 4:50 PM, Tonesto7 <notifications@github.com> wrote:
> 

﻿
@ikilimnik I tracked down the issue and I'm about to push out a new release in about 10 minutes
