### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by ghamian** [tonesto7/echo-speaks#196]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: UNKNOWN
name: Soundbar
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, appleMusic, spotify, alarms, doNotDisturb, microphone, followUpMode
type: AD2YUJTRVBNOF

**Comment by tonesto7** [comment]
added the device to the block list until I can properly validate the device
