### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by vitamincm** [tonesto7/echo-speaks#197]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: UNKNOWN
name: Soundbar
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode
type: AGZWSPR7FLP9E
Model is Yamaha YAS 109

**Comment by tonesto7** [comment]
added the device to the block list until I can identify it properly
