### ISSUE TITLE
[ADD DEVICE SUPPORT] (2) Devices

### ISSUE THREAD

**Issue by shanedorey** [tonesto7/echo-speaks#198]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: UNKNOWN
name: Shane's AmazfitWatch
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode
type: A2V3E2XUH5Z7M8

description: What kind of device/model?(PLEASE UPDATE THIS)
family: MSHOP
name: Shane's Alexa Apps
permissions: volumeControl, spotify, microphone
type: A1MPSLFC7L5AFK

**Comment by tonesto7** [comment]
added these devices to the block list as they can't really be used without validating them
