### ISSUE TITLE
[Add Device Support] Fire TV Cube (Gen2)

### ISSUE THREAD

**Issue by DixieChckn** [tonesto7/echo-speaks#199]
**Required Info is the following (Found under Echo Speaks app under devices page):

* Family: FIRE_TV
* Type:  A2JKHJ0PX4J3L3

** Other Info:
Requesting support for Announcements and Speech

* Model and/or Generation of device:  Fire TV Cube (Gen2)

**Have you tested the device for announcement/speech support using Alexa Routine?
Yes. Announcement/speech works properly on this device through an Alexa Routine

**Comment by tonesto7** [comment]
The device permissions all of the ES to support speech and announcements.  Can you make it speaks using an Alexa Routine?
