### ISSUE TITLE
(BUG) Errors on Create Alarm / Create Reminder

### ISSUE THREAD

**Issue by JDiaz11** [tonesto7/echo-speaks#200]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): SmartThings
-  How many devices are detected?: 10
-  iOS or Android?: iOS 
-  Mobile App Version(Not required):
-  App/SmartApp Version: 3.3.2.0
-  Device Handler/Driver Version: 3.3.0.1
-  Heroku Server Version: 2.3.0

## Expected Behavior
**tell us what should happen**
Create Alarm / Create Reminder 
## Current Behavior
**What happens instead of the expected behavior?**
When attempting to make a Create Alarm or Create Reminder action, the IDE log returns the following errors and doesn't actually create the Alarm or Reminder:

**_Action_:
7:47:48 AM: info Action (v3.3.2.0) | Updated Event Received...
7:47:48 AM: info Action (v3.3.2.0) | Installed Event Received...

_Echo Device_:
7:48:25 AM: error Echo (v3.3.0.1) | CreateReminder Response Exception | Status: (500) | Msg: Internal Server Error

_Echo Speaks_:
2464abc6-d6c3-4ddb-af50-58ad4216c26a 7:48:55 AM: error org.springframework.jdbc.UncategorizedSQLException: Hibernate operation: could not execute query; uncategorized SQLException for SQL [select this_.id as id61_0_, this_.version as version61_0_, this_.date_created as date3_61_0_, this_.`key` as key4_61_0_, this_.type as type61_0_, this_.value as value61_0_ from server_config this_ where this_.`key`=?]; SQL state [null]; error code [0]; [SimpleAsyncTaskExecutor-12] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:50; busy:7; idle:0; lastwait:30000].; nested exception is org.apache.tomcat.jdbc.pool.PoolExhaustedException: [SimpleAsyncTaskExecutor-12] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:50; busy:7; idle:0; lastwait:30000]. @line 1235 (postInitialize)
2464abc6-d6c3-4ddb-af50-58ad4216c26a 7:48:14 AM: info EchoApp (v3.3.2.0) | Cookie Validation: (true) | Process Time: (226ms)
2464abc6-d6c3-4ddb-af50-58ad4216c26a 7:48:13 AM: info EchoApp (v3.3.2.0) | Updated Event Received...**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Attempting to create as usual
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by JDiaz11** [comment]
Is this going to get addressed please?

**Comment by tonesto7** [comment]
@JDiaz11 Yes...

I'm working on fixes for Echo Speaks right now... 
I will have something out this evening.

**Comment by tonesto7** [comment]
@JDiaz11  It's taking longer than expected so I might not be out tonight.

**Comment by tonesto7** [comment]
I’ve resolved the issue and it’s pending deployment sometime today.

**Comment by JDiaz11** [comment]
Hi-- Thank you. It seems to have affected it and the Echo Speaks module no longer pulls an issue. However the device module does and the Alarm/Reminder is not successfully created. I even initiated a new instance of the server just to clear out any old settings but no dice.
--------------
```
5:09:50 AM: error Echo (v3.4.0.0) \| CreateAlarm Response Exception \| Status: (500) \| Msg: Internal Server Error
5:09:50 AM: debug params: [type:Alarm, status:ON, alarmTime:1580033450491, createdDate:1580033390491, originalTime:05:30.00.000, originalDate:2020-01-27, timeZoneId:null, reminderIndex:null, sound:null, deviceSerialNumber:G090U50990520K9Q, deviceType:A32DOYMUN6DTXA, recurrenceEligibility:false, alarmLabel:TestAlarm, reminderLabel:null, reminderSubLabel:Echo Speaks, timerLabel:null, skillInfo:null, isSaveInFlight:true, triggerTime:0, id:createAlarm, isRecurring:false, remainingDuration:0, rRuleData:null, recurringPattern:null]
5:09:50 AM: debug rule: [data:null, pattern:null]
5:09:50 AM: debug transormRecurString(type: null, opt: null, time: 05:30,date: 2020-01-27)
5:09:50 AM: trace createdNotification params: [cmdType:CreateAlarm, label:TestAlarm, date:2020-01-27, time:05:30, type:Alarm]
```

**Comment by andyhawks** [comment]
I'm also having the 500 server error as in the comment above using `createAlarm()` in webcore:

```
28ba91a9-7824-45f3-b2f5-3c38cccc4d33 6:05:32 PM: error Echo (v3.4.0.0) | CreateAlarm Response Exception | Status: (500) | Msg: Internal Server Error
28ba91a9-7824-45f3-b2f5-3c38cccc4d33 6:05:32 PM: debug params: [type:Alarm, status:ON, alarmTime:1580259992500, createdDate:1580259932500, originalTime:05:45.00.000, originalDate:2020-01-29, timeZoneId:null, reminderIndex:null, sound:null, deviceSerialNumber:G0911B0592560922, deviceType:A4ZP7ZC4PI6TO, recurrenceEligibility:false, alarmLabel:2020-01-29, reminderLabel:null, reminderSubLabel:Echo Speaks, timerLabel:null, skillInfo:null, isSaveInFlight:true, triggerTime:0, id:createAlarm, isRecurring:false, remainingDuration:0, rRuleData:null, recurringPattern:null]
28ba91a9-7824-45f3-b2f5-3c38cccc4d33 6:05:32 PM: debug rule: [data:null, pattern:null]
28ba91a9-7824-45f3-b2f5-3c38cccc4d33 6:05:32 PM: debug transormRecurString(type: null, opt: null, time: 05:45,date: 2020-01-29)
28ba91a9-7824-45f3-b2f5-3c38cccc4d33 6:05:32 PM: trace createdNotification params: [cmdType:CreateAlarm, label:2020-01-29, date:2020-01-29, time:05:45, type:Alarm]
```
