### ISSUE TITLE
[ADD DEVICE SUPPORT] (2) Devices

### ISSUE THREAD

**Issue by rjterry21** [tonesto7/echo-speaks#201]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode
name: Sandy's Portal
description: What kind of device/model?(Facebook Portal account - that has Alexa on it)
family: FALCON
type: A3B5K1G3EITBIF

permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode
name: Russell's Portal
description: What kind of device/model?(Facebook Portal account that has Alexa on it)
family: FALCON
type: A3B5K1G3EITBIF

**Comment by tonesto7** [comment]
I've added it to the allow list... Please open the smartapp and press done.  It should detect it as the correct device.

**Comment by rjterry21** [comment]
Thanks!
