### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by Pipemeister** [tonesto7/echo-speaks#202]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: ALEXA_AUTO
name: Andrew's Roav Car Charger Pro
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, appleMusic, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode, bluetoothControl
type: A347G2JC8I4HC7

**Comment by tonesto7** [comment]
I've added to the allow list... Please open the app and press done for it to discover the new device.
After testing the device please let me know if it works or not for speech and announcements.
