### ISSUE TITLE
[Feature Request] Add Support for HEOS Devices

### ISSUE THREAD

**Issue by marktheknife** [tonesto7/echo-speaks#204]
Hi, I noticed I can see a Sonos device in Echo speaks, but not a HEOS device. It would be great if Echo speaks could add support for HEOS devices connected to Alexa. Thanks!

**Comment by tonesto7** [comment]
If it shows under the alexa app and you can select it as a device to speak and send announcements I can add it to ES.

**Comment by tonesto7** [comment]
@marktheknife Can you verify you can get the HEOS devices to work under Alexa Routings?

**Comment by marktheknife** [comment]
Hey, sorry for the delayed reply. I went on vacation shortly after your response. I will check next week when I’m home and let you know. Thanks for looking into this!

**Comment by tonesto7** [comment]
any update on this?

**Comment by marktheknife** [comment]
Sorry for not following up. I can’t see my HEOS devices in the Alexa app as an option for an announcement when I try to create a new routine.

Bummer.
