### ISSUE TITLE
[Add Device Support] Fire HD 10

### ISSUE THREAD

**Issue by EZPeazy** [tonesto7/echo-speaks#206]
**Required Info is the following (Found under Echo Speaks app under devices page):

* Family: Alexa Fire HD 10 Tablet 9th Gen

I have been using an older echo dot with no issue connecting. I use it as a speaker for alerts. I wanted to use the new tablet's speakers, in the same manner, to get rid of the echo dot. The table is being used as my home automation UI touch screen. After everything I tried, I'm not sure if the tablet is supported as a device.

Thanks,
EZ

**Comment by tonesto7** [comment]
This device already has support
