### ISSUE TITLE
(BUG) Activation delay for zones not honored

### ISSUE THREAD

**Issue by zuhairmahd** [tonesto7/echo-speaks#208]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):
-  How many devices are detected?:
-  iOS or Android?:
-  Mobile App Version(Not required):
-  App/SmartApp Version:
-  Device Handler/Driver Version:
-  Heroku Server Version:

## Expected Behavior
**tell us what should happen**

## Current Behavior
**What happens instead of the expected behavior?**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

iOS app, echospeaks apps v3.3.2.0 and DTH V3301.   Troubleshooting steps above followed. 

Scenario:
I’m trying to set up a zone upstairs to route Alexa speech to the echo device located in my office. Using 3 motion sensors, I want the zone to become active whenever motion is detected on any of the three upstairs motion sensors. I’d like the zone to become inactive 15 minutes after motion has stopped on all sensors. 

I created a zone as follows:
1. Trigger conditions: whenever motion on any of the three sensors is active. The checkbox to instruct that all three sensors be active was unchecked, which, as I understand it, means that at least one of the sensors has to become active for the zone to trigger. 
1. For Alexa device's, I selected the one echo in my office.
3. Under delays, I put 900 seconds under inactivity delay. 
4. Lastly, I set up a notification through the pushover manager to notify me whenever the zone activated or deactivated. 

Expected behavior:
Motion is active on any of the sensors, therefore the zone activates. Once motion stops, the zone will wait for 15 minutes and deactivate.  

Actual behavior:
Zone activates whenever motion is active on any sensor, and instantly deactivates when motion is inactive.to eliminate the possibility that multiple sensors may be complicating the issue, I used only one sensor to trigger the zone but got the same result. 

Hope this is a helpful rundown of the issue. 

P.s. there is a typo in the custom  notification configuration screen. The labels for notification when active and inactive both say “active”

**Comment by tonesto7** [comment]
Sorry, you haven't heard from me... I will attempt to duplicate this.

**Comment by tonesto7** [comment]
@zuhairmahd I have resolved this issue and will be pushing out updated apps in the next 30 minutes

**Comment by tonesto7** [comment]
This should be resolved now
