### ISSUE TITLE
[Feature Request] Support other music search providers (need RADIO.COM) or generic search

### ISSUE THREAD

**Issue by glenmm** [tonesto7/echo-speaks#209]
**Is your feature request related to a problem? Please describe.**
Limited selection of Echo Speaks search providers

**Describe the solution you'd like**
I would like either specifically to support a RADIO.COM search (as many radio stations have moved OFF of TUNEIN to RADIO.COM), or a generic search where I can execute search::"WCBS Newsradio 880 on RADIO dot COM"

**Describe alternatives you've considered**
Tried leaving off the provider name as searchMusic("WCBS Newsradio 880 on RADIO.COM") in WebCore and the command seems to be ignored by the Echo -- should be able to just have alexa search all its providers for the requested item as searchMusic("WCBS Newsradio 880") and it will find it on one of the configured Services in SETTINGS>MUSIC & PODCASTS

**Additional context**
N/A

Thanks for your consideration in advance

**Comment by tonesto7** [comment]
@glenmm I apologize but there is no native way to do this using the current API.  I'm required to target a specific service when searching.
I can only select certain music providers and at this Radio.com is not one of them
