### ISSUE TITLE
(BUG) erroneous zone activation notifications

### ISSUE THREAD

**Issue by zuhairmahd** [tonesto7/echo-speaks#211]
# Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):
-  How many devices are detected?:
-  iOS or Android?:
-  Mobile App Version(Not required):
-  App/SmartApp Version:
-  Device Handler/Driver Version:
-  Heroku Server Version:

## Expected Behavior
**tell us what should happen**

## Current Behavior
**What happens instead of the expected behavior?**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug
Somewhat related to #208, while zone activation delays seem to be honored, I set up a notification to trigger whenever a zone activates or deactivates.  While the does seem to remain active for the duration of the delay, I keep getting multiple activation notifications. The expected behavior is for the notifications to trigger only when the zone is activated and deactivated

**Comment by zuhairmahd** [comment]
Forgot to mention that I had switches tied to the activation and deactivation of a zone, and those are working as expected — the switches come on when the zone is active and turn off when it is not. Only the notifications are being triggered.

**Comment by tonesto7** [comment]
@zuhairmahd Thanks for reporting this.  It should be easy for me to duplicate this on my end.

**Comment by zuhairmahd** [comment]
@tonesto7 the other thing is that if the zone is set to activate when all conditions are true (by checking the box), and one of the conditions is a time period and the time period expires while the zone is active, the zone remains active even past the inactivity delay period. For example, the zone I have is set to activate when all the following conditions are true:
1. Location mode is set to home
2. Alarm state is disarmed.
3. Motion is detected on any one of 3 sensors, and 
4. The time is between 10:00 AM and 11:00 PM.


The expectation is then that if any of the above conditions is no longer true, the zone should deactivate after the inactivity delay period (I set that to 1800 seconds) has elapsed. 

I’d therefore expect that if all other conditions remain true, the zone should become inactive 1800 seconds after 11:00 PM, instead the zone remains active regardless of any subsequent condition changes. 

In the current implementation, the deactivation delay is not specific to motion sensors, but rather to any or all conditions. But wouldn’t there be a good case also for adding a delay specific to motion inactivity? That way the zone will deactivate immediately whenever the location mode or alarm state changes or when the time period expires, but will remain active until motion has been inactive for a specific time period.

**Comment by tonesto7** [comment]
You are right about the time conditions not setting the condition as false.  I need to add a schedule to the logic.  

> In the current implementation, the deactivation delay is not specific to motion sensors, but rather to any or all conditions. But wouldn’t there be a good case also for adding a delay specific to motion inactivity? That way the zone will deactivate immediately whenever the location mode or alarm state changes or when the time period expires, but will remain active until motion has been inactive for a specific time period.

I do like this idea.  Can you open these two items as separate feature requests?  I want to make sure to get them addressed.

**Comment by tonesto7** [comment]
Nvm.  I used up feature requests for thesr

**Comment by tonesto7** [comment]
I think i've resolved this.  I found a few bugs in the notification logic and the UI

**Comment by tonesto7** [comment]
This fix will be deployed in the next couple hours

**Comment by zuhairmahd** [comment]
@tonesto7  thanks. Look forward to the push. Regarding the issue of zones failing to deactivate after time has expired, wouldn’t that be more of a bug rather than a feature request?
