### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by adw770** [tonesto7/echo-speaks#215]
First off the Echo Speaks is a great addition to my SmartThings infrastructure. 

I’m using this to announce the Monitoring status of my home. Is it armed or disarmed.  I use motion to disarm automatically in morning however my issue is the announcement occurs even if home is already in proper state.  I would like to see a setting to not announce if state is same.  I currently have an option to perform once a day but if I arm and disarm multiple times in one day I only get announcements once.

**Comment by tonesto7** [comment]
@adw770 Is this something you can control with conditions?  Like requiring all the conditions to be true versus any.
I guess I'm just not seeing how to handle what you're asking for at the moment :smile:

**Comment by adw770** [comment]
I did try using conditions without success. The only area I have had 
this kind of challenge is using the Home Monitor.

Here is my scenario of events. I have a routine that was created in the 
classic to disarm using  several motions sensors that use the Things 
Start Happening in the morning to change from armed home to disarm. If I 
do not have the routine set to Only Once Per Day then the motion 
detected will send a disarm to the system. This has not been an issue 
until I setup Echo Speaks to announce that house is armed are disarmed. 
Hoping this is making sense so far.

What would be great in your application in the Home Monitoring section 
is a way to test if current condition is the same as the one just 
processed and if it is not to fire. This is based on an assumption that 
the current status can be checked.

My Trigger is Smart Home Monitor
Smart home Modes are Armed Home and Disarm

As I talk through this I think if I build 2 rules then I can use the 
condition to manage. Trying to use a single rule for both arm and disarm 
made it where conditions created other issues. I'll give that a try and 
let you know.

------ Original Message ------

**Comment by adw770** [comment]
So the conditions did not work and I have split the actions into 2 
separate ones so I could use. Here are the live events I captured of me 
walking in front of several of the motion sensors that help determine of 
it is OK to disarm home in the morning.

Things Start Happening
Disarm
Amazon Alexa
Alert with Lights
Echo - Alan's Echo Show
Kitchen Lighting Motion
Front Door Lighting
Logs
ba030299-cbff-483f-ad26-59e71978839d 7:41:46 AM: debug state: active
ba030299-cbff-483f-ad26-59e71978839d 7:41:46 AM: debug 18 sec since 
motion stopped
ba030299-cbff-483f-ad26-59e71978839d 7:41:46 AM: debug schedule check, 
ts = 1579621288062
cf5a4931-6b3a-47ee-994d-8afc78e453c8 7:41:28 AM: info 
postEventToEndpoint: event successfully posted.
cf5a4931-6b3a-47ee-994d-8afc78e453c8 7:41:28 AM: debug 
doesTvSupportVoice Motion Sensor: false
cf5a4931-6b3a-47ee-994d-8afc78e453c8 7:41:28 AM: debug Property Changed 
event motion: inactive (source: DEVICE)
cf5a4931-6b3a-47ee-994d-8afc78e453c8 7:41:28 AM: debug 
routeEndpointEvent event name: motion, physical?: false
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:28 AM: debug 
motionOrContactHandler(Kitchen Motion motion:inactive)
ba030299-cbff-483f-ad26-59e71978839d 7:41:28 AM: debug state: active
ba030299-cbff-483f-ad26-59e71978839d 7:41:28 AM: debug motionHandler: 
motion: inactive
b3ab3f21-8ca3-4d81-b29b-344a153bb574 7:41:22 AM: info Echo (v3.3.0.1) | 
SpeakCommand Sent | (The Smart Home Monitor is now set to off) | 
Runtime: (4 sec) | QueueItems: (0) | Execution Time: (3906ms)
abe63a55-0495-46cb-9220-48adeb8ed4d3 7:41:21 AM: debug state: activating
abe63a55-0495-46cb-9220-48adeb8ed4d3 7:41:21 AM: debug schedule check, 
ts = null
b3ab3f21-8ca3-4d81-b29b-344a153bb574 7:41:17 AM: info Echo (v3.3.0.1) | 
SpeakCommand Sent | (The Smart Home Monitor is now set to off) | 
Runtime: (4 sec) | QueueItems: (0) | Execution Time: (1406ms)
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:16 AM: info SHM COMPLETED 
DISARM CHILDREN:1 ISA:c79c6958-0a83-4cae-8922-75b8d90630f1, TIME:0.488
2bec3d57-334d-424a-a829-77868af3af31 7:41:16 AM: trace 
onSecurityEnable(MODE_DISABLE)
2bec3d57-334d-424a-a829-77868af3af31 7:41:16 AM: debug summaryData: 
[[icon:indicator-dot-gray, iconColor:#878787, value:Disarmed], 
[icon:indicator-dot-green, iconColor:#79b821, value:Everything OK, 
heroInfo:[heroStatus:ok, heroMessage:Everything OK]]] - 
[[icon:indicator-dot-gray, iconColor:#878787, value:Disarmed], 
[heroInfo:[heroMessage:Everything OK, heroStatus:ok], 
icon:indicator-dot-green, iconColor:#79b821, value:Everything OK]]
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:16 AM: trace unscheduling 
delayed alarms
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:16 AM: trace 
/unsubscribeChildApps
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:15 AM: trace removing 
subscriptions to Alert with Lights
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:15 AM: trace 
unsubscribeChildApps()
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:15 AM: info SHM - 
dismissSirens() wasn't executed because there is no active incident
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:15 AM: info SHM TRYING DISARM 
CHILDREN: 1 ISA: c79c6958-0a83-4cae-8922-75b8d90630f1
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:15 AM: info SHM armDisarmCheck 
executing off
33585d86-365a-407b-93a5-0888385934e1 7:41:15 AM: debug INITIALIZED, 
settings: [triggerResetTime:1579397501807, lightDevices:[Bedroom, 
Kitchen, Piano Light, WeMo Back Yard, Hallway, Front Door Light, WeMo 
North Patio, Living RM pole, Color], lightLevel:100, color:Red]
33585d86-365a-407b-93a5-0888385934e1 7:41:15 AM: debug Updated with 
settings: [triggerResetTime:1579397501807, lightDevices:[Bedroom, 
Kitchen, Piano Light, WeMo Back Yard, Hallway, Front Door Light, WeMo 
North Patio, Living RM pole, Color], lightLevel:100, color:Red]
cf5a4931-6b3a-47ee-994d-8afc78e453c8 7:41:15 AM: info 
postEventToEndpoint: event successfully posted.
cf5a4931-6b3a-47ee-994d-8afc78e453c8 7:41:15 AM: debug 
doesTvSupportVoice Motion Sensor: false
cf5a4931-6b3a-47ee-994d-8afc78e453c8 7:41:15 AM: debug Property Changed 
event motion: active (source: DEVICE)
cf5a4931-6b3a-47ee-994d-8afc78e453c8 7:41:15 AM: debug 
routeEndpointEvent event name: motion, physical?: false
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:15 AM: info SHM 
isActiveSensor(motion:active, app: off, location: off) = false, 
locationId: b8fc2f84-e50f-4f67-8d07-d5a2bdea6198, ISA: 
c79c6958-0a83-4cae-8922-75b8d90630f1
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:15 AM: debug 
motionOrContactHandler(Kitchen Motion motion:active)
1f7c6c2f-2b79-4aaf-bf23-027aed909017 7:41:15 AM: trace Not sending 
alert, no preferences set
1f7c6c2f-2b79-4aaf-bf23-027aed909017 7:41:15 AM: trace oncePerDayOk = 
true
1f7c6c2f-2b79-4aaf-bf23-027aed909017 7:41:15 AM: debug HH autoExecute(), 
newMode: null
956f7f14-d4e1-4860-971c-58b2ece25f5a 7:41:15 AM: debug HH auto execute 
Disarm Things Start Happening
956f7f14-d4e1-4860-971c-58b2ece25f5a 7:41:15 AM: trace daysOk = true
956f7f14-d4e1-4860-971c-58b2ece25f5a 7:41:15 AM: debug startTime: 
2017-01-22T05:00:00.000-0800, endTime: 2017-01-22T10:30:00.000-0800, t0: 
Tue Jan 21 15:41:15 UTC 2020
956f7f14-d4e1-4860-971c-58b2ece25f5a 7:41:15 AM: trace 
motionActiveHandler(motion: active), timeOfDay: 
2017-01-22T05:00:00.000-0800, endTime: 2017-01-22T10:30:00.000-0800
ba030299-cbff-483f-ad26-59e71978839d 7:41:15 AM: debug state: activating
ba030299-cbff-483f-ad26-59e71978839d 7:41:15 AM: debug turning on lights
ba030299-cbff-483f-ad26-59e71978839d 7:41:15 AM: debug motionHandler: 
motion: active
b3ab3f21-8ca3-4d81-b29b-344a153bb574 7:41:12 AM: info Echo (v3.3.0.1) | 
SpeakCommand Sent | (The Smart Home Monitor is now set to off) | 
Runtime: (4 sec) | QueueItems: (0) | Execution Time: (4200ms)
b3ab3f21-8ca3-4d81-b29b-344a153bb574 7:41:08 AM: warn Echo (v3.3.0.1) | 
speechCmd | Too Many Requests Made to Amazon | Msg: Too Many Requests
b3ab3f21-8ca3-4d81-b29b-344a153bb574 7:41:07 AM: info Echo (v3.3.0.1) | 
SpeakCommand Sent | (The Smart Home Monitor is now set to off) | 
Runtime: (4 sec) | QueueItems: (0) | Execution Time: (244ms)
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:05 AM: info SHM COMPLETED 
DISARM CHILDREN:1 ISA:c79c6958-0a83-4cae-8922-75b8d90630f1, TIME:0.264
2bec3d57-334d-424a-a829-77868af3af31 7:41:05 AM: trace 
onSecurityEnable(MODE_DISABLE)
2bec3d57-334d-424a-a829-77868af3af31 7:41:05 AM: debug summaryData: 
[[icon:indicator-dot-gray, iconColor:#878787, value:Disarmed], 
[icon:indicator-dot-green, iconColor:#79b821, value:Everything OK, 
heroInfo:[heroStatus:ok, heroMessage:Everything OK]]] - 
[[icon:indicator-dot-gray, iconColor:#878787, value:Disarmed], 
[heroInfo:[heroMessage:Everything OK, heroStatus:ok], 
icon:indicator-dot-green, iconColor:#79b821, value:Everything OK]]
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:05 AM: trace unscheduling 
delayed alarms
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:05 AM: trace 
/unsubscribeChildApps
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:04 AM: trace removing 
subscriptions to Alert with Lights
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:04 AM: trace 
unsubscribeChildApps()
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:04 AM: info SHM - 
dismissSirens() wasn't executed because there is no active incident
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:04 AM: info SHM TRYING DISARM 
CHILDREN: 1 ISA: c79c6958-0a83-4cae-8922-75b8d90630f1
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:04 AM: info SHM armDisarmCheck 
executing off
33585d86-365a-407b-93a5-0888385934e1 7:41:05 AM: debug INITIALIZED, 
settings: [triggerResetTime:1579397501807, lightDevices:[Bedroom, 
Kitchen, Piano Light, WeMo Back Yard, Hallway, Front Door Light, WeMo 
North Patio, Living RM pole, Color], lightLevel:100, color:Red]
33585d86-365a-407b-93a5-0888385934e1 7:41:05 AM: debug Updated with 
settings: [triggerResetTime:1579397501807, lightDevices:[Bedroom, 
Kitchen, Piano Light, WeMo Back Yard, Hallway, Front Door Light, WeMo 
North Patio, Living RM pole, Color], lightLevel:100, color:Red]
cf5a4931-6b3a-47ee-994d-8afc78e453c8 7:41:04 AM: info 
postEventToEndpoint: event successfully posted.
cf5a4931-6b3a-47ee-994d-8afc78e453c8 7:41:04 AM: debug 
doesTvSupportVoice SmartSense Motion: false
cf5a4931-6b3a-47ee-994d-8afc78e453c8 7:41:04 AM: debug Property Changed 
event motion: active (source: DEVICE)
cf5a4931-6b3a-47ee-994d-8afc78e453c8 7:41:04 AM: debug 
routeEndpointEvent event name: motion, physical?: false
1f7c6c2f-2b79-4aaf-bf23-027aed909017 7:41:04 AM: trace Not sending 
alert, no preferences set
1f7c6c2f-2b79-4aaf-bf23-027aed909017 7:41:04 AM: trace oncePerDayOk = 
true
1f7c6c2f-2b79-4aaf-bf23-027aed909017 7:41:04 AM: debug HH autoExecute(), 
newMode: null
956f7f14-d4e1-4860-971c-58b2ece25f5a 7:41:04 AM: debug HH auto execute 
Disarm Things Start Happening
956f7f14-d4e1-4860-971c-58b2ece25f5a 7:41:04 AM: trace daysOk = true
956f7f14-d4e1-4860-971c-58b2ece25f5a 7:41:04 AM: debug startTime: 
2017-01-22T05:00:00.000-0800, endTime: 2017-01-22T10:30:00.000-0800, t0: 
Tue Jan 21 15:41:04 UTC 2020
956f7f14-d4e1-4860-971c-58b2ece25f5a 7:41:04 AM: trace 
motionActiveHandler(motion: active), timeOfDay: 
2017-01-22T05:00:00.000-0800, endTime: 2017-01-22T10:30:00.000-0800
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:04 AM: info SHM 
isActiveSensor(motion:active, app: off, location: off) = false, 
locationId: b8fc2f84-e50f-4f67-8d07-d5a2bdea6198, ISA: 
c79c6958-0a83-4cae-8922-75b8d90630f1
c79c6958-0a83-4cae-8922-75b8d90630f1 7:41:04 AM: debug 
motionOrContactHandler(Motion Bedroom motion:active)
  7:41:59 AM: info Waiting on events...
  7:41:59 AM: info For past logs for individual things go to the My 
Devices section, find the device and click on the Events link on the 
device information page.
  7:41:59 AM: info This console provides live logging of your 
SmartThings.


------ Original Message ------
From: "Alan Weinstein" <adw770@gmail.com>
To: "tonesto7/echo-speaks" 
<reply@reply.github.com>; 
"tonesto7/echo-speaks" <echo-speaks@noreply.github.com>
Cc: "Mention" <mention@noreply.github.com>
Sent: 1/20/2020 8:44:14 PM
Subject: Re[2]: [tonesto7/echo-speaks] [Feature Request] (#215)
