### ISSUE TITLE
(BUG) conditions not working with SHM 

### ISSUE THREAD

**Issue by adw770** [tonesto7/echo-speaks#218]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings):
-  How many devices are detected?: All
-  iOS or Android?: iOS
-  Mobile App Version(Not required):
-  App/SmartApp Version:
-  Device Handler/Driver Version:
-  Heroku Server Version:

## Expected Behavior
**tell us what should happen** If conditional trigger applied action should only occur when conditions met 

## Current Behavior
**What happens instead of the expected behavior?** conditions not working when configured based on SHM

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

Will respond with example pics and details to response email.  I also opened a feature enhancement with you a few days ago. 

## Context
**How has this issue affected you? What are you trying to accomplish?  Negative impact is that option keeps speaking even though it should speak only when conditions are met.   

Goal to to announce change to SHM only when it changed from Arm to Disarm or vis-versa. 

**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
This is on my list of repairs for the next release.

**Comment by tonesto7** [comment]
Just so I’m clear are you using SHM (classic) or STHM (New App)?

**Comment by adw770** [comment]
I mainly use classic app.  I do have both installed and someday they will
finish the migration to the new.
