### ISSUE TITLE
(BUG) Error 500: Internal Server Error when trying to publish code for this SmartApp.

### ISSUE THREAD

**Issue by ZacharyAC14** [tonesto7/echo-speaks#222]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [X ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Smartthings
-  How many devices are detected?: 0
-  iOS or Android?: iOS
-  Mobile App Version(Not required):
-  App/SmartApp Version: N/A
-  Device Handler/Driver Version: N/A
-  Heroku Server Version: N/A

## Expected Behavior
**tell us what should happen**
I should be able to publish the echo-speaks smartapp code from your repo to my smartthings IDE.

## Current Behavior
**What happens instead of the expected behavior?**
When I try to publish the code, I get an internal server error (500). I'm following your directions exactly. I've installed other of your smartapps including the recent Smartthings V2 without this issue.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Please see attached screenshot
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
I'm not able to install Echo-Speaks
![500_Internal_EchoSpeaks](https://user-images.githubusercontent.com/59495138/73139048-7be4a500-401e-11ea-8bf9-a7da1d4d3988.jpg)

**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by ZacharyAC14** [comment]
Closed without a response?

**Comment by tarunsinghal92** [comment]
This is not a bug. Just install/publish `Echo Speaks` first and then `Echo Speaks-Actions` & `Echo Speaks-zones` to avoid this error
