### ISSUE TITLE
Non-Amazon Alexa Devices (FitBit Versa 2 with Alexa)

### ISSUE THREAD

**Issue by chadbaldwin** [tonesto7/echo-speaks#223]
May be duplicate of #45 but just in case, leaving this anyways. If you need any sort of screenshots or more info, I'm more than happy to help.

**Is your feature request related to a problem? Please describe.**
Not really sure...Either it's just not supported due to limitations. Or maybe this is something that could be easily implemented.

**Describe the solution you'd like**
I have a FitBit Versa 2. It has Alexa built in. You can do pretty much everything on it that you can do with a normal alexa device, except instead of there being verbal announcements, they're transcribed and vibrate the watch. However, alexa.amazon.com and the Alexa app still allows you to create reminders online. So I'm hoping that if the website allows it, that the integrations/api's do as well.

**Describe alternatives you've considered**
None...as of now, I just do everything manually via alexa web UI or alexa app.

The reason I need this is because I work from home, and many times I have my headphones on. So when I create a new reminder for the kitchen or office Echo, I want it to also sound off on my watch. I was planning on creating a WebCoRE piston that just has all of my daily reminders.

**Comment by tonesto7** [comment]
Thanks for opening a request. 
Under the Echo Speaks smartapp in SmartThings/Hubitat there is a devices section that will list all of your devices.  I need the deviceType id that listed there for the Fitbit

**Comment by chadbaldwin** [comment]
I've tried just about everything I can, but it does not show up in the list.

It's pretty common for the watch to show as offline and disappear from the Alexa app, so I also tried keeping the watch active, making sure it says online in the app and then refreshing the app... But still no luck.

And yes, I have the app set to ignore developer device filters.

**Comment by tonesto7** [comment]
try going here https://alexa.amazon.com/api/devices/v3

This will be a large chunk of data but will list all devices on your account.

**Comment by chadbaldwin** [comment]
Ah okay, here's the device type: A2XPGY5LRKB9BE

Looks like it was hidden as part of #144

**Comment by tonesto7** [comment]
I've added support to the new database.  You will see these enabled in the next code release (On Monday)
