### ISSUE TITLE
(BUG) Actions SHM trigger Issue

### ISSUE THREAD

**Issue by adw770** [tonesto7/echo-speaks#224]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):SmartThings
-  How many devices are detected?:any shm
-  iOS or Android?:iOS
-  Mobile App Version(Not required):13.3
-  App/SmartApp Version:3.4.0
-  Device Handler/Driver Version:
-  Heroku Server Version:

## Expected Behavior
**tell us what should happen**
I have 3 SHM triggers. arm stay, arm away, and disarm. If I select away stay as my tigger then switching to that show announce. Switching to disarm should not fire that routine. 
## Current Behavior
**What happens instead of the expected behavior?**
Now that I applied latest version if I select SHM as trigger for Arm Stay regardless of mode the routine is firing. So setting system to disarm is announcing home armed. Setting to Arm Stay announces same message and arm away does the same. Please respond and I’ll debug tomorrow and send the event log and any other information you may want me to gather. 

PS.. I only donate to few applications yet you’re one I felt warranted a donation. Even though it was small I know every amount helps and confirms your effort isn’t just in  vain.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
@adw770 I'm not able to duplicate this.  Can you provide some screens of your current settings?

**Comment by adw770** [comment]
I will work on reconfiguring and duplicate. I will also try to capture 
logs for you.

------ Original Message ------

**Comment by adw770** [comment]
Sorry I did complete steps requested. Recently had surgery so this is on
back burner.  For now I paused events.  I’ll redo once I recover as will
reopen issue is f needed.  Will make sure I have latest installed before
retesting.
