### ISSUE TITLE
(ACTIONS BUG) 

### ISSUE THREAD

**Issue by avioniqueca** [tonesto7/echo-speaks#226]
It looks like there is an issue with single quotes (') in the Echo Speak Response Designer. In french we often use single quotes like : "C'est pas ok" witch means "It's not ok". The editor sometime strips those quotes after hitting the "Save responses" button. Not all of them are removed though. They're must a way to properly escape them? Please advise.

**Comment by tonesto7** [comment]
@avioniqueca Thanks for reporting this. 
I will need to think about how to persist these.
Does Alexa read them any differently when they are not used?

**Comment by avioniqueca** [comment]
Yes, there is a big difference in the way Alexa read them. In some case, it changes the meaning of the whole sentence. French is weird like that. For now, I'm replacing the words with quotes with other words that does not contain quotes and "sounds" the same in order for Alexa to output a sentence that sounds right. For exemple, if I need Alexa to say "Je **n'ai** pas accès" (means I do not have access), I would write "Je **nez** pas accès" (witch translates to: I nose no access).

**Comment by tonesto7** [comment]
In today's release you will see that the ' is no longer filtered out.

**Comment by avioniqueca** [comment]
Looks like I can't update the Echo speak device driver to v3.5.0.0. I get that error: "No signature of method: static com.hubitat.hub.dao.DeviceDao.getState() is applicable for argument types: (null) values: [null] Possible solutions: getState(long), getData(long), getClass(), getAt(java.lang.String) on line 2980".
Also, the bug is partially corrected. It saves correctly initially, but the quotes gets deleted again when I re-open the popup page to edit a message containing single quotes.
