### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by scorrigan** [tonesto7/echo-speaks#228]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: UNKNOWN
name: Sean's Jabra Elite 75t
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode
type: AKKLQD9FZWWQS

**Comment by tonesto7** [comment]
I've added this as a blocked device
