### ISSUE TITLE
(BUG) 

### ISSUE THREAD

**Issue by jsarcone** [tonesto7/echo-speaks#229]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Hubitat
-  How many devices are detected?: 6
-  iOS or Android?: Both
-  Mobile App Version(Not required):
-  App/SmartApp Version:3.4.0.0
-  Device Handler/Driver Version:3.4.0.0
-  Heroku Server Version:2.3.1

## Expected Behavior
**tell us what should happen**

## Current Behavior
**What happens instead of the expected behavior?**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
I removed an action and started receiving this.

I keep getting this message on Hubitat.
 • There appears to have been a change to Amazons API resulting in log entries like this: | Status: (400) | Message: Bad Request | Data: [message:Rate exceeded]/nI'm out of town for work and will look into it more when I return

**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug.
Error EchoApp (v3.4.0.0) | getDoNotDisturb | Request Timeout | Msg: Connect to alexa.amazon.com:443 [alexa.amazon.com/13.226.99.201] failed: connect timed out

**Comment by tonesto7** [comment]
@jsarcone Thanks for reporting... I have some fixes in the works.  Hopefully releasing them in the next couple days.

**Comment by jsarcone** [comment]
Very good! Thank you for the quick response.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tonesto7** [comment]
The message you were seeing is a notice I added to let users know i'm aware of the issue.  I will be removed once I release the next version.

**Comment by jsarcone** [comment]
I'm still seeing this issue please let me know when it will be fixed.  Thanks.
