### ISSUE TITLE
Fire tablet shows as Echo 

### ISSUE THREAD

**Issue by GRClark** [tonesto7/echo-speaks#23]
Fire HD 8 showing up as Echo Dot Gen 1
https://drive.google.com/file/d/1T5_B1NSwbjnAy5XbCiwmncHDSz_68jxA/view?usp=drivesdk

**Comment by joelw135** [comment]
I have the same problem om my Fire HD 8 2017

**Comment by tonesto7** [comment]
This is fixed as of the next the release i'm pushing out in a couple hours.
