### ISSUE TITLE
(BUG)  getDeviceActivity | Status: (400) | Message: Bad Request | Data: [message:Rate exceeded]

### ISSUE THREAD

**Issue by audiofreak9** [tonesto7/echo-speaks#230]
-  [ X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ X] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ X] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ X] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Smartthings
-  How many devices are detected?: 13 devices // 3 groups
-  iOS or Android?: iOS
-  Mobile App Version(Not required): 
-  App/SmartApp Version: v3.4.0.0
-  Device Handler/Driver Version: v3.4.0.0
-  Heroku Server Version: v2.3.1

## Current Behavior
Every 5 minutes or so I get the following ERROR in my logs: 

> Echo (v3.4.0.0) | getDeviceActivity | Status: (400) | Message: Bad Request | Data: [message:Rate exceeded]

Do I have too many devices configured such that it is hitting a response rate limit?  If so are you aware of a hard limit?  Thanks for the great app!

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
I'm rolling out the fixes for this today
