### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by akeys111** [tonesto7/echo-speaks#231]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: THIRD_PARTY_AVS_MEDIA_DISPLAY
name: Bathroom
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode, bluetoothControl
type: AO6HHP9UE6EOF

**Comment by TonyFleisher** [comment]
What type of device (Brand/Model) is this?

**Comment by tonesto7** [comment]
Added as a generic device for now
