### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by JoeHennessy** [tonesto7/echo-speaks#233]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: MSHOP
name: Joe's Alexa Apps
permissions: volumeControl, spotify, microphone
type: A3NWHXTQ4EBCZS

**Comment by tonesto7** [comment]
Can't add support for MSHOP alexa apps.
