### ISSUE TITLE
[Feature Request] Support Amazon Smart Oven

### ISSUE THREAD

**Issue by n3pjk** [tonesto7/echo-speaks#235]
I just installed an Amazon Smart Oven, which has a built-in Alexa button, but ES did not recognize it, nor set up a device for it, even though I have "Create Other Alexa-enabled Devices" turned on. 

I would like ES to create a Smart Oven device, or, at least add the permissions to the Echo devices to allow me to control the oven and respond to notifications with actions.

I have been unable to identify any other alternatives for smart home integration with this device; however, GE has similar products that integrate with Alexa through a skill called "Geneva". 

**Additional context**
Note that the Amazon Smart Oven is a combination microwave, convection oven and air fryer. There is also an AmazonBasics Microwave, that is Alexa controlled as well.

**Comment by tonesto7** [comment]
This is not what ES was for.  It's a tool to manage your echo enabled devices.  If they don't show up as an unrecognized device than they don't meet the criteria to be used with ES.

The app will prompt you to submit a GitHub issue to add support for an unrecognized device if one was found.

**Comment by n3pjk** [comment]
As near as I can tell, the oven *is* an echo enabled device. It has an Alexa button and does not require any skills to support it. Alexa recognizes it as a cooking device. I suspect that there are simply additional Echo permissions specific to cooking devices.

________________________________

**Comment by TonyFleisher** [comment]
Echo Speaks is designed for using alexa speakers as speech devices. Since the smart oven doesn't have its own speaker, it really isn't something we can address. (Though echo-speaks should work with the echo dot companion speaker.)

**Comment by n3pjk** [comment]
It sounds like this functionality lies outside the speech api. I guess my next task is to identify that api.

________________________________

**Comment by tonesto7** [comment]
there is no api that’s accessible for this outside the alexa device’s themselves
