### ISSUE TITLE
(BUG) with new smartthings app 

### ISSUE THREAD

**Issue by alextheangel** [tonesto7/echo-speaks#237]
Controlling at new smartthings app no longer show track info or even the play/pause botton along with volume control 
![Screenshot_20200212-002037_SmartThings](https://user-images.githubusercontent.com/15373261/74305681-9c0aa880-4d2e-11ea-9f8c-f4831ec73dd4.jpg)
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):
-  How many devices are detected?:
-  iOS or Android?:
-  Mobile App Version(Not required):
-  App/SmartApp Version:
-  Device Handler/Driver Version:
-  Heroku Server Version:

## Expected Behavior
**tell us what should happen**

## Current Behavior
**What happens instead of the expected behavior?**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
This isn't a bug.  ST hasn't released the metadata for creating the custom interface found in the classic app.

Once they release the spec I will add support immediately.

**Comment by alextheangel** [comment]
However it was function before the 3.5.0.0 update


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by tonesto7** [comment]
That is not correct because v3.5.0 changed nothing with the device interface.  
This is likely a side effect of the recent ST Mobile App update.

**Comment by alextheangel** [comment]
This what it was before the 3.5.0.0 update. It shows track info , control and volume
[Image]

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by tonesto7** [comment]
I'm trying to tell you that I made no changes to the device code at all between now and v2.x.x! 
I think the latest Mobile App update broke support for generic-media metadata tag

**Comment by alextheangel** [comment]
I am not blaming you, thanks for your work. Just to point out what happened, I don’t know what makes the difference on interface. And just a note for you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
