### ISSUE TITLE
(BUG) Can't save the device driver code on Hubitat

### ISSUE THREAD

**Issue by rfoust** [tonesto7/echo-speaks#240]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):Hubitat
-  How many devices are detected?:3
-  iOS or Android?:n/a
-  Mobile App Version(Not required):
-  App/SmartApp Version:
-  Device Handler/Driver Version:3.5.0.0
-  Heroku Server Version:

## Expected Behavior
I should be able to import & save the device driver

## Current Behavior
When I click save, I get this error: "No signature of method: static com.hubitat.hub.dao.DeviceDao.getState() is applicable for argument types: (null) values: [null] Possible solutions: getState(long), getData(long), getClass(), getAt(java.lang.String)"

The import url I used is: https://raw.githubusercontent.com/tonesto7/echo-speaks/master/drivers/echo-speaks-device.groovy

## Steps to Reproduce (for bugs)
Just try to import the url and click save.

## Context
**How has this issue affected you? What are you trying to accomplish? Initial setup.
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by spydermb** [comment]
Having same issue

When I try to import the habitat device drive over the existing one I get this error

No signature of method: static com.hubitat.hub.dao.DeviceDao.getState() is applicable for argument types: (null) values: [null] Possible solutions: getState(long), getData(long), getClass(), getAt(java.lang.String) on line 2980

**Comment by tonesto7** [comment]
Sorry.  I'm just getting home from work... I'm taking a look at it now

**Comment by spydermb** [comment]
Thanks

**Comment by tonesto7** [comment]
Ok. i've pushed out the fix... It may take about 5 minutes for the import to import the latest code. 

Look for 2-13-2019 date value in the header variable

**Comment by spydermb** [comment]
Okay,  thanks for all u do

**Comment by spydermb** [comment]
That did the trick, all working now

**Comment by rfoust** [comment]
Same here, works great now! Thanks!
