### ISSUE TITLE
Volume isn’t updating/correct

### ISSUE THREAD

**Issue by GRClark** [tonesto7/echo-speaks#25]
Volume isn’t showing the correct level or updating on any device.

**Comment by GRClark** [comment]
Additionally if I go into SmartThings app and mute the device then unmute it’ll restore volume to wrong level showing in device instead of level it was actually at before muting.

**Comment by tonesto7** [comment]
What type of device is this?

**Comment by GRClark** [comment]
Echo Show gen 2

**Comment by tonesto7** [comment]
Thanks I’m investigating now

**Comment by tonesto7** [comment]
I'm not able to duplicate the mute issue on any of my devices.  
I'm not saying your wrong I just don't have any show gen2 to validate against.

**Comment by TonyFleisher** [comment]
Is this still an issue with the latest release (2.0.2)?

**Comment by GRClark** [comment]
Yes it is still an issue.  Adjusting volume in SmartThings app device seems to control Echo volume but if you adjust volume on Echo it doesn’t update in SmartThings app.

**Comment by TonyFleisher** [comment]
Do you have music playing when you do this? so far we only have access to volume with player data which is only available when music is playing

**Comment by GRClark** [comment]
Yes Music was playing.

**Comment by googlejam** [comment]
I just installed and seeing something strange as well.  When testing from the app or from the device the volume is quite low.  Looking at the devices the volume is 0%.  When I try to change the volume, I can raise the slider but when you exit back to the device the volume still shows 0%.

**Comment by an565** [comment]
I'm using BigTalker2 and not sure how to set the volume for each Echo.  If its under the config for the "Echo Thing" then I have the 0% problem mentioned above as well with Gen 2 Dots. Volume level is stuck at 0% and they also don't speak. My Gen 1 Echo sets OK but the volume % doesn't always match perfectly what I set it to. I may set to 60% but get 56%, for example. 

Also, I have a multi-room device, and that doesn't seem to speak at all.
