### ISSUE TITLE
[ADD DEVICE SUPPORT] (2) Devices

### ISSUE THREAD

**Issue by cwilliams3579** [tonesto7/echo-speaks#257]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, doNotDisturb, microphone, followUpMode
name: Cleveland's Alexa Gear
description: What kind of device/model?(PLEASE UPDATE THIS)
family: UNKNOWN
type: A2C8J6UHV0KFCV

permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, doNotDisturb, microphone, followUpMode
name: Cleveland's 2nd Alexa Gear
description: What kind of device/model?(PLEASE UPDATE THIS)
family: UNKNOWN
type: A2C8J6UHV0KFCV

**Comment by TonyFleisher** [comment]
Can you provide details on what the make and model of the device is?

**Comment by JamesMarcum** [comment]
I found that once it's working, if you use it in a routine put a wait on the Alexa side for as many seconds as the talking will take or it aborts the rest of the routine.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 29, 2020 at 3:43 PM, TonyFleisher<notifications@github.com> wrote:   
Can you provide details on what the make and model of the device is?

**Comment by tonesto7** [comment]
I've added this to the list and will be available on v3.6

**Comment by cwilliams3579** [comment]
Awesome thanks!
