### ISSUE TITLE
Manage Actions Page will not open in app on Note8 Android 

### ISSUE THREAD

**Issue by LukeRuppSr** [tonesto7/echo-speaks#259]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform SmartThings
-  13 devices are detected?:
-   Android
-  Mobile App Version(Not required):
-  App/SmartApp Version: v3.6.00
-  Device Handler/Driver Version: v3.6.00
-  Heroku Server Version: v2.4.0

## Expected Behavior
The The Manage Actions page should open

## Current Behavior
The manage actions page returns "Something Wrong - We can't load you page right now."

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Open ST app on smartphone, navigate to SmartApps and open the Echo Speaks app. 
Select manage actions and the manage actions page opens with noted error. 

## Context
**How has this issue affected you? What are you trying to accomplish?
I am not able to modify or add actions.
It worked well up until a few days ago. 
I vaguely remember adding a new action for a valve status change before the issue came up. 

I have checked at Oath is on, all apps are current and configured.
The Echo Speaks app continues to work but I can not add or change the Manage Actions page 

Thanks,
Luke

**Comment by LukeRuppSr** [comment]
I updated the 3 apps and 1 device handler to "3.6.1.0" The behavior did not change, I am still not able to access the "Manage Actions" page in the app. Thanks.

**Comment by TonyFleisher** [comment]
Is there any errors in live logging from Echo Speaks or Actions when you try to access the page?

**Comment by LukeRuppSr** [comment]
When I open the app I see these entries:

cbdafd70-d339-4f01-9517-b21ba7de1f1c
<https://graph-na02-useast1.api.smartthings.com/ide/logs#cbdafd70-d339-4f01-9517-b21ba7de1f1c>
 8:25:16 PM: info EchoApp (v3.6.1.0) | wakeupServer Completed... | Process
Time: (105ms)
cbdafd70-d339-4f01-9517-b21ba7de1f1c
<https://graph-na02-useast1.api.smartthings.com/ide/logs#cbdafd70-d339-4f01-9517-b21ba7de1f1c>
 8:25:16 PM: info EchoApp (v3.6.1.0) | wakeupServer Completed... | Process
Time: (105ms)
cbdafd70-d339-4f01-9517-b21ba7de1f1c
<https://graph-na02-useast1.api.smartthings.com/ide/logs#cbdafd70-d339-4f01-9517-b21ba7de1f1c>
 8:25:16 PM: info EchoApp (v3.6.1.0) | GuardSupport Response Length: 497713

When I open the Manage Actions page I see no entries.

Thanks for responding.
I hate to have to delete the whole thing and start over again.
It generally works well and is somewhat amazing.
Right now all the automations are working fine.
But I can not add or modify Actions.

Maybe I should start over ?

Thanks,
Luke

**Comment by LukeRuppSr** [comment]
I was contemplating deleting the actions app in an attempt to resolve the
issue without uninstalling the entire app due to the number of automations
I have.
Then I decided to delete the actions app and the IDE would not let me
delete it with a message "Not deleted as in use by one or more users" or
something like that.
Is it possible the issue could be related to a device I deleted or such
that is referenced in the actions app?
Is there code to time out if a device has been removed?
In the UI the "Manage Actions" section presents the following:
"(9) Active

Tap to Modify"

**Comment by LukeRuppSr** [comment]
Updated server to version v2.4.1. No change in behavior. "Manager Actions" will still not populate. App continues to function otherwise.

**Comment by tonesto7** [comment]
Something was not installed correctly... 
Under the IDE > My Locations > Under the Installed SmartApps Column click smartapps > look for any child action apps and scroll to top of the page and click edit and scroll back down and click delete next to the app to remove.

**Comment by LukeRuppSr** [comment]
Removing the actions via that panel on the IDE resolved the issue.
That saved me a lot of time as opposed to deleting the entire app and
starting over.
Thanks.
Luke

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
