### ISSUE TITLE
[Feature Request] CO2 (Carbon Dioxide) Sensors

### ISSUE THREAD

**Issue by Ra7t0r** [tonesto7/echo-speaks#261]
Hello
Is this possible to add CO2 sensors available as triggers for an action?
I wish to create and ESpeaks alert when carbon dioxide concentration is high.

Thanks

**Comment by tonesto7** [comment]
I will get this added in for the next push

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ra7t0r** [comment]
Hey. I hope you are doing well.
Any updates regarding this specific trigger?
Thanks
