### ISSUE TITLE
Notification Settings Not Working

### ISSUE THREAD

**Issue by GRClark** [tonesto7/echo-speaks#262]
forgive me if it’s already been mentioned but tapping notifications in smartapp doesn’t do anything. Get spinning wheel then nothing.  ![Image](https://i.imgur.com/4t77AMe.jpg)

**Comment by tmleafs** [comment]
Pressing on the notification for me I get the "Something's Wrong" Message 

In the IDE I get the following
`groovy.lang.MissingMethodException: No signature of method: java.lang.String.join() is applicable for argument types: (java.lang.String) values: [ - ] Possible solutions: wait(), trim(), find(), wait(long), split(java.lang.String), find(java.util.regex.Pattern) @line 3948 (getNotifSchedDesc)`

**Comment by tmleafs** [comment]
Im still getting "somethings wrong" message

IDE Shows
`groovy.lang.MissingMethodException: No signature of method: java.lang.String.join() is applicable for argument types: (java.lang.String) values: [- ]
Possible solutions: wait(), trim(), find(), wait(long), split(java.lang.String), print(java.lang.Object) @line 3994 (getNotifSchedDesc)`
