### ISSUE TITLE
(BUG) UK Cookie lasting hours

### ISSUE THREAD

**Issue by tmleafs** [tonesto7/echo-speaks#263]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [X] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [X] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): ST 
-  How many devices are detected?:12
-  iOS or Android?: andriod
-  Mobile App Version(Not required):
-  App/SmartApp Version: 3.6.1.0
-  Device Handler/Driver Version: 3.6.0.1
-  Heroku Server Version: 2.4

## Expected Behavior
Stay logged in for months

## Current Behavior
since 2.4 upgrade its hours with 24 hours max before I have to redo cookie, located in the UK.
Still using the beta branch if you want help testing

**Comment by Toggz** [comment]
Same problem here in the UK, using server v2.4 cookie expires within 2hrs. Dropped back to v2.3.1 and all ok.

**Comment by tonesto7** [comment]
Try the latest smart app and server version
