### ISSUE TITLE
(BUG) Cannot get deviceSerialNumber for use with sendAnnouncementToDevices()

### ISSUE THREAD

**Issue by SANdood** [tonesto7/echo-speaks#268]
Following how Echo Actions call sendAnnouncementToDevices, I cannot get the deviceSerialNumber to create the devObj required, as the direct call used by Echo Actions works because it is a common child of the parent "Echo Speaks". Unfortunately, my app is not a child of "Echo Speaks", and so `getEchoSerial()` only returns "null".

There is existing logic to store the needed `deviceType` as an attribute of the device, so I can get to that. I/we need the same done for `deviceSerialNumber`.

**Comment by tonesto7** [comment]
I thought I exposed the serial number as an attribute but maybe not.

Here is a good way to get the echo devices into your app as a device object.
You can specifically target the ES devices using this input:

```input "esDevices", "device.EchoSpeaksDevice", title: "Select Echo Speaks Devices", description: "Tap to select", multiple: true, submitOnChange: true```

**Comment by SANdood** [comment]
Thanks - the serial number is in the deviceNetworkId, which works for most of my use cases. An attribute would be better for when I’m using HubConnect, as the remote device can’t see the host device’s DNI. 

Thanks!
      Barry

**Comment by tonesto7** [comment]
i will add in an attribute.
