### ISSUE TITLE
Archive URL not found

### ISSUE THREAD

**Issue by aldo-raine** [tonesto7/echo-speaks#27]
Using the ST-Community-Installer... I get "Archive URL not found" when deploying heroku app.

![img_1007](https://user-images.githubusercontent.com/32476380/49379487-3c058480-f6dd-11e8-87a5-419e700f7835.PNG)

**Comment by tonesto7** [comment]
This is an issue on Heroku side with New deployments... Please see the community forum for instructions on how to get around this
