### ISSUE TITLE
(BUG) Devices not appearing in app + Multiple errors in log

### ISSUE THREAD

**Issue by SebastienViel** [tonesto7/echo-speaks#270]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [X] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [X] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Hubitat 
-  How many devices are detected?: 0
-  iOS or Android?: iOS
-  Mobile App Version(Not required):
-  App/SmartApp Version: 3.6.1.1
-  Device Handler/Driver Version: 3.6.1.0
-  Heroku Server Version: 2.4.1

## Expected Behavior
When opening the app, under “Manage Devices”, I should see my 6 devices.  When going in this menu, I should see my 6 devices.
Log is clear of errors.

## Current Behavior
When opening the app, under “Manage Devices”, I see “(0) Installed” devices.  When going in this menu, I see “No Devices Available”.
There are multiple errors in the log.

## Steps to Reproduce (for bugs)
Follow the installation instructions on a first hub.  Find that all is as expected.
Follow the installation instructions on a second hub.  Find that the devices are installed, but not showing up in the app.

## Context
I am unable to see device details. 

Logs:
app:122020-03-23 17:39:42.821 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 17:29:42.017 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 17:28:13.517 errorsendPlaybackStateToClusterMembers Error: java.lang.NullPointerException: Cannot get property 'd7cecb96f54b417da806cac8de44b4a3' on null object
app:122020-03-23 17:28:12.034 errorsendPlaybackStateToClusterMembers Error: java.lang.NullPointerException: Cannot get property '0d9a06d35fbb4afb837cffa67ba6823f' on null object
app:122020-03-23 17:28:09.082 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 17:28:08.368 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Everywhere (WHA))
app:122020-03-23 17:28:07.705 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Family Room Echo Show)
app:122020-03-23 17:28:07.085 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Downstairs (WHA))
app:122020-03-23 17:28:06.454 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Master Bedroom Echo Dot)
app:122020-03-23 17:28:05.765 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Dining Room Echo Dot)
app:122020-03-23 17:28:04.949 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Den Echo Dot)
app:122020-03-23 17:27:33.508 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 17:27:28.483 warn EchoApp (v3.6.1.1) | removeDevices() | In Use: (0) | Removing: (0)
app:122020-03-23 17:27:27.046 warn EchoApp (v3.6.1.1) | removeDevices() | In Use: (0) | Removing: (0)
app:122020-03-23 17:27:24.192 warn EchoApp (v3.6.1.1) | removeDevices() | In Use: (0) | Removing: (0)
app:122020-03-23 17:27:20.488 warn EchoApp (v3.6.1.1) | removeDevices() | In Use: (0) | Removing: (6)
app:122020-03-23 17:25:28.220 errorsendPlaybackStateToClusterMembers Error: java.lang.NullPointerException: Cannot get property 'd7cecb96f54b417da806cac8de44b4a3' on null object
app:122020-03-23 17:25:26.648 errorsendPlaybackStateToClusterMembers Error: java.lang.NullPointerException: Cannot get property '0d9a06d35fbb4afb837cffa67ba6823f' on null object
app:122020-03-23 17:25:23.818 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 17:25:23.072 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Everywhere (WHA))
app:122020-03-23 17:25:22.244 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Family Room Echo Show)
app:122020-03-23 17:25:21.632 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Downstairs (WHA))
app:122020-03-23 17:25:20.856 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Master Bedroom Echo Dot)
app:122020-03-23 17:25:20.107 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Dining Room Echo Dot)
app:122020-03-23 17:25:19.383 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Den Echo Dot)
app:122020-03-23 17:25:12.691 warn EchoApp (v3.6.1.1) | removeDevices() | In Use: (0) | Removing: (0)
app:122020-03-23 17:24:59.746 warn EchoApp (v3.6.1.1) | removeDevices() | In Use: (0) | Removing: (6)
app:122020-03-23 17:24:11.746 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 17:24:07.502 info EchoApp (v3.6.1.1) | Updated Event Received...
app:122020-03-23 17:24:07.299 errorsendPlaybackStateToClusterMembers Error: java.lang.NullPointerException: Cannot get property 'd7cecb96f54b417da806cac8de44b4a3' on null object
app:122020-03-23 17:24:05.165 errorsendPlaybackStateToClusterMembers Error: java.lang.NullPointerException: Cannot get property '0d9a06d35fbb4afb837cffa67ba6823f' on null object
app:122020-03-23 17:24:03.269 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 17:24:01.753 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Everywhere (WHA))
app:122020-03-23 17:24:00.639 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Family Room Echo Show)
app:122020-03-23 17:23:59.722 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Downstairs (WHA))
app:122020-03-23 17:23:58.529 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Master Bedroom Echo Dot)
app:122020-03-23 17:23:57.111 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Dining Room Echo Dot)
app:122020-03-23 17:23:55.444 info EchoApp (v3.6.1.1) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Den Echo Dot)
app:122020-03-23 17:23:48.814 warn EchoApp (v3.6.1.1) | removeDevices() | In Use: (0) | Removing: (6)
app:122020-03-23 17:23:22.070 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 17:13:21.765 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 17:03:21.057 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 16:53:21.529 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 16:43:21.305 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 16:33:21.356 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 16:23:21.436 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 16:13:21.345 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 16:03:21.096 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 15:53:21.344 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 15:43:21.256 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 15:33:21.635 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 15:23:21.000 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 15:13:22.458 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 15:03:21.747 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 14:53:21.156 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 14:43:21.746 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 14:33:21.209 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 14:23:21.241 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 14:13:21.724 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 14:03:21.903 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 13:53:21.343 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 13:43:21.236 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 13:33:21.459 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 13:23:21.396 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 13:13:21.256 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 13:03:21.288 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 12:53:21.183 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 12:43:21.398 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 12:33:21.079 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 12:23:21.198 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 12:13:21.215 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 12:03:21.145 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 11:53:20.904 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 11:43:21.461 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 11:33:21.039 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 11:23:21.369 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 11:13:21.368 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 11:03:21.512 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 10:53:21.538 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 10:43:21.772 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 10:33:21.609 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 10:23:21.399 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 10:13:21.431 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 10:03:21.545 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 09:53:21.736 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 09:43:21.757 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 09:33:21.381 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 09:23:21.537 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 09:13:21.902 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 09:03:20.992 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 08:53:21.719 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 08:43:21.552 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 08:33:21.286 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 08:23:22.203 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 08:13:21.385 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 08:03:21.658 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 07:53:21.708 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 07:43:21.150 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 07:33:21.488 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 07:23:21.569 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 07:13:21.502 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 07:03:21.236 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 06:53:21.470 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 06:43:21.786 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 06:33:21.337 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 06:23:21.350 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found
app:122020-03-23 06:13:21.482 errorEchoApp (v3.6.1.1) | receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found

**Comment by tonesto7** [comment]
This was because you were missing the WebSocket driver.
