### ISSUE TITLE
[FEATURE REQUEST] Add Button Support for Actions Triggers under Hubitat

### ISSUE THREAD

**Issue by alpaville21a14** [tonesto7/echo-speaks#271]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [X] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [X] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Hubitat
-  How many devices are detected?: 2
-  iOS or Android?: Android
-  Mobile App Version(Not required):
-  App/SmartApp Version: 3.6.1.0
-  Device Handler/Driver Version: 3.6.1.0
-  Heroku Server Version: 2.4.1

## Expected Behavior
**The triggers' list should show "button" as an option to be chosen **

## Current Behavior
**The triggers' list doesn't show "button" as an option to be chosen**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Click in manage actions
2. Click in create new action
3. Select action type
4. Select action triggers
5. Open Select Trigger Event(s)'s list
6. Button is not available as an option to be chosen

## Context
**How has this issue affected you? What are you trying to accomplish?
It prevents us to start any action from a button
**Providing context helps us come up with a solution that is most useful in the real world**
Reading the app code it seems the button is available but for any reason it is not appearing on the trigger list. I believe it could be due to any little mistake in the code

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
I've never had time to add support for buttons under hubitat.  Buttons are handled differently under Hubitat and would require some major changes to the dynamic logic in actions.
