### ISSUE TITLE
(BUG)  The "view action history" is returning error in UI (classic app)

### ISSUE THREAD

**Issue by TonyFleisher** [tonesto7/echo-speaks#272]
Please include a copy of any relevant log output to assist in tracking down the bug

org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '[Trigger: [switch]...

**Comment by tonesto7** [comment]
I'm not sure how to fix this.  I think this was a remnant of the old action history object.  It should have cleared itself by now
