### ISSUE TITLE
[Actions Feature Request]

### ISSUE THREAD

**Issue by solosolo70** [tonesto7/echo-speaks#273]
Repeat an announcement a certain number of times before stopping

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tonesto7** [comment]
This feature already exists...
Review the Configuration and Examples
https://tonesto7.github.io/echo-speaks-docs/actions/config/actions_config/

**Comment by solosolo70** [comment]
Thanks- missed that

Regards,

Anthony

Atlantic Pharmaceuticals, Inc.
Anthony Soscia
President
One Glenlake Parkway, Suite 700
Atlanta, GA 30328
Main: 404 994-5135
Direct: 404-994-5180
Fax: 404-994-5190
Web: atlanticpharma.com

**Comment by solosolo70** [comment]
I see the option to repeat x times until not active. Is there an option to repeat x times even if active? Ie – just repeat three times then stop even if active?

Regards,

Anthony

Atlantic Pharmaceuticals, Inc.
Anthony Soscia
President
One Glenlake Parkway, Suite 700
Atlanta, GA 30328
Main: 404 994-5135
Direct: 404-994-5180
Fax: 404-994-5190
Web: atlanticpharma.com

From: Anthony Soscia <asoscia@atlanticpharma.com>
Date: Monday, March 30, 2020 at 1:54 PM
To: tonesto7/echo-speaks <reply@reply.github.com>, tonesto7/echo-speaks <echo-speaks@noreply.github.com>
Cc: "asoscia@gmail.com" <asoscia@gmail.com>, Author <author@noreply.github.com>
Subject: Re: [tonesto7/echo-speaks] [Actions Feature Request] (#273)

Thanks- missed that

Regards,

Anthony

Atlantic Pharmaceuticals, Inc.
Anthony Soscia
President
One Glenlake Parkway, Suite 700
Atlanta, GA 30328
Main: 404 994-5135
Direct: 404-994-5180
Fax: 404-994-5190
Web: atlanticpharma.com

**Comment by tonesto7** [comment]
this was added in the last release
