### ISSUE TITLE
(BUG) alexaPlaylists not stored as a valid JSON format string per attribute definition in DTH

### ISSUE THREAD

**Issue by KurtSanders** [tonesto7/echo-speaks#279]
## Verify the following before opening an trouble issue

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): SmartThings
-  How many devices are detected?: 1
-  iOS or Android?: iOS
-  Mobile App Version(Not required): Classic
-  App/SmartApp Version: "3.6.1.0"
-  Device Handler/Driver Version: "3.6.1.0"
-  Heroku Server Version: 2.4.1

## Expected Behavior
The Echo Speaks SmartThings DTH defines the attribute “alexaPlaylists” as a “JSON_OBJECT”. The online Echo Speaks documentation for alexaPlaylists shows the following example (which is a valid JSON):
```
{
   "Home Audio": [
      {
          "title": "Home Audio",
          "playlistId": "a1553cd7-f732-4f7e-ac3c-995b94860e57",
          "entryList": null,
          "version": "1",
          "trackCount": 0
      }
   ]
}
```

## Device Information from Echo Speaks DTH:

deviceFamily: KNIGHT
deviceStatus: stopped_echo_show_gen2
deviceStyle: Echo Show 8
deviceType: A1Z88NGR2BK6A2
doNotDisturb: false
firmwareVer: 3523856004

## Current Behavior

My Echo Speaks device has the alexaPlaylists string value stored in current states as:

[alexaPlaylists]:
{My Griffin House=[{entryList=null, playlistId=2c06b52a-68ee-4f9b-9bb4-a4bffe31124f, title=My Griffin House, trackCount=69, version=3}]}

## Context
**How has this issue affected you? What are you trying to accomplish?

I would like to get this data string into a JSON format from a SmartApp that I am coding for playlist playback.

**Comment by tonesto7** [comment]
Thanks for opening this.  I have the changes in place and they will roll out in the next release (Tonight or Tomorrow hopefully)
