### ISSUE TITLE
[Feature Request] Add capability 'Media Presets' for alexaPlaylists 

### ISSUE THREAD

**Issue by KurtSanders** [tonesto7/echo-speaks#280]
Would like to have support for a command 'playPreset' so the from WebCore or another SmartApp one could invoke a playlist that is stored in the device's **alexaPlaylist** field.

**Comment by tonesto7** [comment]
i’ll look into this

**Comment by tonesto7** [comment]
@KurtSanders Do you have any examples of where a device handler is using the Media Presets capability
