### ISSUE TITLE
[Feature Request] Global volume for annoucements

### ISSUE THREAD

**Issue by flynhawaiian** [tonesto7/echo-speaks#281]
Using better laundry monitor or other apps in habitat it would be nice to set global announcement volume.

**Comment by tonesto7** [comment]
I'm going to need a bit more explanation of what you're looking for here.
What do you mean by global volume.

**Comment by flynhawaiian** [comment]
Basically set a global volume when anything uses the app function to __%.  This way in case the volume is low it actually sets it to a reasonable volume to be heard.  For example, I was having an issue hearing the laundry monitor app on Hubitat.  I realized I just needed to up the volume on the device directly, but it would be nice if I could set it to a certain volume for all announcements.  Not sure if that makes sense?

**Comment by tonesto7** [comment]
There are commands in ES to send the volume with speech.  I'm not sure how long it would take right now to even implement this.  
https://tonesto7.github.io/echo-speaks-docs/devicesupport/commands/speech_commands/
