### ISSUE TITLE
Functionality to deselect conditions/restrictions for Smart Home Monitor is ...

### ISSUE THREAD

**Issue by LukeRuppSr** [tonesto7/echo-speaks#283]
I am not able to deselect conditions/restrictions in actions for Smart Home Monitor.
It is possible to change the selection from Armed Away to Disarmed.
However It appears that once an alarm state is selected it can not be undone. 
Maybe I am missing something.

I would like the functionality to deselect the alarm condition to where there is no alarm condition. 

Thanks for the app.
It is the beat app on ST that I have read about or utilized.
The power and flexibility is amazing.

Also you were very helpful suggesting how to remove a bad action that was preventing my Actions screen from populating. I appreciate the assistance. 

Thanks

**Comment by tonesto7** [comment]
I just tested this and I can't duplicate the issue.  I can go back into the action and change the SHM restriction from Armed Away to disarm.
