### ISSUE TITLE
(ACTIONS BUG) 

### ISSUE THREAD

**Issue by mgdis4me82** [tonesto7/echo-speaks#284]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [X ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ X] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):SmartThings echospeak
-  How many devices are detected?: 5
-  iOS or Android?: iOS
-  Mobile App Version(Not required): SmartThings classic
-  App/SmartApp Version: 2.19.0 (1457)
-  Device Handler/Driver Version:
-  Heroku Server Version:

## Expected Behavior
**tell us what should happen**
At a scheduled time the my multi room Echo group Should play Eric church on Spotify. 
## Current Behavior
**What happens instead of the expected behavior?**
Nothing happens, music does not play. If I set it to use a single echo, it works well. It does not work on multiple echos or my “everywhere” multi room music group. The “everywhere” multi room music group is recognized and is an option but the action does not play to the multi room group. 
## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.Time arrives and action does not fire 
2.Does not work with the test action button either 
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
@mgdis4me82  Unfortunately,  music playback is a shit show with Amazon.  I can only send commands.  Amazon decides whether to act on them (Inconsistently)
