### ISSUE TITLE
[Feature Request] -- Go Home or Issue Other Commands

### ISSUE THREAD

**Issue by aridizSTtest** [tonesto7/echo-speaks#287]
I've read a fair amount and search the smartthings forums, here and the documentation, but if this is there... I'm missing it.

**Is your feature request related to a problem? Please describe.**
Is there a way to use Echo Speaks to "Speak" to my alexa device, without speaking?
We use the Echo Devices in the home as Baby Monitors. 
I'd like to be able to have it "Show me the baby's room" every night at 7 pm, 
and "go home" at 9am the next morning.

**Describe the solution you'd like**
Under accessibility on the Echo Show devices, 
there is the "Tap to Alexa" functionality, where you can type in a command, and it will execute as if spoken.  I would recommend a TapToAlexa or TextToAlexa type command that alexa would execute on said device as if spoken to.

**Describe alternatives you've considered**
In rooms with multiple devices, I've tried having one device speak the command to the other, and sometimes it works, but unreliably.
I tried testing the ExecuteCommand command, but it didn't seem to work, or I got the context wrong.

**Additional context**
Just a little more info on Tap To Alexa
![20200428_104030](https://user-images.githubusercontent.com/60025993/80503596-161af880-8940-11ea-84f1-63d7f58a75c7.jpg)
![20200428_104016](https://user-images.githubusercontent.com/60025993/80503601-17e4bc00-8940-11ea-8501-6ce85663dd53.jpg)

**Comment by tonesto7** [comment]
These are not possible.  Those actions are not exposed to the web api.
