### ISSUE TITLE
"Stop" command in webCORE doesn't stop current Echo activity 

### ISSUE THREAD

**Issue by ericb182** [tonesto7/echo-speaks#29]
"Stop" command in webCORE doesn't stop current Echo activity.  E.G., doesn't stop music from playing.

**Comment by tonesto7** [comment]
Since i just realized there is no stop command in the alexa api i've changed the stop command to use pause.
I will be pushing this up shortly

**Comment by tonesto7** [comment]
Fixed in v2.0.4
