### ISSUE TITLE
(BUG) 

### ISSUE THREAD

**Issue by LukeRuppSr** [tonesto7/echo-speaks#292]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform SmartThings 
-  How many devices are detected 13
-   Android
-  Mobile App Version(Not required):
-  App/SmartApp Version: newest
-  Device Handler/Driver Version: newest 
-  Heroku Server Version: newest

## Expected Behavior
Actions automations should should speak via echo and non echo devices.

## Current Behavior
In the last week or so my actions automations to speak have stopped working on non echo devices including fire 8 and fire 10 tablets, 2 ecobee 4 units, and 2 ecobee switches. The odd thing is on the tablets a tone is still announced but no speaking. Also when in the ST app on my phone, when go to the things list and open one of the non speaking devices and select a weather forecast to some other speak action the device speaks the request. 

## Steps to Reproduce (for bugs)
See above

## Context
When I change the desired speak device in the action from a non echo device to an echo device the speak action works.

Thanks
Luke

**Comment by tonesto7** [comment]
This is out of my hands :(
It could be an issue on the Amazon side.  I can only send the command but Amazon has to act on it.  This isn't an official api that's used (there isn't one)
You can test to see if the device is still supported by creating an Alexa routine to make the none echo device speak. If it works in the routine then Echo Speaks should support it.

**Comment by LukeRuppSr** [comment]
Ok thanks. After carefully monitoring the devices I found the ecobee4s work 95 percent of the time. The Fire 8 and Fire 10 tablets exhibit the behavior of a speak tone with no speak of the text. I also found the tablets do work some time but not often .. maybe 20 of the time. I am thinking it may be a network issue with the tablets. I will do some additional testing. Thanks.

**Comment by LukeRuppSr** [comment]
I meant to mention the Amazon Echo devices work all the time.
