### ISSUE TITLE
Login with Amazon UK Account fails

### ISSUE THREAD

**Issue by mayhew132** [tonesto7/echo-speaks#3]
I seem to be getting an error when logging in to the Heroku instance using my Amazon account. After entering the code for 2FA on the Amazon account I get UnknownOperationException:

![image](https://user-images.githubusercontent.com/25966969/47968908-05016c00-e068-11e8-832d-71dd3bbb1832.jpeg)

![image](https://user-images.githubusercontent.com/25966969/47968900-f74be680-e067-11e8-83b8-d0cd56d5d70a.jpeg)

**Comment by mayhew132** [comment]
Edit - this doesn't seem to be 2FA related (I disabled it temporarily), I note it goes to this URL when showing the error:

https://echo-speaks-*******.herokuapp.com/proxy/alexa.null

**Comment by mayhew132** [comment]
After deleting and re-adding the Heroku instance it suddenly worked.

**Comment by tonesto7** [comment]
@mayhew132  thanks for letting me know... I pushed out fixes about an hour ago.  That means they worked.
