### ISSUE TITLE
OOPS... Spotify is NOT Supported by this Device!!!

### ISSUE THREAD

**Issue by Hafogit** [tonesto7/echo-speaks#30]
Spotify works directly on Echo devices. In Webcore now I get the OOPS error … Spotify is NOT Supported by this Device !!!
Everything else works okay.

**Comment by tonesto7** [comment]
@Hafogit Can you PM in the ST community with your heroku server name please

**Comment by tonesto7** [comment]
Fixed in v2.0.4
