### ISSUE TITLE
(BUG) Action Time Condition Not Working

### ISSUE THREAD

**Issue by jsarcone** [tonesto7/echo-speaks#302]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [* ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ *] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [* ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [* ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Hubitat
-  How many devices are detected?: 9
-  iOS or Android?: Both
-  Mobile App Version(Not required):n/a
-  App/SmartApp Version:3.6.2.0
-  Device Handler/Driver Version: 3.6.2.0
-  Heroku Server Version:2.4.1

## Expected Behavior
**tell us what should happen**

## Current Behavior
**What happens instead of the expected behavior?**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.setup action
2.mode change to night
3. Play weather
4.set condition between 10pm - 12:30 am
It will never meet the condition. If you change to 11:58pm it will meet the condition. Of course the time would have to be between them.

## Context
**How has this issue affected you? It doesn't run and it would require me short the time or make two rules.
 What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
Thanks for providing me an example of your action to duplicate on my end. I will look into it right now

**Comment by jsarcone** [comment]
Thank you for all the awesome work that you do. Thanks for looking at it not critical.
