### ISSUE TITLE
Random routine don't work

### ISSUE THREAD

**Issue by Giamma1963** [tonesto7/echo-speaks#303]
-  Hub Platform (SmartThings or Hubitat):     SMARTTHINGS
-  How many devices are detected?:  3
-  iOS or Android?:                                          ANDROID
-  Mobile App Version(Not required):
-  App/SmartApp Version:                               3.6.2.0
-  Device Handler/Driver Version:                   
                                                         String devVersion()  { return "3.6.2.0" }
                                                         String devModified() { return "2020-04-22" }
                                                         Boolean isBeta()     { return false }
                                                         Boolean isST()       { return (getPlatform() == "SmartThings") }
                                                         Boolean isWS()       { return false }
-  Heroku Server Version:                               2.4.1

I use Echo speaks for several months and I often use in my piston the instruction "ExecuteRoutineId" without problems, but for about one month I have problems  ...
The piston work (tun on light - turn off light) but random the instruction "ExecuteRoutineId" don't work .... All this alexa's routine turn on tv and speak one message, the message is different depending on the time (good morning-good lunch- ecc. ecc), yesterday for example in the morning is start the routine of the afternoon but I have not made changes in my piston the it's the same from a long time, other time the routine don't start ....
I have no errors in the ide .....

**Comment by tonesto7** [comment]
I'm not sure how to help you with this. Are you receiving an error in the logs while sending the excuteRoutine command?

**Comment by Giamma1963** [comment]
Up until a week ago the log displayed these errors:
-----------
Echo (v3.6.1.0) | updDeviceActivity Error: Getting properties on class org.apache.http.conn.ConnectTimeoutException is not allowed

java.lang.SecurityException: Invoking methods on class org.apache.http.conn.ConnectTimeoutException is not allowed: getMessage @line 2315 (respExceptionHandler)

java.util.concurrent.TimeoutException: Execution time exceeded 20 app execution seconds: 252719854456639 @line -1 (respExceptionHandler)

Echo (v3.6.2.0) | updDeviceActivity Error: Getting properties on class org.apache.http.conn.ConnectTimeoutException is not allowed 
-----------
but not in relation to the execution of piston, but is a few days that I have not errors for echo speaks ....
