### ISSUE TITLE
Won't login in to Amazon/Alexa account

### ISSUE THREAD

**Issue by jackadferguson** [tonesto7/echo-speaks#305]
The app doesn't seem to accept my log in credentials for my amazon/alexa account. I've followed all the guides on the echo speak website for setting up numerous times with no luck. Once setting up the app on Heroku then asking for my amazon log in, once i return to the echo speaks app it just says I'm no longer logged in to amazon.

I don't have any experience with this stuff so could be doing something stupid.
Thanks
![IMG_2501](https://user-images.githubusercontent.com/65367095/82077331-28828980-96d7-11ea-992f-a34665490135.PNG)

![IMG_2501](https://user-images.githubusercontent.com/65367095/82077295-1a346d80-96d7-11ea-8a7f-2cf9eadc9133.PNG)
![IMG_2500](https://user-images.githubusercontent.com/65367095/82077304-1dc7f480-96d7-11ea-8c59-f7804b4d9212.PNG)

**Comment by tonesto7** [comment]
Are you using a shared account?

**Comment by jackadferguson** [comment]
No its just me on the account.

**Comment by flatttop** [comment]
I’m having similar issue.  After entering my Amazon credentials, a small red text message displays above the email/phone field that says only “A problem occurred.”
I have tried on iPad and iPhone using Classic and after that failed several times the new ST app. (On new app one time of multiple attempts  Amazon showed a message to enable cookies... browser window is built into the app, so couldn’t do that). 
Cookies are enabled in my Safari browser.

**Comment by menefsc** [comment]
Similiar issue here. I got 
"There was a problem
Enter a valid email or mobile number"
I reset my password and tried multiple times...so many that I got a notification of unusual activity.   I allowed the activity and was able to get logged in but had screen saying enable cookies.   The only option was returning to the previous page which now I get "There was a problem" when logging in.

**Comment by ClashingPlaids** [comment]
I'm having this problem as well, multiple times.  I have to delete the app (in the IDE) and start over and then it accepts my Amazon login credentials.  However, like **flattop** said, I then get an Amazon message to enable cookies, and I have no idea how to do that from within the ST app.
