### ISSUE TITLE
[Feature Request] Add config in device to support DnD

### ISSUE THREAD

**Issue by TonyFleisher** [tonesto7/echo-speaks#31]
I would like the ability for dnd mode to silence echo speaks on my device
Use case: when i am on the phone in my office, i don't want hear automated announcements.

**Comment by tonesto7** [comment]
Ok... So DnD On = no speech output

**Comment by tonesto7** [comment]
This should be by default right?

**Comment by tonesto7** [comment]
This was added in v2.0.5 of the device code
