### ISSUE TITLE
(BUG) 

### ISSUE THREAD

**Issue by kyparamedic** [tonesto7/echo-speaks#313]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [X] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [X] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): SmartThings
-  How many devices are detected?: 6
-  iOS or Android?: Android
-  Mobile App Version(Not required):
-  App/SmartApp Version: 3.6.2.0
-  Device Handler/Driver Version: 3.6.2.0
-  Heroku Server Version: 2.4.1

## Expected Behavior
Be able to change the device settings

## Current Behavior
No matter what is selected, it says to fill out all of the required fields, although none are red. Even without changing anything it won't allow me to save the current device settings.
![Screenshot_20200523-124548_SmartThings](https://user-images.githubusercontent.com/23271823/82735963-f20ac700-9cf3-11ea-9e01-ac9f8dba66f0.jpg)

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. See attached screenshot
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
set the max volume to 100
