### ISSUE TITLE
(ACTIONS BUG) time restrictions not honored

### ISSUE THREAD

**Issue by skorn** [tonesto7/echo-speaks#314]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ X ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ X ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ X ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ X ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): SmartThings 
-  How many devices are detected?: 3
-  iOS or Android?: iOS 
-  Mobile App Version(Not required): 3.6.2.0
-  App/SmartApp Version: 3.6.2.0
-  Device Handler/Driver Version: 3.6.2.0
-  Heroku Server Version: 2.4.1

## Expected Behavior
I had 2 rules created to trigger based off a contact sensor opening. They were identical in all but 2 ways.
(1) one was time restricted to only be between 9am-9pm, with the other 9pm-9am. 
(2) the daytime one would set the echo volume to 100 for the announcement, and the evening one would set it to 50 for it. 
I would expect that when the contact sensor was opened I would get 1 announcement, and the volume of that announcement would be at 100 during the day and 50 in the evening. 

## Current Behavior
When the contact sensor is opened I will pretty much always get 2 announcements. Presumably due to race conditions sometimes the volume will be loud first then quiet, or sometimes the same volume both times. There are also occasional instances that I do only get 1 announcement, but I am guessing that, because it is the rare occurrence, it is just one of them getting lost/overriden. 

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Create 2 actions that differ only as described in the expected behavior. 
2. When viewing the actions it does properly show the check/X based on being within the time or not. 
3. Open the sensor, and get multiple/incorrect announcements.

## Context
My intent here is to have the echo make an announcement whenever  the door is opened. When it is opened during daytime hours however I want to ensure that the announcement is made at full volume. 
This is specifically as a notification of exit doors being opened as I have special needs children that have a history of trying to elope. Please understand that I am not 100% reliant on this, as we have several layered protections, but this solution is honestly one of the clearest as I can have customized announcements made at a volume that can be heard throughout the house. 

---
Please include a copy of any relevant log output to assist in tracking down the bug

I will attempt to gather relevant logs and attach here as soon as I am able.

**Comment by skorn** [comment]
So after recreating the rules it may be working. I noticed something though. When it wasn’t working the conditions section had “any” with a check, but then only one condition (the time period) which had an X. So it seems that there was some invisible condition that was met and allowed the “any” to pass. Note that because there was no other conditions the selector for any/all was not visible.

**Comment by skorn** [comment]
Ok I think I have steps to reproduce:
1) create an action and put a time frame condition that is not currently met. 
2) observe X next to both”any” and the time restriction (EXPECTED)
3) add another condition, I used location in mode and selected current or all. 
4) observe check next to “any” and the mode condition. X next to time restriction. (EXPECTED)
5) remove mode condition so only time restriction remains. 
6) observe check next to “any” and X next to the only shown condition. (NOT EXPECTED)

I think it persisted for me as I was cloning rules instead of making fresh. When making fresh and never having more than one condition it seems to work as expected. 

Hopefully detail in this comment helps nail down to some hidden co diction not being fully removed.

**Comment by tonesto7** [comment]
@skorn  I think this was a bug from an older version of actions.  Usually toggling the "any or all" will clean it up

**Comment by skorn** [comment]
Just went through reproducing steps again.
If I have 2 conditions the “all” setting does work. However if there was previously 2 conditions and one is removed it always reverts to “any” even when “all” was selected prior to removing the second condition. 
It is complicated by the fact that when you remove the extra condition to the point that there is only one, the option to switch is removed.

**Comment by tonesto7** [comment]
I added in some cleanups to the all conditions flag if there is only one condition defined
