### ISSUE TITLE
Echo listening right

### ISSUE THREAD

**Issue by Giamma1963** [tonesto7/echo-speaks#316]
Will be possible in the future to have a command to be used in a piston to listen echo like I saying "alexa ...." ?

Example:
I open the door and (by piston) alexa says "give me the code to disable alarm"
Now I must say "alexa, hello word", 
well, I wish that in this case I could tell directly "hello word".

**Comment by tonesto7** [comment]
Sorry there is no way to access any of that info with the current api.
