### ISSUE TITLE
Album Art Not Updating

### ISSUE THREAD

**Issue by jnewbury2280** [tonesto7/echo-speaks#320]
The "audioTrackData" doesn't get updated in my SmartThings.

![2020-05-30_10h30_20](https://user-images.githubusercontent.com/5819158/83330953-ab235100-a260-11ea-8e78-9c9a0aa49f43.png)

I use this for Album art in SharpTools and my Album Art seems to be stuck on this [IMAGE](https://m.media-amazon.com/images/I/715NakGzkuL._UL600_.jpg?fbclid=IwAR38iqLAnynfjQcXT1wa4Hcdj3bTVaLnhGFrCyknvkQDj71_GM7vAoOc0os).

It will never change. I have also tried iHeart Radio still no updates. Is there a way to reset this so it will update on each song change?

**Comment by tonesto7** [comment]
THis should be happening. I've never seen or heard of this not working.
