### ISSUE TITLE
Wake don't stop

### ISSUE THREAD

**Issue by Giamma1963** [tonesto7/echo-speaks#327]
Hub Platform (SmartThings or Hubitat): SMARTTHINGS
    How many devices are detected?: 4
    iOS or Android?: ANDROID
    App/SmartApp Version: 3.6.2.0
    String devVersion() { return "3.6.2.0" }
    Heroku Server Version: 2.4.1

I don't know if this is a bug but ....
When an echo play a song and I say "alexa, stop", echo stop the music ...
When an alarm clock rings and I say "alexa stop", echo stop the alarm ... 
In the piston, rather, the instruction "stop" don't work when an alarm clock rings ....

**Comment by tonesto7** [comment]
This has nothing to do with Echo Speaks.  We have no control over the voice commands... We simply simulate Alexa routine actions to control the devices.
