### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by alanizat** [tonesto7/echo-speaks#331]
Wyze Band has imbedded Alexa instance. It uses text only to respond, but is completely functional otherwise. Ability to have the custom responses and alerts on its output would be fantastic. 

If there is anything I can do to generate any logs you need, please advise. The product is new to Wyze, but based on the beta program, there are a lot of system integrators using the product and evaluating it’s capabilities to enhance IoT use.

Requesting device support from the following device(s):
description: What kind of device/model Wyze Band release 1
family: UNKNOWN
name: AlansWyzeBand
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, appleMusic, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode
type: A1NAFO69AAQ16Bk

**Comment by tonesto7** [comment]
Sorry, but this band will not work... I've added the device to the block list

**Comment by alanizat** [comment]
Test
