### ISSUE TITLE
(BUG) Actions - Logic Issue with Motion and SHM

### ISSUE THREAD

**Issue by miketheman2k** [tonesto7/echo-speaks#332]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):ST
-  How many devices are detected?:
-  iOS or Android?:
-  Mobile App Version(Not required):
-  App/SmartApp Version: 3.6.2.0
-  Device Handler/Driver Version: 3.6.2.0
-  Heroku Server Version: 2.4.1

## Expected Behavior
In Actions, I have created a "motion detected" speak output. In Action Triggers I have 'motion > motion sensor > active'. In Conditions I have 'Alarm conditions > Smart Home Monitor is... Armed Away'. In 'Execution Config' I have an echo device selected.

The result I would expect from this is that active motion, in armed away mode, will result in the echo announcing the speech.

## Current Behavior
What actually happens is the 'armed away' status of SHM is ignored and regardless of mode the speech is activated.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
I haven't had time to troubleshoot this yet, but I will

**Comment by tonesto7** [comment]
I've corrected this issue in the latest release.
