### ISSUE TITLE
[Add Device Support]

### ISSUE THREAD

**Issue by mitchelllu66** [tonesto7/echo-speaks#340]
**Required Info is the following (Found under Echo Speaks app under devices page):

* Family:  ZEPHYR
* Type: A3IYPH06PH1HRA

** Other Info:
**Status: (Online)
**Style: Echo Unknown( Actual is Echo Frames)
* Model and/or Generation of device: GR79BD Echo Frames
Announcements :(False)
Text-to-Speech: (False)

But I need these 2 function to my Echo Frames, But Echo Auto and Echo Budes with above function (true)

**Have you tested the device for announcement/speech support using Alexa Routine?
Yes, Routine Can not send Speech and announcement to Echo Frames either

**Comment by tonesto7** [comment]
Added.  This will be included in this evening release.
