### ISSUE TITLE
(BUG) 

### ISSUE THREAD

**Issue by Bastro0107** [tonesto7/echo-speaks#342]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): smartthungs
-  How many devices are detected?:0
-  iOS or Android?: android
-  Mobile App Version(Not required):
-  App/SmartApp Version:
-  Device Handler/Driver Version:
-  Heroku Server Version:

## Expected Behavior
**tell us what should happen**
Everythjng is up to date. 
Can't sign in to amazon
## Current Behavior
**What happens instead of the expected behavior?**
Says that alexa cookie has been retrieved successfully. 
Then takes me back to the echo speaks app and says I still have to log into amazon 

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
Can't use echo speaks 
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by Jigu106** [comment]
I am facing the same issue. I have tried from Heroku app as well as from smartthings/echo speaks/ login status|service management. 
In both way I get message "alexa cookie has been retrieved successfully.."
but on to the page back it still says 'GOTO LOGIN PAGE".
![Snag_5bee82f](https://user-images.githubusercontent.com/53095107/87861486-ac920100-c914-11ea-93fb-78d3db801415.png)

**Comment by Jigu106** [comment]
With latest server 2.5.2 thes issue not fixed. I am using Amazon.ca. Echo Speaks app (v3.6.3.1) everytime displays.. 
" You are no  longer logged in to Amazon. Please complete the Authentication Process on the server login page." 

Which i have did for multiple times...
![WhatsApp Image 2020-07-19 at 3 40 03 PM (4)](https://user-images.githubusercontent.com/53095107/87883586-79b04180-c9d6-11ea-8330-fb0328549a34.jpeg)
![WhatsApp Image 2020-07-19 at 3 40 03 PM (3)](https://user-images.githubusercontent.com/53095107/87883587-7a48d800-c9d6-11ea-9647-2e6f59f37611.jpeg)
![WhatsApp Image 2020-07-19 at 3 40 03 PM (2)](https://user-images.githubusercontent.com/53095107/87883589-7b7a0500-c9d6-11ea-9916-b66f73db44ea.jpeg)
![WhatsApp Image 2020-07-19 at 3 40 03 PM (1)](https://user-images.githubusercontent.com/53095107/87883591-7c129b80-c9d6-11ea-9559-385f0f6a9bf0.jpeg)
![WhatsApp Image 2020-07-19 at 3 40 03 PM](https://user-images.githubusercontent.com/53095107/87883592-7d43c880-c9d6-11ea-9ff5-7a247f05f467.jpeg)

**Comment by Jmarcos13** [comment]
I'm having the same issue, can't login...

**Comment by Toggz** [comment]
Also unable to login in the UK. Using server 2.5.2, with recent app updates..... Waiting patiently! :)

**Comment by kranix0** [comment]
Same problem and I'm in Australia.

**Comment by Jmarcos13** [comment]
Hey guys. Don't know if everyone here followed the issue reported by tonesto, on the cookie library, but you can do this (ty hafizchin) :

App:
Domain : select your correct domain (mine is amazon.com.br)
Locale: select your correct locale (mine is pt-BR)

Heroku:
when you deploy a new server modify the following config variables / or just update your existing server:
amazonDomain: amazon.com
regionLocale: your correct locale (probably this one is corrected by the default installation on the app)

To change the configs above (in heroku), you must go the settings of your server and reveal configs var. Then you'll see the amazonDomain and RegionLocale for edit. Try to loggin now. 💯

**Comment by Bastro0107** [comment]
Jmarcos13 you are a life saver. Been fiddling with this for ages with no luck.
Tried and it worked straight away. 
Thanks so much for your help

**Comment by Toggz** [comment]
@Jmarcos13, perfect solution! Worked instantly after server config change. Thank you, Thank you!

**Comment by Jigu106** [comment]
Please forgive me if I am on wrong track.
From : Canada.
Steps I followed. 
Delete app (via smartthing app) & Delete Heroku server.
Install echo speaks app again.
on Server deployment selected (amazon.ca & en-CA)

![image](https://user-images.githubusercontent.com/53095107/88406619-ec3a6c00-cd9e-11ea-850d-495ee49f46fe.png)

sign in to amazon followed to process , says cookie retrieved.. but in app message didn't change I can not find any of my devices.

![image](https://user-images.githubusercontent.com/53095107/88406917-53582080-cd9f-11ea-88b2-804b4adc6d16.png)


once deployed check the config var ( matches with what i selected).

![image](https://user-images.githubusercontent.com/53095107/88406719-112edf00-cd9f-11ea-856f-bbf433624392.png)


![image](https://user-images.githubusercontent.com/53095107/88406972-6b2fa480-cd9f-11ea-8e76-ef38431ab508.png)


What is wrong I am doing. 
Please advise.

**Comment by Jmarcos13** [comment]
Hey @Jigu106 !!

In the config var you must switch the amazon.ca to amazon. com
It's not just a check.


![image](https://user-images.githubusercontent.com/68557019/88408468-f9a92380-cda9-11ea-9736-a95e4435db44.png)

**Comment by Jigu106** [comment]
@Jmarcos13  Thanks a lot. that helps a lot.
With that update Heroku able to capture the cookie & App does not complain about Amazon login.

![image](https://user-images.githubusercontent.com/53095107/88414078-48ef5400-cdaa-11ea-8eab-7262aa57275e.png)


But The app still not shows my devices.
Possible issue is I am able to use both Amazon.ca and Amazon.com with my credentials. 
(in .com I do not have any device & possibly the cookie captured by Heroku is from .com & not .ca)

Please advise.

**Comment by Jmarcos13** [comment]
@Jigu106 Ohhhh yeah!! I forgot! That happened to me too, I think it's because you've tried to loggin and failed. 

This is what i did:
I removed everything, started again, but this time i made everything correct, my "first" attempt to logged was a sucess and then my devices showed up. 

Dunno if this is a thing, but you might try again and only loggin after you fix the amazonDomain

**Comment by Jigu106** [comment]
@Jmarcos13  Thanks a lot man. That help..

What I did is ...
Change the amazonDomain while deploying in Heroku from echo speak app itself.
and then hit deploy.
 (Validated on Heroku config & it did not changed there remains as amazon.com) 
login to amazon... 

now my devices shows up... 

Thanks a lot again.
