### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by noddy73** [tonesto7/echo-speaks#343]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: ALEXA_AUTO
name: Peter's BMW Group – Amazon Alexa Car Integration
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, appleMusic, spotify, alarms, doNotDisturb, microphone, followUpMode
type: A3BW5ZVFHRCQPO

**Comment by tonesto7** [comment]
Added... I will roll it out this evening.
