### ISSUE TITLE
(BUG) 

### ISSUE THREAD

**Issue by TaZZaT** [tonesto7/echo-speaks#344]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x]  That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): SmartThings 
-  How many devices are detected?:15
-  iOS or Android?:iOS
-  Mobile App Version(Not required):
-  App/SmartApp Version:v3.6.3.1
-  Device Handler/Driver Version:v3.6.3.1
-  Heroku Server Version:v2.5.2

## Expected Behavior
Should have detected my new Fire Tablet HD 10. (9th generation)

## Current Behavior
Does not detect fire HD 10

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Order new Fire HD from Amazon to replace Fire HD 10 with bad screen. 
2. Receive Device and setup with Amazon credentials
3. Verify device is listed in Alexa app and verify SmartThings integration works
4.  Open Echo Speaks and device is not listed 

## Context
**How has this issue affected you? What are you trying to accomplish? 

This is the main automation panel for my home. I use echo speaks to announce critical events on this device.  The current panel has a bad screen. I cannot discover the replacement device in the echo speaks app
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug
The counts show 1 FIre HD 10. It should show 2, the old one with the defective screen and the New replacement.   
counts": {
        "deviceStyleCnts": {
            "Echo (Gen2)": 2,
            "Echo Auto": 1,
            "Echo Dot (Gen2)": 1,
            "Echo Input": 1,
            "Echo Show (Gen2)": 1,
            "Echo Show 5 (Gen1)": 2,
            "Fire TV Cube": 2,
            "Fire Tablet HD": 1,
            "Fire Tablet HD 10": 1,
            "Fire Tablet HD 8": 2,
            "Multiroom": 1
        },

**Comment by westynet** [comment]
I have the same issue. The HD Fire 10 (9th Generation) doesn't seem to be recognised. I have multiple other HD Fire Tablets that all work perfectly.
