### ISSUE TITLE
(BUG) Unpredictable behaviour with consecutive messages

### ISSUE THREAD

**Issue by kranix0** [tonesto7/echo-speaks#347]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ x ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): SmartThings
-  How many devices are detected?: 1
-  iOS or Android?: Android
-  Mobile App Version(Not required):
-  App/SmartApp Version: 3.6.3.1
-  Device Handler/Driver Version: 3.6.3.1
-  Heroku Server Version: 2.5.2

## Expected Behavior
In WebCore, if I give a sequence of commands for Echo Speaks, it ought to queue them and play them consecutively. Ideally, this also ought to apply for commands of non-fixed length, e.g. _playFunFact._

## Current Behaviour
Behaviour is unpredictable. Sometimes a message will start and be interrupted by the next one. Sometimes it will be skipped and the next one will play.

## Steps to Reproduce (for bugs)
Here is some sample code:
<img width="589" alt="download" src="https://user-images.githubusercontent.com/461278/88451660-c8a91b80-ce9b-11ea-9ef6-277c0b7c6ad4.png">

It works with the manual "Wait" commands that I've inserted. These stop the spoken commands from running into each other. If you remove the Wait commands, the behaviour becomes unpredictable.

## Context
In this example, I'm creating a bedtime routine for my kids. Alexa tells them that it's bedtime, speaks a fun fact, then wishes them good night. It's a fun way for them to end the day.

But the same context should apply to any space where Echo Speaks is running several commands at once.

**Comment by tonesto7** [comment]
The only commands that a queued for successive commands are speech and announcements.  All others will interrupt any other.
