### ISSUE TITLE
(BUG) Unable to login :(

### ISSUE THREAD

**Issue by Stokykyle** [tonesto7/echo-speaks#348]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): SmartThings
-  Heroku Server Version: 2.5.2

## Expected Behavior
Login to amazon alexa UK

## Current Behavior
Unable to login and even using manual cookie entries this does not work and still just results back issuing me to login again.

Seems to work fine if i try to login using amazon.com instead of the amazon.co.uk.

Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by Jmarcos13** [comment]
Hey @Stokykyle.

This week we have a nice post about that, you can check in the #342

**Comment by Stokykyle** [comment]
I managed this and then found that it could not discover any devices.

**Comment by Stokykyle** [comment]
There we go reinstalled the server and set the amazon domain name as I was deploying and this worked correctly.

Thanks

**Comment by Jmarcos13** [comment]
> I managed this and then found that it could not discover any devices.

It happened to me and another user. Have you removed everything and logged in your first attempt? 
My devices showed up only after that.

**Comment by Jmarcos13** [comment]
> There we go reinstalled the server and set the amazon domain name as I was deploying and this worked correctly.
> 
> Thanks

Nice!! Enjoy!
