### ISSUE TITLE
New Smartthings app behaving strangely with Echo Speaks

### ISSUE THREAD

**Issue by fdelima1** [tonesto7/echo-speaks#359]
I've had to migrate to the new Smartthings app - but in doing so Ive noticed that my echo devices appear much differently than in the Classic app. The device doesn't appear to have any features or configurations settings in the new app.

Is there an updated Echo Speaks smartapp to bring back the functionality that the classic app has ??

**Comment by LukeRuppSr** [comment]
Following as it will be an issue for me as well.

**Comment by tonesto7** [comment]
The new app doesn't support custom attributes and commands yet.  
When I can add them I will push out an update

**Comment by fdelima1** [comment]
Ok np.     But the  smart app can stil bemused with the new smartthings app
right ?
