### ISSUE TITLE
error groovy.lang.MissingMethodException

### ISSUE THREAD

**Issue by sblock-23** [tonesto7/echo-speaks#36]
Seeing the following error recorded in live logging consistently. Everything seems to be working though. I'm currently on 2.0.6.

error groovy.lang.MissingMethodException: No signature of method: script_app_731d58812bfeefd93489df17c0e25fe874984be60e45a7729676f104a0dee646.lanEventHandler() is applicable for argument types: (physicalgraph.app.EventWrapper) values: [physicalgraph.app.EventWrapper@4f7e1530]

**Comment by tonesto7** [comment]
This is just because the pending schedule hadn't been cleared.  Once the app discovered it was update the issue should have resolved itself

**Comment by halr9000** [comment]
FYI @tonesto7 I'm seeing this error now. I don't know that it matters, just wanted you to be aware.
