### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by partyka0** [tonesto7/echo-speaks#360]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: THIRD_PARTY_AVS_MEDIA_DISPLAY
name: corey's Samsung TV 2020-U
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode
type: A1QKZ9D0IJY332

**Comment by tonesto7** [comment]
added
