### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by mhmatttu** [tonesto7/echo-speaks#363]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: MMSDK
name: Mike's Portal+
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode
type: A52ARKF0HM2T4

**Comment by tonesto7** [comment]
Added and will be released tonight
