### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by websterbt** [tonesto7/echo-speaks#366]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: UNKNOWN
name: Grady's Room - Alexa Jam
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode, bluetoothControl
type: AKO51L5QAQKL2

**Comment by tonesto7** [comment]
Added and will roll out this evening
