### ISSUE TITLE
Echo speaks duplicates response

### ISSUE THREAD

**Issue by OgreMHDW** [tonesto7/echo-speaks#367]
Hub Platform (SmartThings or Hubitat): Hubitat
How many devices are detected?: 4
App/SmartApp Version: 3.6.3.1
Device Handler/Driver Version: 3.6.3.2
Heroku Server Version: heroku-18 175

## Expected Behavior
Echo should speak the phrase programmed once.

## Current Behavior
Intermittently, echo speaks the phrase, then repeats it again. 

## Steps to Reproduce (for bugs)
Set up a child app of echo speaks with the following parameters:

Triggers:
Switch (1 selected)
Trigger State (any)
Wait (10)

Alexa Devices:
Default Action Response (Optional)
%name% %type% is now %value% %unit%
Dot - Master Bedroom
New Volume (50)
Restore Volume (50)

## Context**How has this issue affected you? What are you trying to accomplish?
Echo says when a device status is changed, notifying users in the room that the device was turned on.

**Providing context helps us come up with a solution that is most useful in the real world**
Be notified in a different room when devices are turned on or off. 

Please include a copy of any relevant log output to assist in tracking down the bug
Log does not show any useful information except "receiveEventData Error: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks WS' in namespace 'tonesto7' not found"

**Comment by tonesto7** [comment]
I have no way to really prevent this.  It shouldn't happen very often. 

In regards to the other error please make sure you installed the Echo Speaks WebSocket driver listed in the documentation.  It significantly increases the reliability of Echo Speaks.
