### ISSUE TITLE
Action triggered by temperature -error- groovy.lang.MissingMethodException: 

### ISSUE THREAD

**Issue by MarkA75160** [tonesto7/echo-speaks#368]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):  HUBITAT
-  How many devices are detected?:  FOUR
-  iOS or Android?:  NEITHER
-  Mobile App Version(Not required):
-  App/SmartApp Version:  
-  Device Handler/Driver Version:  3.6.3.2
-  Heroku Server Version:  UNKNOWN

## Expected Behavior
SPOKEN HIGH TEMPERATURE (>100) ALERT FROM GARAGE SENSORS

## Current Behavior
ERRORS IN LOG EVERY TIME THERE IS A TRIGGER EVENT
groovy.lang.MissingMethodException: No signature of method: java.math.BigDecimal.isNumber() is applicable for argument types: () values: [] Possible solutions: signum() on line 3659 (deviceEvtHandler)

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.  CREATE NEW ECHO SPEAKS ACTION USING TWO TEMPERATURE SENSORS AS A TRIGGER EVENT
2.  ACTION TYPE IS SPEAK WHEN TEMPERATURE IS ABOVE 100 ON ALL (BOTH) SENSORS
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**
JUST A SIMPLE ACTION TO LET ME KNOW WHEN THE GARAGE TEMPERATURE GETS OVER 100 DEGREES FAHRENHEIT 
---
Please include a copy of any relevant log output to assist in tracking down the bug
app:2492020-08-24 08:54:53.232 am errorgroovy.lang.MissingMethodException: No signature of method: java.math.BigDecimal.isNumber() is applicable for argument types: () values: []
Possible solutions: signum() on line 3659 (deviceEvtHandler)
app:2492020-08-24 08:51:50.466 am errorgroovy.lang.MissingMethodException: No signature of method: java.math.BigDecimal.isNumber() is applicable for argument types: () values: []
Possible solutions: signum() on line 3659 (deviceEvtHandler)
app:2492020-08-24 08:49:32.738 am errorgroovy.lang.MissingMethodException: No signature of method: java.math.BigDecimal.isNumber() is applicable for argument types: () values: []
Possible solutions: signum() on line 3659 (deviceEvtHandler)
app:2492020-08-24 08:46:47.976 am errorgroovy.lang.MissingMethodException: No signature of method: java.math.BigDecimal.isNumber() is applicable for argument types: () values: []
Possible solutions: signum() on line 3659 (deviceEvtHandler)
app:2492020-08-24 08:44:29.877 am errorgroovy.lang.MissingMethodException: No signature of method: java.math.BigDecimal.isNumber() is applicable for argument types: () values: []
Possible solutions: signum() on line 3659 (deviceEvtHandler)
app:2492020-08-24 08:41:45.224 am errorgroovy.lang.MissingMethodException: No signature of method: java.math.BigDecimal.isNumber() is applicable for argument types: () values: []
Possible solutions: signum() on line 3659 (deviceEvtHandler)

**Comment by tonesto7** [comment]
Sorry, this has sat so long.  I will get this addressed tonight.

**Comment by tonesto7** [comment]
I'm not able to duplicate this so far.  W

**Comment by tonesto7** [comment]
This issue should be resolved.  Please update all code to the latest version
