### ISSUE TITLE
SirusXM not working in action all other like amazon music, Pandora etc work.

### ISSUE THREAD

**Issue by svsnead** [tonesto7/echo-speaks#372]
I have Echo Speaks installed on a hubitat. I loved how it worked on ST but Samsung is removing it. I really sad as I cannot get SiriusXM to work. It does nothing. But work in the test phase section.

Platform Version : 2.2.3.135
Hubitat : Rev C-5

**Comment by tonesto7** [comment]
I've corrected the issue and the will be rolling out tonight.
