### ISSUE TITLE
Cannot sign into amazon

### ISSUE THREAD

**Issue by tjodork1960** [tonesto7/echo-speaks#373]
I have a smartthings V2 hub.
My daughter changed her amazon password...since then Echo Speak hasnt worked.
I did the community install (very cool) and it said it updated everything for Echo Speak, however it say the device and server had to be updated... by pressing Done, then Save..  I could never find Done but pressed save.... restarted app, went on groovy and published device but the app still says Updates Required for Echo Speaks Device and Echo Speaks Driver

It says I'm no longer logged into Amazon
I've tried it from the app or the web page....it takes me to an amazon alexa web page and my echo's are all on my daughters account so I put her email and password and it says it doesn't recognize the name or phone number... 
I've gone to a completely different browser and signed into amazon alexa with her email and password so I'm at a loss..

I can sign into the heroku server and i have 4 instances of 
![image](https://user-images.githubusercontent.com/47948862/92195497-bc1cc900-ee32-11ea-85df-589b2c87326d.png)

Any help suggestions would be appreciated.....

**Comment by tjodork1960** [comment]
help ? any suggestions ?

**Comment by tonesto7** [comment]
I apologize.  I can't really help with this.. Amazon login works so if it's an issue it's not with Echo Speaks and likely with your amazon account.
