### ISSUE TITLE
[ADD DEVICE SUPPORT] (2) Devices

### ISSUE THREAD

**Issue by robdman1** [tonesto7/echo-speaks#375]
Requesting device support from the following device(s):
description: What kind of device/model?(PLEASE UPDATE THIS)
family: FIRE_TV
name: Kitchen tv
permissions: volumeControl, spotify, alarms, reminders, flashBriefing, microphone
type: AFF5OAL5E3DIU

description: What kind of device/model?(PLEASE UPDATE THIS)
family: TABLET
name: Kitchen Fire 8
permissions: volumeControl, spotify, alarms, reminders, microphone
type: AVU7CPPF2ZRAS

**Comment by tonesto7** [comment]
Will be added in tonights release
