### ISSUE TITLE
[Add Device Support]

### ISSUE THREAD

**Issue by chaseparker** [tonesto7/echo-speaks#378]
**Required Info is the following (Found under Echo Speaks app under devices page):

* Family: TABLET
* Type: AVU7CPPF2ZRAS

** Other Info: 

* Model and/or Generation of device: Fire HD 8 (10th Generation)

**Have you tested the device for announcement/speech support using Alexa Routine? Yes

**Comment by tonesto7** [comment]
This will be added in tonight's release
