### ISSUE TITLE
need to return false in case of non-auth errors

### ISSUE THREAD

**Issue by spickelmier** [tonesto7/echo-speaks#38]

**Comment by spickelmier** [comment]
In this code I think you should return false for any 'hasError' instead of just 401.  Right now I am getting 503 and it is triggering an NPE due to this.

![image](https://user-images.githubusercontent.com/843000/50528937-39ad0500-0aa6-11e9-83b1-0478838d8b6e.png)

`private respIsValid(response, methodName) {
    if (response.hasError()) { 
        if(response?.getStatus() == 401) {
            setAuthState(false)
            return false
        } else { if(response?.getStatus() > 401) { log.error "${methodName} Error: ${response.getErrorMessage()}" } }
    }
    return true
}`

**Comment by tonesto7** [comment]
This issue is resolved as of v2.0.8
