### ISSUE TITLE
(BUG) ES keeps reporting that the ES device needs updated. It's currently on 3640, updated by HPM and confirmed in the driver code. Also seeing quite a lot of 500 errors in the log like this: dev:59832020-09-30 04:10:36.911 am errorEcho (v3.6.4.0) | speechCmd Response Exception | Status: (500) | Msg: Internal Server Error. Everything appears to be working and no issues with HE otherwise.

### ISSUE THREAD

**Issue by kfraleigh** [tonesto7/echo-speaks#381]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Hubitat
-  How many devices are detected?:18 (using 9, ignoring 9)
-  iOS or Android?: iOS
-  Mobile App Version(Not required):
-  App/SmartApp Version: 3640 (ES reporting 3640, but stating update available)
-  Device Handler/Driver Version: 3640 (ES reporting 3632)
-  Heroku Server Version:2.6.0

## Expected Behavior
**tell us what should happen**

## Current Behavior
stated above

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug
{
    "guid": "44bccc83-1885-42c0-9fc0-d320412ed9c7",
    "datetime": "Wed Sep 30 15:14:21 EDT 2020",
    "installDt": "Tue Aug 18 00:10:18 EDT 2020",
    "updatedDt": "Tue Aug 18 00:42:42 EDT 2020",
    "timeZone": "US/Eastern",
    "hubPlatform": "Hubitat",
    "authValid": true,
    "stateUsage": "33%",
    "amazonDomain": "amazon.com",
    "serverPlatform": "Cloud",
    "versions": {
        "app": "3.6.4.0",
        "server": "2.6.0",
        "actions": "3.6.3.2",
        "zones": "N/A",
        "device": "3.6.3.2",
        "socket": "3.3.1.1"
    },
    "detections": {
        "skippedDevices": {
            "AKPGW064GI9HE": {
                "volume": true,
                "image": "firetv_stick_gen1",
                "reason": "Other Devices Not Enabled",
                "tts": true,
                "mediaPlayer": false,
                "name": "Family Room Fire TV",
                "online": true,
                "family": "FIRE_TV",
                "type": "AKPGW064GI9HE",
                "desc": "Fire TV Stick 4K (Gen3)"
            },
            "A1RTAM01W29CUP": {
                "volume": true,
                "image": "alexa_windows",
                "reason": "Other Devices Not Enabled",
                "tts": true,
                "mediaPlayer": true,
                "name": "Laptop",
                "online": false,
                "family": "REAVER",
                "type": "A1RTAM01W29CUP",
                "desc": "Windows App"
            },
            "A3C9PE6TNYLTCH": {
                "volume": true,
                "image": "echo_wha",
                "reason": "WHA Devices Not Enabled",
                "tts": false,
                "mediaPlayer": true,
                "name": "Everywhere",
                "online": true,
                "family": "WHA",
                "type": "A3C9PE6TNYLTCH",
                "desc": "Multiroom"
            },
            "A3S5BH2HU6VAYF": {
                "volume": true,
                "image": "echo_dot_gen2",
                "reason": "In Ignore Device Input",
                "tts": true,
                "mediaPlayer": true,
                "name": "Kenny and Christinas echo",
                "online": true,
                "family": "ECHO",
                "type": "A3S5BH2HU6VAYF",
                "desc": "Echo Dot (Gen2)"
            },
            "A1JJ0KFC4ZPNJ3": {
                "volume": true,
                "image": "echo_input",
                "reason": "In Ignore Device Input",
                "tts": true,
                "mediaPlayer": true,
                "name": "Minivan",
                "online": false,
                "family": "ECHO",
                "type": "A1JJ0KFC4ZPNJ3",
                "desc": "Echo Input"
            },
            "A2LWARUGJLBYEW": {
                "volume": true,
                "image": "firetv_stick_gen1",
                "reason": "Other Devices Not Enabled",
                "tts": true,
                "mediaPlayer": false,
                "name": "Office Fire TV",
                "online": true,
                "family": "FIRE_TV",
                "type": "A2LWARUGJLBYEW",
                "desc": "Fire TV Stick (Gen2)"
            },
            "A32DOYMUN6DTXA": {
                "volume": true,
                "image": "echo_dot_gen3",
                "reason": "In Ignore Device Input",
                "tts": true,
                "mediaPlayer": true,
                "name": "Living Room",
                "online": true,
                "family": "ECHO",
                "type": "A32DOYMUN6DTXA",
                "desc": "Echo Dot (Gen3)"
            }
        }
    },
    "actions": {
        "0": {
            "version": "3.6.3.2",
            "type": "dnd",
            "delay": 0,
            "triggers": [
                "scheduled"
            ],
            "echoZones": [
                
            ],
            "echoDevices": [
                "5991",
                "5994"
            ],
            "usingCustomText": 0,
            "triggerDeviceCnt": 0
        },
        "1": {
            "version": "3.6.3.2",
            "type": "dnd",
            "delay": 0,
            "triggers": [
                "scheduled"
            ],
            "echoZones": [
                
            ],
            "echoDevices": [
                "5991",
                "5994"
            ],
            "usingCustomText": 0,
            "triggerDeviceCnt": 0
        },
        "2": {
            "version": "3.6.3.2",
            "type": "speak",
            "delay": 0,
            "triggers": [
                "contact"
            ],
            "echoZones": [
                
            ],
            "echoDevices": [
                "5983"
            ],
            "usingCustomText": 1,
            "triggerDeviceCnt": 5
        },
        "3": {
            "version": "3.6.3.2",
            "type": "speak",
            "delay": 0,
            "triggers": [
                "presence"
            ],
            "echoZones": [
                
            ],
            "echoDevices": [
                "5983"
            ],
            "usingCustomText": 1,
            "triggerDeviceCnt": 5
        },
        "4": {
            "version": "3.6.3.2",
            "type": "speak",
            "delay": 0,
            "triggers": [
                "switch"
            ],
            "echoZones": [
                
            ],
            "echoDevices": [
                "5983",
                "5986"
            ],
            "usingCustomText": 1,
            "triggerDeviceCnt": 1
        }
    },
    "zones": {
        
    },
    "counts": {
        "deviceStyleCnts": {
            "Echo (Gen2)": 1,
            "Echo Dot (Gen3)": 2,
            "Echo Dot (Gen2)": 6
        },
        "appHeartbeatCnt": 0,
        "getCookieCnt": 28,
        "appErrorCnt": 0,
        "deviceErrors": {
            
        },
        "deviceUsage": {
            
        }
    }
}
![image](https://user-images.githubusercontent.com/34952811/94729670-0610a600-0330-11eb-9bcc-3bcf300f2b29.png)

**Comment by tonesto7** [comment]
This is not an uncommon error when the Alexa API is having issues.  
Amazon has also done a lot of work on rate-limiting requests so you may see other errors as well.

**Comment by tonesto7** [comment]
Duplicate issue follow #385
