### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by dnorris78** [tonesto7/echo-speaks#382]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, siriusXm, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode
name: David's Talk to Alexa
description: What kind of device/model?(PLEASE UPDATE THIS)
family: UNKNOWN
type: A1ETW4IXK2PYBP

**Comment by tonesto7** [comment]
Will be included in tonights release
