### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by andyjkr** [tonesto7/echo-speaks#383]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, doNotDisturb, microphone, followUpMode
name: Andy's Pioneer Car AV–Prod
description: What kind of device/model?(PLEASE UPDATE THIS) Pioneer DMH-W4660NEX
family: UNKNOWN
type: A1SCI5MODUBAT1

**Comment by tonesto7** [comment]
This will be added in tonights release.
