### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by davidgeo** [tonesto7/echo-speaks#385]
I recently updated my Echo Speak to v.3.6.4.0 (both app and device). I verified the saved coding is the new version. Now when I open the app I get the following message. " If you just updated the code please press Done/Save to let the app process the changes." I can't figure out what I'm doing wrong. I scrolled to the bottom of the main app page and clicked on done but nothing changes.

Thanks

**Comment by peteypauls** [comment]
I think I have the same issue. I updated everything as well, clicked done but on top  it still says “updates required for 

Echo Speaks Device
Echo Speaks Server

**Comment by tonesto7** [comment]
I'm not sure how to help with this... The main app reads the version number from the other files

**Comment by rfoust** [comment]
Same issue here, upgraded like I usually do but can't get that message to go away. Also seems that my integration with alexa is broken after the last update, can't seem to fix it. Still trying to track down the problem.

**Comment by tonesto7** [comment]
How are you updating the code?

Are you using hubitat packager manager?
Manual copy/paste?
Using import under hubitat?

**Comment by rfoust** [comment]
I used hubitat package manager.  I also went back and did a manual import for the app/device code just in case something went wrong there but it didn't seem to make a difference.

**Comment by rfoust** [comment]
Map minVersions()     { return [echoDevice: 3641,

Is that why? Looks like the latest device code is 3.6.3.2?

**Comment by rfoust** [comment]
Just updated to 3.6.4.2, seems to have resolved my problems.  Not sure if this was the correct steps, but after I upgraded (using hubitat package manager), I had to go to Login Status and click Next, and then the version error message finally went away.

**Comment by peteypauls** [comment]
Just saw this and tried.  Still seeing this in Smartthings.  
![9AEE623A-3ADC-49B0-AA7B-51258E70ACB1](https://user-images.githubusercontent.com/24756796/95881201-57646080-0d46-11eb-823b-15f1cea5a0f4.jpeg)

**Comment by peteypauls** [comment]
And I’m using update repo from GitHub.

**Comment by tonesto7** [comment]
@peteypauls You will need to update your server to the latest version.  
https://tonesto7.github.io/echo-speaks-docs/updates/server_update/

**Comment by peteypauls** [comment]
Got it.  Not sure why it didn't autoupdate, but i manually deleted and set up again.  Thanks for the help.
