### ISSUE TITLE
still getting update notifications with notifications turned off

### ISSUE THREAD

**Issue by leepyswetr** [tonesto7/echo-speaks#39]
I'm on v2.0.5, but since I wanted to test a fix, I haven't updated. It appears to me that this bug is still in 2.0.7, but I'm not a programmer.

I turned off update notifications, but when there is a new version of the app available I get push notifications every 2 hours. The settings page indicates that the default is 12 hours, but there's a hard-coded 2 hour default.

In appUpdateNotify() it logs whether or not notifications are enabled, but doesn't seem to actually check it before sending a notification.

I changed line 1143 (line 1190 in 2.0.7) to the following and it seems to work as expected:
 if(**on &&** getLastUpdMsgSec() > state?.updNotifyWaitVal.toInteger()) {

**Comment by tonesto7** [comment]
i completely missed this issue.  I will look into more and push out a fix
