### ISSUE TITLE
Tone when setting volume level before and after action

### ISSUE THREAD

**Issue by hal-sys** [tonesto7/echo-speaks#391]
Echo Speaks Documentation | Community Thread | Donate
Echo Speaks v3.6.4.3 (app)
Echo Speaks - Actions v3.6.4.1 (app)
Echo Speaks - Zones v3.6.4.1 (app)
Echo Speaks Device v3.6.4.1 (driver)
Echo Speaks WS v3.3.1.1 (driver)

Hi I was creating an action an I noticed that if I set the volumes, I get a tone before an after the action. Is there a way to turn this off?

**Comment by tonesto7** [comment]
Unfortunately there is no way to disable this.  It's part of the echo firmware
