### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices - Echo Dot 4th Gen

### ISSUE THREAD

**Issue by Rumtum** [tonesto7/echo-speaks#396]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, isMultiroomMember, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Sitting Room Echo Dot 4g
description: What kind of device/model? It's an Echo Dot 4th generation
family: ECHO
type: A2U21SRK4QGSE1

**Comment by jstevensaz** [comment]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, isMultiroomMember, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Kitchen Dot4
description: What kind of device/model? (Echo Dot (4th Gen))
family: ECHO
type: A2U21SRK4QGSE1
