### ISSUE TITLE
Can’t Add SmartApp in new Samsung app(BUG) 

### ISSUE THREAD

**Issue by dcfurst** [tonesto7/echo-speaks#400]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ X] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ X] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [X ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): ST
-  How many devices are detected?: 18
-  iOS or Android?: iOS 
-  Mobile App Version(Not required): 1.6.52
-  App/SmartApp Version: 3.6.4.4
-  Device Handler/Driver Version: 3.6.4.1
-  Heroku Server Version:

## Expected Behavior
**tell us what should happen**

SmartApp should install

## Current Behavior
**What happens instead of the expected behavior?**

Error message during install “Something went wrong. Please try to install the SmartApp again”

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Try installing it
2.
3.
4.
![D9A9FDBC-1118-4E30-8CF9-6D374C334945](https://user-images.githubusercontent.com/24395446/98580354-d4bfba00-228d-11eb-8e57-30800d3fb52c.jpeg)

![2C8183D2-EB74-45A5-B03B-90EAC4C6EE88](https://user-images.githubusercontent.com/24395446/98580469-02a4fe80-228e-11eb-85b6-3ca3d10c14e0.jpeg)

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by gitST2020** [comment]
I am seeing exactly the same thing.
Some things I've tried:

- Started by deleting all Echo speaks related DH, Smart apps
- Removed Alexa linked service
- Logged out of Smartthings App
- Logged out of Alexa
- Installed through Github repository - cannot install the SmartApp
- Installed manually
- Installed through Community Installer (each time I removed all associated remnants)
- Tried on 3 different iOS devices

Interestingly, I have been able to add other SmartApps through the Community Installer without any issues.
Then I saw this under the Smartthings Notices page on the app - also here: https://community.smartthings.com/t/updates-to-the-smartthings-platform/200513


_The Echo Speaks SmartApp will no longer be supported and existing installs will no longer be accessible.Echo Speaks uses a cloud-based Groovy implementation that is resource heavy. | September 8, 2020 | Visit this page 227 for instructions on how to transition to the new SmartThings Alexa integration.This upgrade, in collaboration with Amazon, provides support for more devices and the ability to control multiple locations. For additional Echo Speaks feature parity requests, complete this form 124.
-- | -- | --_
