### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by jefftrnka** [tonesto7/echo-speaks#401]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, siriusXm, spotify, isMultiroomMember, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
description: Echo Dot Gen 4, https://smile.amazon.com/gp/product/B07XJ8C8F5/
family: ECHO
type: A2U21SRK4QGSE1

**Comment by jefftrnka** [comment]
I added this to the :
"A2U21SRK4QGSE1": [ caps: [ "a", "t" ], image: "echo_dot_gen3", name: "Echo Dot (Gen4)" ]
I haven't figured out how to define an image, so it's good enough for me  for now, but it did enable the use of the new Echo.

**Comment by tonesto7** [comment]
support will be added in this weeks release
