### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by JRKuyper** [tonesto7/echo-speaks#406]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [Yes, but not sure] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [Yes] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [Yes] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [Yes] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):  SmartThings
-  How many devices are detected?:  ?
-  iOS or Android?:  Android
-  Mobile App Version(Not required):
-  App/SmartApp Version:  Downloaded Today (26 Nov 2020)
-  Device Handler/Driver Version:  Downloaded Today (26 Nov 2020)
-  Heroku Server Version:  Downloaded Today (26 Nov 2020)

## Expected Behavior
When Tapping on "Echo Speaks" for the first time, should be in the main screen of the Echo Speaks SmartApp.

## Current Behavior
When Tapping on "Echo Speaks" for the first time, message:
"We're having trouble connecting.  Check your network connection and try again."  (New App)
"Something's Wrong.  We can't load your screen right now."  (Classic App)
SmartThings and other apps are able to connect to the internet.

## Steps to Reproduce (for bugs)
Follow instructions on https://tonesto7.github.io/echo-speaks-docs/installation/smartthings/installs/.  
Continue to https://tonesto7.github.io/echo-speaks-docs/configuration/smartthings/config_app/.
[Instructions refer to Classic App.  I used the New App the first time, Classic App the second time.  Got errors both times.]
New App:
1.  Tapped Menu > SmartApps
2.  Tapped "+"
3.  Tapped "Echo Speaks"
Received Error:  "We're having trouble connecting.  Check your network connection and try again." [OK]

Classic App (retired):
1.  Tapped "Automation" >  "Add a SmartApp"  >"My Apps" > "Echo Speaks"
Received Error:  "Something's Wrong.  We can't load your screen right now."  [Retry]

## Context
I can't install Echo Speaks.

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by hageson** [comment]
I can't install Echo Speaks either, although the message I get is "Something went wrong.  Please try to install the SmartApp again.".  Clicking OK closes the dialog box and returns me to the list of SmartApps I can add.
![IMG_0498](https://user-images.githubusercontent.com/22227364/101422302-32eeb580-38ab-11eb-9b8f-84f0ea6b74ae.PNG)
![IMG_0499](https://user-images.githubusercontent.com/22227364/101422309-371ad300-38ab-11eb-8867-ea1b1aaa0c2b.PNG)

**Comment by SRCOOMBER** [comment]
I have this exact same issue:

![image](https://user-images.githubusercontent.com/16171975/104108526-39e56980-532a-11eb-8812-58fc77b57e32.png)

Any update on this?

**Comment by pottisatish** [comment]
Have the same issue here. I already have the code installed in my IDE. When i try to add the smartapp using the + -> smartapp in the new Smarthings app and choose EchoSpeaks , I get the same error "we are having trouble connecting. Check your network connection and try again.

Is this something because samsung is blocking it? I remember receiving a note from smartthings that they are not allowing echospeaks to be installed due to groovy implementation taking up huge resources etc etc...

**Comment by mortz74** [comment]
+1 Am having the same issue.

**Comment by anirs** [comment]
I have the same issue here

**Comment by tonesto7** [comment]
ES no longer supports SmartThings
