### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices - Echo Dot 4th Gen

### ISSUE THREAD

**Issue by jwprovencher** [tonesto7/echo-speaks#411]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, appleMusic, spotify, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Lounge
description: What kind of device/model? Echo Dot 4th Gen
family: ECHO
type: A2U21SRK4QGSE1

**Comment by tonesto7** [comment]
Support coming in this weeks release
