### ISSUE TITLE
[ADD DEVICE SUPPORT] (2) Devices

### ISSUE THREAD

**Issue by Toy4Rick** [tonesto7/echo-speaks#416]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, isMultiroomMember, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Kitchen Echo
description: What kind of device/model?(PLEASE UPDATE THIS)
family: ECHO
type: A3RMGO6LYLH7YN

permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, isMultiroomMember, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Master Bedroom Echo
description: What kind of device/model?(PLEASE UPDATE THIS)
family: ECHO
type: A3RMGO6LYLH7YN

**Comment by tonesto7** [comment]
Support coming in this weeks release
