### ISSUE TITLE
Echos are recognized, Dots not working at all

### ISSUE THREAD

**Issue by brownson39622** [tonesto7/echo-speaks#42]
I've read through the entire 1600+ Echo Speaks ST Community blog plus your ES Documentation and not finding anything quite like my experience.  Perhaps you've seen this and can suggest something.  I loaded Echo Speaks both through code and Github and both exhibit the same issue (removed code and only GitHub now).  In ST Classic all 3 Echos are showing in the device list.  My 2 gen 2 Dots are unresponsive to any of the button commands on the page.  They show as online with TTS supported and everything looks good.  My Echo 2nd gen DOES respond to button commands in the ST devices list including TTS.  However NONE of the Echos will respond with speech to ANY of the smartapps, not even with the test broadcast in your Echo Speaks app.  I use BigTalker2, for my voice notifications and wanted to get ES working before adding more Apps such as RemindR.  I also have a Samsung Multiroom and it works fine with the BigTalker notifications.  

I deleted and reloaded Heroku and confirmed my Amazon cookies to no avail.  As far as I can tell everything looks fine, just doesn't work.  And I get no error messages.  Which logs or screen shots would be most helpful to to troubleshoot the issue?  I hope you can help as it would be awesome to have this working.    Mike B

**Comment by brownson39622** [comment]
Thanks for replying.  Here’s the log for one of the Dots that does not respond when I press Send test TTS.

 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:11:04 PM: trace getDoNotDisturb: [enabled:false, deviceType:A3S5BH2HU6VAYF, deviceSerialNumber:G090LF11749303PJ] 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:11:03 PM: trace getAvailableWakeWords: [ALEXA, AMAZON, ECHO, COMPUTER] 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:11:03 PM: trace getWakeWord: ALEXA 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:11:03 PM: trace getAlarmVolume: [volumeLevel:70, deviceType:A3S5BH2HU6VAYF, softwareVersion:628538320, deviceSerialNumber:G090LF11749303PJ] 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:11:03 PM: trace getPlaylists: [playlists:[sleep:[[title:sleep, playlistId:1dabaee3-8b70-40ee-bd1b-d73351c82bfe, entryList:null, version:9, trackCount:71]]]] 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:11:03 PM: trace getPlaybackState: [template:null, mediaId:null, progress:null, infoText:null, playingInLemurId:null, queueId:null, state:null, provider:null, hint:null, lyrics:null, miniArt:null, transport:null, lemurVolume:null, miniInfoText:null, upNextItems:null, volume:null, mainArt:null, playbackSource:null, isPlayingInLemur:false] 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:11:03 PM: trace permissions: [TTS:true, alarms:true, amazonMusic:true, appleMusic:false, connectedHome:true, doNotDisturb:true, flashBriefing:true, iHeartRadio:true, isMultiroomDevice:false, isMultiroomMember:false, mediaPlayer:true, microphone:true, pandoraRadio:true, reminders:true, siriusXm:false, spotify:true, tuneInRadio:true, volumeControl:true, wakeWord:true] 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:11:03 PM: trace refreshData()... 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:10:56 PM: trace resetQueue() 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:10:56 PM: error postCmdProcess Error | status: 400 | message: null 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:10:56 PM: debug ┌─────── Echo Command ──────── 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:10:56 PM: debug │ Command: (SpeakCommand) 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:10:56 PM: debug │ Current Volume: (null%) 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:10:56 PM: debug │ Message(84 char): Being able to make me say whatever you want is the coolest thing since sliced bread! 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:10:56 PM: debug │ Rechecking: (6 seconds) 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:10:56 PM: debug │ Queue Items: (0) │ Working: (false) 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:10:56 PM: debug │ SentToQueue: (true) 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:10:56 PM: debug │ First Command: (true) 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:10:56 PM: debug │ Last TTS Sent: (1000 seconds) 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:10:56 PM: debug └───────────────────────────── 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:10:56 PM: debug 

d16171d1-b4f8-4ff6-a42f-a7446edf3763 <https://graph-na04-useast2.api.smartthings.com/ide/logs#d16171d1-b4f8-4ff6-a42f-a7446edf3763>  2:10:56 PM: trace speak() command received... 

 

 

Restoring Historic Denver

Mike Brownson

mike@phantomcreekllc.com

**Comment by brownson39622** [comment]
The Kitchen Echo does respond to TTS within your ES app, but when I just sent a Talk Now request from BigTalker2 to the Kitchen Echo I get this error.  

 

ea3da532-c748-497c-9dfa-35db4bda8ca1 <https://graph-na04-useast2.api.smartthings.com/ide/logs#ea3da532-c748-497c-9dfa-35db4bda8ca1>  2:29:51 PM: warn Uh-Oh... The playTrackAndRestore(uri: https://s3.amazonaws.com/smartapp-media/polly-tts/justin/testing_again_and_again.mp3, duration: 6, volume: null) Command is NOT Supported by this Device!!! 

 

I get the exact same error on the Dots when I sent a Talk Now request from BigTalker.

 

And for just a little more info here’s the log on the Kitchen Echo when I press Send Test TTS.  It does announce the TTS, however my BigTalker events don’t announce over this device.  

ea3da532-c748-497c-9dfa-35db4bda8ca1 <https://graph-na04-useast2.api.smartthings.com/ide/logs#ea3da532-c748-497c-9dfa-35db4bda8ca1>  2:41:23 PM: trace checkQueue | Nothing in the Queue... Performing Queue Reset 

ea3da532-c748-497c-9dfa-35db4bda8ca1 <https://graph-na04-useast2.api.smartthings.com/ide/logs#ea3da532-c748-497c-9dfa-35db4bda8ca1>  2:41:18 PM: info SpeakCommand Sent Successfully | Execution Time (466ms) | Recheck Wait: (1 sec) | CmdID: (257) 

 

 

 

 

 

 

Restoring Historic Denver

Mike Brownson

mike@phantomcreekllc.com

**Comment by TonyFleisher** [comment]
What version of echo speaks do you have installed?
What is the device showing for volume level? If it is 0 or empty/not set, Can you try setting the volume on the device to 50 and then test TTS again?

**Comment by TonyFleisher** [comment]
The big talker issue is that it is setup as music player rather than speech synthesizer. Unfortunately, big talker only supports one or the other (chosen at install), and echo speaks doesn't support music player (SMH can't use it for the same reason).

**Comment by tonesto7** [comment]
Closing this issue...
