### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by digomax123** [tonesto7/echo-speaks#427]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Kitchen  Echo
description: What kind of device/model?(PLEASE UPDATE THIS)
family: ECHO 4th gen
type: A3RMGO6LYLH7YN

**Comment by tonesto7** [comment]
support will be added in the upcoming release this week
