### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by hardverk** [tonesto7/echo-speaks#428]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, isMultiroomMember, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Main
description: What kind of device/model?(PLEASE UPDATE THIS)
family: ECHO dot 4th Gen
type: A2U21SRK4QGSE1

**Comment by tonesto7** [comment]
support will be added in the upcoming release this week
