### ISSUE TITLE
Smart app hang during installation 

### ISSUE THREAD

**Issue by rwa5908** [tonesto7/echo-speaks#43]
I got as far as installing the app in the SmartThings app and it just sat and spun, never got to the Echo Speaks screen. Finally restarted the ST app. Echo Speaks appears to be installed but nothing happens when I click on it. Tried removing smart app from IDE but it says it’s installed by one or more users.

**Comment by tonesto7** [comment]
@rwa5908 I'm unable to duplicate this issue.
I will need to see some more logs to identify your problem.

**Comment by tonesto7** [comment]
This is not possible on latest app versions... closing issue
