### ISSUE TITLE
[ADD DEVICE SUPPORT] (2) Devices

### ISSUE THREAD

**Issue by terryseiple** [tonesto7/echo-speaks#437]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode
name: K-Brilliant
description: What kind of device/model?(Briliant Screen) 

https://www.brilliant.tech/products/brilliant-control-single-switch-smart-lighting-smart-home-control?variant=white

family: UNKNOWN
type: A2E5N6DMWCW8MZ

permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Terry's Echo Dot
description: What kind of device/model?(Newest Echo Dot 4th Gen Version)
family: ECHO
type: A2U21SRK4QGSE1

**Comment by tonesto7** [comment]
support will be added in the upcoming release this week
