### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by xarquath** [tonesto7/echo-speaks#439]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, appleMusic, spotify, isMultiroomMember, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Teresa's Echo Dot
description: What kind of device/model?(Echo Dot 4)
family: ECHO
type: A2U21SRK4QGSE1

**Comment by tonesto7** [comment]
support will be added in the upcoming release this week
