### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by mrnewsy** [tonesto7/echo-speaks#440]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Desk Echo
description: What kind of device/model? Echo Dot (4th Gen) - 2020 release
family: ECHO
type: A2U21SRK4QGSE1

**Comment by tonesto7** [comment]
support will be added in the upcoming release this week
