### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by IanKirkUK** [tonesto7/echo-speaks#442]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Study
description: What kind of device/model?(PLEASE UPDATE THIS)
family: ECHO
type: A2U21SRK4QGSE1

**Comment by tonesto7** [comment]
support will be added in the upcoming release this week
