### ISSUE TITLE
[ADD DEVICE SUPPORT] (2) Devices

### ISSUE THREAD

**Issue by roshan-dias** [tonesto7/echo-speaks#446]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, appleMusic, spotify, isMultiroomMember, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Bedroom 3 Echo
description: What kind of device/model?(PLEASE UPDATE THIS)
family: ECHO
type: A2H4LV5GIZ1JFT

permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, appleMusic, spotify, isMultiroomMember, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Bedroom 4 Echo
description: What kind of device/model?(PLEASE UPDATE THIS)
family: ECHO
type: A2H4LV5GIZ1JFT

**Comment by tonesto7** [comment]
support coming in next release
