### ISSUE TITLE
Kindle Fire Devices Show Offline

### ISSUE THREAD

**Issue by thommerlin** [tonesto7/echo-speaks#46]
Using Kindle Fire tablets with Fully/Actiontiles and wanting to have beeps/announcements to be played from them. I have multiple echo devices (Dots, Show, and Echo v1) setup and working properly. The Kindle Fire devices show "Offline" however.

This is what I have done to troubleshoot:

1. Made sure I was updated to the Echo Speaks 2.1.1 version
2. Uninstalled SmartApp and Reinstalled, while also making sure to remove all devices from all other apps/automations.
3. Power-cycled devices

See screenshots attached for what I am seeing in SmartApp.
![img_3492](https://user-images.githubusercontent.com/11578713/50791668-5fd95e80-1277-11e9-8bad-3603e1e5ff71.PNG)
![img_3493](https://user-images.githubusercontent.com/11578713/50791669-5fd95e80-1277-11e9-8b4b-afd8f332413d.PNG)
![img_3494](https://user-images.githubusercontent.com/11578713/50791670-6071f500-1277-11e9-9550-f5b25c808a30.PNG)
![img_3495](https://user-images.githubusercontent.com/11578713/50791777-ab8c0800-1277-11e9-9bdf-229e8630c571.PNG)

**Comment by thommerlin** [comment]
Shows offline in Alexa app. I have done some digging and it looks like the Alexa Show integration has killed the ability for the device state to show Online unless the "Show Mode" is configured. When that is turned on the ability for ActionTiles on the tablet is disabled since it shows the Show Mode screen only.

To get the functionality I am looking for I have resorted to LanNouncer and then using that to integrate to BigTalker for announcements. That is how I have setup the devices and hey are working properly.

I will update the ST forum with what I am doing. I know many won't come here to the github to search issues for some reason.

**Comment by TonyFleisher** [comment]
Have you verified the fire tablet is actually online? The Fire tablets have a feature that is on by default (Smart Suspend in Settings -> Power) which will shut off the wifi radio to save power when not in use.
Also verify that the latest version of the alexa app and OS is installed on the fire tablet.

**Comment by tonesto7** [comment]
I'm unable to duplicate the issue.  When devices show online in Alexa Mobile app they are shown online in ES
