### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by tinker3433** [tonesto7/echo-speaks#463]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: jefferson's Echo Dot
description: What kind of device/model?(Echo Dot 4th gen)
family: ECHO
type: A2U21SRK4QGSE1

**Comment by tonesto7** [comment]
Support has been added in v4 beta.
