### ISSUE TITLE
error amazonCommandResp error: Failed with status code 401

### ISSUE THREAD

**Issue by richard55uk** [tonesto7/echo-speaks#49]
Echo speaks has been working for me but now I'm getting the Amazon login cookie has expired message. I have been into Echo speaks heroku config page and then  Amazon login and I get the message cookie retrieval successful and Authentication  Good but it is still not working. I have cleared login info and this also gives me Authentication  Good. I am in the UK using Amazon.co.uk with two factor Authentication.

**Comment by tonesto7** [comment]
are you running the latest app/device and server code?

**Comment by richard55uk** [comment]
I am running echo speaks 2.1.2

**Comment by tonesto7** [comment]
what about the heroku server?  The latest public version is 2.1.1

**Comment by richard55uk** [comment]
Sorry not too sure how to check the server version

**Comment by tonesto7** [comment]
This is related to the authentication with amazon.  Meaning you likely need to login again through the we heroku server

**Comment by richard55uk** [comment]
I have redeployed the server and that appears to have fixed the problem.
