### ISSUE TITLE
Data Refresh Issue in ST App

### ISSUE THREAD

**Issue by ilovesmart** [tonesto7/echo-speaks#5]
![echo1](https://user-images.githubusercontent.com/33988570/48493561-f105f900-e823-11e8-8a8a-3edc24ee5091.jpg)

I installed from scratch twice and get he same error.
I can see the devices in ST and the status of them looks fine but these errors appear on the android app on my phone every 4-5 minutes.

**Comment by tonesto7** [comment]
I just pushed up v1.2.4 about an hour ago.  Let me know if it resolves this issue.

**Comment by rickydg** [comment]
I’m still having this issue in 1.2.5

**Comment by Frappawotsit** [comment]
I'm also having the problem where the Auth times out.... I'm using v1.2.5 also. I have 2FA activated, I can do the auth and I get the cookie successful screen, and after a few hours, it just stops working and I have to re-auth again.

**Comment by holdestmade** [comment]
I'm getting this again as well. Tried the auth from pc as well as mobile. Also tried a refresh() every minute in webcore.

**Comment by tonesto7** [comment]
This issue shouldn't exist in v2.0 that's releasing end of the week

**Comment by andyrob2215** [comment]
I'm having this issue with v2.0.1

**Comment by tonesto7** [comment]
If you are seeing this then the getEchoDevices() call is not completing and there is likely an error in the logs
