### ISSUE TITLE
Volume control only working for multiples of 10 on Sonos Beam

### ISSUE THREAD

**Issue by ikad76** [tonesto7/echo-speaks#51]
When I use search Tunein with a volume parameter on my Sonos Beam it only changes the volume if I pick multiples of 10, any other number does not change the volume. It would be nice to be able to set 8 or 12.
I also have an Echo Show, this one accepts any kind of volume setting and changes it at least in the expected ball park (setting 8 comes out as 7 on the device, setting 25 comes out as 27 on the device).

## Verify the following before opening an trouble issue:

-   [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-   [x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-   [x ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-   [x ] That ALL App/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

## About Your Setup:

-   Hub Platform (SmartThings or Hubitat): Smartthings
-   How many devices are detected?:8
-   iOS or Android?:iOS
-   Mobile App Version(Not required):
-   App/SmartApp Version: 2.1.2
-   Device Handler/Driver Version:2.1.2
-   Heroku Server Version:2.1.1

**Comment by tonesto7** [comment]
ST level only accepts values between 0-100.
It's impossible to tell if you sending 10 means 100% or 10%

**Comment by ikad76** [comment]
Sorry if I was unclear. All values mean %. So 10% is working and 20% but not 8% or 25%.

**Comment by tonesto7** [comment]
Ahh...  yea i for sure can't control how amazon processes the volume.  I guess i never thought of it as a problem before.

**Comment by TonyFleisher** [comment]
What does the Alexa app have for volume on this device in the music playing area?

**Comment by ikad76** [comment]
Actually, what I said above is not quite correct. The Sonos Beam sets up as 2 devices in Echo speaks - the Alexa part and the Sonos part. So I have to use the Alexa part to start the music which then plays on the Sonos part. And it's the volume control of the Sonos part that is working well. So for my webcore routines I use 2 commands now, the first with the Alexa part to start the music and the second with the Sonos part to set the volume to the level I want to.
I still don't understand why the Alexa part will only accept 10% or 20% to pass on for the initial music start.

**Comment by tonesto7** [comment]
So does it show as 2 devices in the Alexa Mobile app?

**Comment by ikad76** [comment]
Yes, it does. When you look at the Echo devices you see "Bedroom" first, along with a few other Alexa devices, when you tab on the Bedroom the Sonos Beam shows. Not sure if this is normal or if this is because the Beam is part of a Sonos group consisting of the Beam itself and two Sonos Play 1 as rear speakers. I've attached pictures taken from the Alexa app.
![img_0308](https://user-images.githubusercontent.com/19996191/51514692-1a896500-1e11-11e9-9e86-e3559b4d21ac.PNG)
![img_0309](https://user-images.githubusercontent.com/19996191/51514693-1a896500-1e11-11e9-95e1-a29541945990.PNG)
