### ISSUE TITLE
When announcements are made it is played 10 times before it forces itself to stop.  

### ISSUE THREAD

**Issue by ludeatude** [tonesto7/echo-speaks#53]
## For Feature Requests Only:

-   What are you requesting:

## Verify the following before opening an trouble issue:

-   [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-   [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-   [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-   [x] That ALL App/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

## About Your Setup:

-   Hub Platform (SmartThings or Hubitat)
-   How many devices are detected?:
-   iOS or Android?:
-   Mobile App Version(Not required):
-   App/SmartApp Version:
-   Device Handler/Driver Version:
-   Heroku Server Version:

## Steps to Reproduce (for bugs)

1. 2. 3. 4.

## Context

Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
This is related to an issue with the SmartThings server you are running on.  I will take steps to try to reduce this from occurring again.

**Comment by ludeatude** [comment]
Thanks. Never had this happen before.
