### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by jdmar3** [tonesto7/echo-speaks#533]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, siriusXm, spotify, isMultiroomMember, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Living Room
description: Echo Dot (Gen 4)
family: ECHO
type: A2U21SRK4QGSE1

**Comment by tonesto7** [comment]
added to the v4 beta
