### ISSUE TITLE
Alexa Devices: No Devices Available

### ISSUE THREAD

**Issue by wxmike** [tonesto7/echo-speaks#57]
under Alexa Devices.. It says No devices Available..  Tap to configure.. and the drop down men u is blank.

-   [ ] That _OAuth_ is Enabled for the SmartApp under the IDE.  **YES**
-   [ ] The App/SmartApp and Device Handler/Driver are using the latest code available. 
-   [ ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.  YES
-   [ ] That ALL App/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

## About Your Setup:

-  Hubitat)  YES
-   How many devices are detected?: 40
-   App/SmartApp Version:2.20
-   Device Handler/Driver Version:
-   Heroku Server Version:2.20

<img width="627" alt="2019-01-20_23-43-36" src="https://user-images.githubusercontent.com/29287760/51453496-b6ca4380-1d0d-11e9-89b0-05c5d9979abd.png">
<img width="672" alt="2019-01-20_23-44-03" src="https://user-images.githubusercontent.com/29287760/51453497-b6ca4380-1d0d-11e9-8560-ec2d5436deeb.png">

**Comment by tonesto7** [comment]
Device driver was not installed.
