### ISSUE TITLE
(ACTIONS BUG) Action Setup Time cannot be defined

### ISSUE THREAD

**Issue by jsarcone** [tonesto7/echo-speaks#575]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Hubitat 2.2.5 123
-  How many devices are detected?: 13 detected, Using 9
-  iOS or Android?: Both
-  Mobile App Version(Not required):
-  App/SmartApp Version: 4.0.2.0
-  Device Handler/Driver Version: 4.0.2.0
-  Heroku Server Version:2.7.0

## Expected Behavior 
**tell us what should happen**
When setting up actions I cannot set start and End times. It doesn't give me a choice (the ability) add time to the action.

## Current Behavior
**What happens instead of the expected behavior?**
Should allow me to enter a time for start and Stop. 

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Create action
2. Select Type (weather Report for example)
3. Enter trigger Mode Change 
4. Time Schedule
5. Starting at.. (time of day). (should allow me to enter time) (doesn't work)
6. stopping at.. (time of day). (should allow me to enter time) (doesn't work)

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
This has been addressed in the v4 beta
