### ISSUE TITLE
Feature Request: Start a Scene via Alexa

### ISSUE THREAD

**Issue by ikad76** [tonesto7/echo-speaks#58]
This might not be the core intention of the app but would it be possible to start an Alexa scene via command e.g. startscene(<scene name>)? I understand that there are ways to set this up via virtual sensors in ST and an Alexa routine which starts the scene but its messy. If you have a lot of scenes you end up with a lot of virtual devices and routines which are hard to keep track of. Starting a scene via one command from a webcore piston would make things very neat.
By scene I mean e.g. a Phillips Hue scene like "Relax in Livingroom". I also have a few Smart home devices which don't integrate (well) with ST but integrate with Alexa via scenes which I would like to used in webcore pistons.

**Comment by tonesto7** [comment]
There is already a command like this but I have no easy way for users to get the ID they are required to pass to the executeRoutineId() command.

It's high up on my roadmap though!

**Comment by tonesto7** [comment]
You can locate the routine ID from here https://alexa.amazon.com/api/behaviors/automations
Just pass the id in the executeRoutineId() from any alexa device.

**Comment by tonesto7** [comment]
This item is now possible using the new Actions companion app in v3 beta

**Comment by razorface1978** [comment]
I would like to request a new feature in the smartthings multi sensors they have accelerometers I want to make my washer talk but it not supported could you add that please

**Comment by mgdis4me82** [comment]
Has there been a way discovered yet to fire a alexa routine from webcore? I see the executeRoutineid(..) in webcore but when i put the name of my alexa routine in the string field, it does not work. What am i doing wrong, please help
