### ISSUE TITLE
(BUG) 

### ISSUE THREAD

**Issue by raygamero** [tonesto7/echo-speaks#586]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ X] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [X] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
Hubitat.
With many echo devices. 15 or so.
On a windows maching on chrome.
Version 3.6.4.4
actions 3.6.4.2
zones 3.6.4.1
server 2.6.0

## Expected Behavior
when making a new action to execute routines. 
Execution configuration.
I select the echo device and then "select alexa routine"  
However,  there are no routines to select.  It only has "Click to set"  listed and I cannot finish the step because "Required Fields missing or not passing validation. Please check red underlined fields and complete the required fields (ones with *)"

Then trying to modify one of my many actions, it also has the same problem, no routines to choose.  However, it seems that my existing actions still work.
 
The only thing that changed today was I got the 30 day donation dialogue. ( I donated)  Ironically, that's when everything stopped working.

ray

**Comment by jhurdt** [comment]
Same issues for me as well. No routines are selectable and it only shows "Click to set" within the drop down.
