### ISSUE TITLE
Error on callback using uk account

### ISSUE THREAD

**Issue by barabba9174** [tonesto7/echo-speaks#6]
Using a UK account, on the Amazon Uk callback after the login thee is a 404 error:
Cannot GET /ap/cvf/request

**Comment by barabba9174** [comment]
Route:

- https://echo-speaks-******.herokuapp.com/ 
- http://echo-speaks-******.herokuapp.com/proxy/www.amazon.co.uk/ap/signin?showRmrMe=1&openid.return_to=https://alexa.amazon.co.uk/&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.assoc_handle=amzn_dp_project_dee_uk&openid.mode=checkid_setup&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.ns=http://specs.openid.net/auth/2.0&
- http://echo-speaks-******.herokuapp.com/ap/cvf/request?arb=****************************

**Comment by barabba9174** [comment]
Update: today I don't have a 404 but instead of the callback to Heroku after the Amazon login, it opens directly the echo dashboard

**Comment by tonesto7** [comment]
Can you give it a try again?  I've made adjustments to address the changes Amazon made recently

**Comment by barabba9174** [comment]
On the laptop I have an Amazon 404 (as callback after logged on Amazon)
`https://echo-speaks-***.herokuapp.com/proxy/www.amazon.co.uk/ap/signin`

On the iPhone, at this url:
`http://echo-speaks-***herokuapp.com/proxywww.amazon.co.uk/ap/cvf/request?arb=*************`

Cannot GET /proxywww.amazon.co.uk/ap/cvf/request

(maybe a slash is missed between proxy and www)

**Comment by barabba9174** [comment]
Thank you for everything Tonesto7, I'm using your Nest Manager for years and I love it!

**Comment by barabba9174** [comment]
Now it's fine! thank you!
