### ISSUE TITLE
Artwork

### ISSUE THREAD

**Issue by GRClark** [tonesto7/echo-speaks#61]
Artwork needs to updated for Dash Wand and Fire TV (I’m using gen 3 pendant and it shows Echo gen 1)

**Comment by tonesto7** [comment]
I know the dash wand image is there.  
I have an update coming that is much more transparent to devices and there detections.

If you aren't seeing the right image for the firetv  than it's not a detected version and I will need to add it to the list but lets wait till i release the next version

**Comment by GRClark** [comment]
It’s odd because both devices show correct artwork in list of devices in SmartApp but not in things area. ![Image](https://i.imgur.com/TL04GSf.jpg)

**Comment by tonesto7** [comment]
Hmm... I'll look into it more
