### ISSUE TITLE
[ADD DEVICE SUPPORT] (3) Devices

### ISSUE THREAD

**Issue by flashingcursor** [tonesto7/echo-speaks#619]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, alarms, reminders, doNotDisturb, flashBriefing, microphone, bluetoothControl
name: Gil's 2nd TV
description: Toshiba 55" 4k FireTV - Model: TOSHIBA_55LF621U21 (Best Buy sub-branded)
family: FIRE_TV
type: AN630UQPG2CA4

permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Gil's Echo Dot
description: Echo Dot 4'th Gen
family: ECHO
type: A2U21SRK4QGSE1

permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, alarms, reminders, doNotDisturb, flashBriefing, microphone, bluetoothControl
name: Gil's 3rd TV
description: Toshiba 43" 4k FireTV - TOSHIBA_43LF621U21
family: FIRE_TV
type: AN630UQPG2CA4

**Comment by tonesto7** [comment]
This has been added to the v4 beta
