### ISSUE TITLE
[ADD DEVICE SUPPORT] (2) Devices

### ISSUE THREAD

**Issue by budjik-tech** [tonesto7/echo-speaks#624]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, isMultiroomMember, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Bedroom Echo Dot
description: What kind of device/model?(PLEASE UPDATE THIS)
family: ECHO
type: A2U21SRK4QGSE1

permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, isMultiroomMember, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Living Room Echo Dot
description: What kind of device/model?(PLEASE UPDATE THIS)
family: ECHO
type: A2U21SRK4QGSE1

**Comment by budjik-tech** [comment]
The Issue was created in the Hubitat app and I probably should have added more detail.

These are both Amazon Echo Dot 4th Gen devices.
Speech Test: The are available to select as devices but do not speak.
Announcement Test: They are not available to select.
Sequence Creator Test: They can be selected and can play the following sequence:
`volume::40,, speak::Testing 1 2 3!,, wait::15,, weather,, cannedtts_random::goodbye,, traffic,, amazonmusic::chuck berry,, volume::30`

The fact that the speech works in the sequence would imply the Speech test should essentially work.
Thank you

**Comment by tonesto7** [comment]
Thanks this has been added to the V4 public beta
