### ISSUE TITLE
searchMusic not working on Sonos (BUG) 

### ISSUE THREAD

**Issue by ikad76** [tonesto7/echo-speaks#64]
-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  SmartThings
-  How many devices are detected?: 20
-  iOS or Android?: iOS
-  Mobile App Version(Not required):
-  App/SmartApp Version: 2.3.2
-  Device Handler/Driver Version: 2.3.2
-  Heroku Server Version: 2.2.1

## Expected Behavior
When I send a searchTuneIn () or searchAmazonMusic() command to my Sonos Play 1 (detected as Echo device) it is supposed to play music. The commands I used to test work fine on my Echos.

## Current Behavior
It is not playing any music. The volume setting shown in the logs is the setting I used in the command, though.

Here is what happens in the ST Live logging for the device:

db07fb21-b527-4344-83dd-f2a30279942f  9:31:44 AM: debug Not parsing XML message:
&lt;e:propertyset xmlns:e=&quot;urn:schemas-upnp-org:event-1-0&quot;&gt;
&lt;e:property&gt;
&lt;LastChange&gt;
&amp;lt;Event xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/RCS/&amp;quot;&amp;gt;&amp;lt;InstanceID val=&amp;quot;0&amp;quot;&amp;gt;&amp;lt;Volume channel=&amp;quot;Master&amp;quot; val=&amp;quot;10&amp;quot;/&amp;gt;&amp;lt;Volume channel=&amp;quot;LF&amp;quot; val=&amp;quot;100&amp;quot;/&amp;gt;&amp;lt;Volume channel=&amp;quot;RF&amp;quot; val=&amp;quot;100&amp;quot;/&amp;gt;&amp;lt;Mute channel=&amp;quot;Master&amp;quot; val=&amp;quot;0&amp;quot;/&amp;gt;&amp;lt;Mute channel=&amp;quot;LF&amp;quot; val=&amp;quot;0&amp;quot;/&amp;gt;&amp;lt;Mute channel=&amp;quot;RF&amp;quot; val=&amp;quot;0&amp;quot;/&amp;gt;&amp;lt;/InstanceID&amp;gt;&amp;lt;/Event&amp;gt;
&lt;/LastChange&gt;
&lt;/e:property&gt;
&lt;/e:propertyset&gt;
db07fb21-b527-4344-83dd-f2a30279942f  9:31:44 AM: trace Has mute: '0', value: 'unmuted
db07fb21-b527-4344-83dd-f2a30279942f  9:31:44 AM: trace Has volume: '10'
db07fb21-b527-4344-83dd-f2a30279942f  9:31:44 AM: trace uuid; RINCON_949F3E1E767401400

**Comment by tonesto7** [comment]
Did this work before?  I'm not sure we can send music directly to Sonos

**Comment by ikad76** [comment]
Hasn't worked for me before. But I think it was mentioned in the forum that it should work.
