### ISSUE TITLE
(BUG) AmazonLogin is showing as invalid... was previously working.

### ISSUE THREAD

**Issue by xios01** [tonesto7/echo-speaks#640]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): **Hubitat**
-  How many devices are detected?: 13
-  iOS or Android?: **ios**
-  Mobile App Version(Not required):
-  App/SmartApp Version: v3.6.4.4
-  Device Handler/Driver Version: v3.6.4.1
-  Heroku Server Version: v2.6.0

## Expected Behavior
**tell us what should happen**
Amazon should be logged in... and should indicate that I am logged in when I successfully log in... 

## Current Behavior
**What happens instead of the expected behavior?**
* NOTE: I've echo speaks working flawlessly, but noticed recently it had stopped working.
* app is showing the message "You are no longer logged in to Amazon.  Please complete the Authentication Process on the Server Login Page!"
* in the "Alexa Login Service" section, it states "Login Status: (Invalid), Tap to modify... when I click on this it says "You still need to Login to Amazon to complete the setup"
* However, when I click on the "Amazon Login Page" it shows a "Amazon Login Authentication Good!" message..  I clear login info and re-login successfully, and echo speaks still shows the login as invalid.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. click on "Echo Speaks App", Message in red at top stating that I am no longer logged into amazon.
2. click on "Alexa login Service" (shows Amazon Login Status as Invalid"
3. click on Manage Login Service (currently indicates "Heroku: (configured), Domain: (amazon.com)... message in red at top states "You still need to Login to Amazon to complete the setup".
4. click on Amazon Login Page: pop up windows states "Amazon Login Authentication Good!"...
5. you can "Clear Login info and successfully re-login, however, will not change current status..

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

 In general, echo speaks is not working at all... I've had it working for some time now... but can't figure how why it suddenly stopped... 

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by budjik-tech** [comment]
I'm not saying you have the same issue, however Amazon made me change my password a few days ago which resulted in the same issue.  However re-login to the server with the new password resolved it for me.

**Comment by xios01** [comment]
unfortunately, I have not changed my password recently... and i’ve re logged in multiple times its like its not saving the login info... though the server app does show that the authentication is good for a short time.... but quickly returns to not logged in shortly after that...

**Comment by xios01** [comment]
My issue has since been resolved by resetting, deleting redeploying the Heroku server app... though still not sure why it just stopped accepting valid authentication... regardless, since redeploying, it accepted the authentication and now is working OK.
