### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by lmvaladao** [tonesto7/echo-speaks#673]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, isMultiroomMember, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Echo de Luciano
description: What kind of device/model?(PLEASE UPDATE THIS)
family: ECHO
type: A3RMGO6LYLH7YN

**Comment by tonesto7** [comment]
this is added in the beta

**Comment by lmvaladao** [comment]
Thanks so much
