### ISSUE TITLE
[Feature Request] Speak or Trigger on specific Unlock User for a lock

### ISSUE THREAD

**Issue by ahciii** [tonesto7/echo-speaks#674]
Hi, I like what you have done, but I'm getting stuck on this.

I have a message setup in rule machine to speak "Welcome home, <User>" and such when someone unlocks the door. However, I like the control you have over speaking (add sounds and such). So I setup the same rule in the Echo Speaks App, but cannot find how to tell which User opened the door.

Am I missing something in the Echo Speaks App, or is there a way to call Echo Speaks from the Rules Machine? I googled around, but can't find anything.

I'd love to be able just to have a variable like <USER> in the response manager that I could use in my response. Or even triggered on Changes to "Unlocked" / "User" like the rule machine does.

What I'm currently doing is I have a separate rule in Rule Machine with a trigger like "Lock code entered on Front Door: Alfred" since it allow me to select a user that is unlocking, and I put the responses for myself. Then I do this for each user, so I have multiple rules right now.

Cheers and Thanks,
Alfred

**Comment by tonesto7** [comment]
our v4 beta supports this... I highly recommend you give it a try
https://community.hubitat.com/t/beta-echo-speaks-v4/66503

**Comment by ahciii** [comment]
Excellent, Thanks for the info. And getting back to me super fast.

I finished up installing the beta, but when I tried to set up what I was doing here, I get a java error. I documented it on the beta thread in the Hubitat Community, since I assume that's probably the best place for this.
