### ISSUE TITLE
(BUG) generated app names all "unavailable"

### ISSUE THREAD

**Issue by bemace** [tonesto7/echo-speaks#680]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): hubitat
-  How many devices are detected?: n/a
-  iOS or Android?: ios
-  Mobile App Version(Not required):
-  App/SmartApp Version: 3.6.4.4
-  Device Handler/Driver Version: 3.6.4.1
-  Heroku Server Version: 2.6.0

I've tried about 10 times to deploy the server to heroku, but each time heroku says the autogenerated app name is unavailable. between attempts i reset the server data in hubitat to generate a new name. the deploy works if i put in a different name, but i don't see any way to tell hubitat about the alternate name.

**Comment by tonesto7** [comment]
If you were actually following the documentation you would be able to move past this by adding a space and deleting it
