### ISSUE TITLE
Mute isn’t working on groups

### ISSUE THREAD

**Issue by GRClark** [tonesto7/echo-speaks#69]
The mute command does not work when trying to mute multi room audio groups. Additionally it’s unclear how the volume is supposed to work - whether the volume controls the entire group at the same volume or…?

**Comment by tonesto7** [comment]
I don't think mute works if there are any devices in the group that don't support volume control.

**Comment by tonesto7** [comment]
I'm pretty certain this isn't supported by Amazon which
