### ISSUE TITLE
Errors During new install V1.2.4

### ISSUE THREAD

**Issue by alljetnopilot** [tonesto7/echo-speaks#7]
During new install, I'm getting an "unexpected error" while attempting step 8 on the wiki:
![image](https://user-images.githubusercontent.com/19246345/48680891-e7e29800-eb53-11e8-999c-d6a8e703e801.png)

The live logging produces the following message.
![image](https://user-images.githubusercontent.com/19246345/48680877-c97c9c80-eb53-11e8-976c-01d7963a9b2d.png)

**Comment by alljetnopilot** [comment]
App version is 1.2.4
Account is a samsung account in the old smarthings app on android

**Comment by tonesto7** [comment]
Thanks for reporting this.  I pushed out v1.2.5 to fix this...
