### ISSUE TITLE
Installation failure on OAuth enable step

### ISSUE THREAD

**Issue by dduisenb** [tonesto7/echo-speaks#70]
When I click the "Update" button after enabling OAuth I get the following error:  "Access to graph-na04-useast2.api.smartthings.com was denied"
![image](https://user-images.githubusercontent.com/40639088/52896457-30264c00-317d-11e9-90a9-6e5220f835b7.png)

**Comment by tonesto7** [comment]
This is an issue with the SmartThings IDE and Google Chrome.   Try to enable the OAuth on a different browser
