### ISSUE TITLE
Amazon.com.au + English AU Feature request

### ISSUE THREAD

**Issue by joelegg** [tonesto7/echo-speaks#72]
**Is your feature request related to a problem? Please describe.**
I can't select Amazon.com.au as the domain or english AU when setting up echo speaks

**Describe the solution you'd like**
Amazon.com.au account holders (english au) should work with echo speaks. 

**Describe alternatives you've considered**
Change my account back to amazon.com which causes a bunch of other problems for echo locale functionality 

thank you

**Comment by joelegg** [comment]
any idea when you may have time to look at this @tonesto7 ? Smartthings integration works again for english AU Alexa skill so i'm getting by for now .

**Comment by tonesto7** [comment]
This was pushed out in the last release
