### ISSUE TITLE
Playing and Stopped Conditions

### ISSUE THREAD

**Issue by rontalley** [tonesto7/echo-speaks#73]
Could "Playing" and "Stopped" be added as conditions? I know you do this by using "Status" and type in "playing" or "stopped" however, it would be more intuitive to be able to directly select these conditions.

My use cases are:
If Echo is Playing 
Then Using Harmony Activity
Turn On

If Echo is Stopped
Then Using Plug
Turn Off

If Echo Stays Stopped for 10 Minutes
Then Using Echo
Disconnect from Bluetooth

If Echo Changes to Playing
Then Using Echo
Connect to Bluetooth

**Comment by tonesto7** [comment]
@rontalley So are you asking for an attribute for each state?

This doesn't seem like a good idea because of the status attribute you mentioned.  We are already crashing WebCore because of the long list of attributes
