### ISSUE TITLE
The Amazon login info has expired

### ISSUE THREAD

**Issue by aero77** [tonesto7/echo-speaks#74]
I have this cookie issue, telling me every hour that I need to refresh my cookie. I'm using the latest version of this as of the date of this post. 2.4.0.

> Echo Speaks Amazon Login Issue:
> The Amazon login info has expired!
> Please open the heroku amazon authentication page and
> login again to restore normal operation.

In the Smartthings Connect app under the Echo Speaks settings it says

> Notice: You are not currently logged in to Amazon. Please complete the Authentication Process on the Server Login Page

**Comment by tonesto7** [comment]
Is this still an issue?  This sounds like the server is not >= v2.2
