### ISSUE TITLE
Now DEPLOY button available

### ISSUE THREAD

**Issue by taxicabconfessor** [tonesto7/echo-speaks#75]
I've been walking through your installation guide and am stuck. When I copy the echo-speaks-xxxxxxxxx, back space, name available (works), there is no deploy button. Instead, I have three deployment options: Heroku GIT, GitHub and Container Registry. I'm not sure where I went wrong.

**Comment by flyballz330** [comment]
I am having the same issue as well.  It worked fine as per the instructions back in January, but I just got around to installing the 2.4.0 upgrade and I cannot deploy the Heroku app.

**Comment by tdillon77** [comment]
Same issue here.....install was going well up to this point but now I'm stuck.

**Comment by flyballz330** [comment]
For me, I finally figured out that the issue was caused by running Safari in Private Mode on my iPhone.  As soon as I turned off Private Mode i was able to see the Deploy button.

**Comment by tdillon77** [comment]
Ty flyballz - that worked!
