### ISSUE TITLE
Nothing happens (HELP)

### ISSUE THREAD

**Issue by KronosMarauder** [tonesto7/echo-speaks#76]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Smarthings
-  How many devices are detected?: 6
-  iOS or Android?: Android
-  App/SmartApp Version:2.4.0
-  Device Handler/Driver Version:2.4.0
-  Heroku Server Version:2.2.1

## Expected Behavior
Some type of audible sound

## Current Behavior
Setup went fine, however nothing happening when complete (no sound). No errors have presented themselves.

## Steps to Reproduce (for bugs)
Installed the app from the start twice (first time user of echo-speaks, but avid & experienced on git and tonesto skils otherwise). All steps were followed to the "T", and no errors along the way. When I got to the 'Device Broadcast Page' and select a device to test, nothing happens. 
I tried different devices, combination of a few... nothing still. I tried different volumes, etc. 
When I press 'Perform the Broadcast?' toggle, it briefly turns on then off, but no sound and no errors whatsoever. 

Is this a router/firewall issue maybe?.

PS: I use a SONOS speaker currently and it works fine with annunciation skills.

**Comment by KronosMarauder** [comment]
To confirm, the echo devices show as 'Things' and I can send commands that activate the device, so I know they are connected. I just cant get any announcer (BigTalker2, etc), to work.

**Comment by dhooksabq** [comment]
Following because I have the exact same issue. I have verified all of the same settings and install that Kronos has. I also uninstalled and reinstalled twice. I go to test and button toggles on, then toggles off and nothing happens. No error code or sound from any device. HELP!?!

**Comment by dhooksabq** [comment]
Update--I unpublished Echosistant smartapp and echo speaks began to work. Could they have been competing in some way? I dont know, but my problem is apparently fixed. Thanks.

**Comment by KronosMarauder** [comment]
> Update--I unpublished Echosistant smartapp and echo speaks began to work. Could they have been competing in some way? I dont know, but my problem is apparently fixed. Thanks.

Too bad for me, as I don't even have "Echosistant" smartapp. I don't see another that would be competing either. Maybe Alexa helper?

**Comment by rabaker358** [comment]
I have the same problem.   Everything installed perfectly.  No errors.  It appears to test but nothing on any echo devices.    I uninstalled LANouncer.    Still nothing.

**Comment by rabaker358** [comment]
dhooksabq:  Very interesting.  I did the same and YES, the devices are there and somewhat work.
My 2 Echo Dots work from the app.    My 1st Gen Full size Echo does nothing from the app.  It says it does and the log says it is, but nothing activates.   I may try reinstalling everything.

**Comment by KronosMarauder** [comment]
> **Update** The test feature in the smart app setup worked two times total. (That was when I posted that it was working.) Unfortunately, it stopped working immediately after I posted that. Today, the test in the app still does not work, BUT the functionality of the app DOES work. I went into smartthings, found the Echo devices then clicked on one. It comes up with a screen that shows several voice commands that can be given. When I touch one of those, the device speaks that command every time. I also set up an automation using Webcore with the speak text function and it works flawlessly. SO, all that to be said, if you have not already, try the app by creating an automation or got to the smartthings device and try the functions. You may find that they work even though the test does not just like I did. I still have no clue why the test function doesn't work. Hope that helps!

Yes, I was able to add the devices, they are active and live in Smartthings, and the commands work (like Announcement Test), however none of the "speaking/dictating smart apps" seems to dictate/relay voice when I select echo devices (although my sonos works fine when selected in these scenarios). I've tried LanNouncer, Big Talker and Speaker Companion.

**Comment by almulder** [comment]
I have 4 Echos (Echo Dot (Gen 2), Echo (Gen1), and 2 Echo Spots
I have the same issue. I can run the Broadcast test and everything speak (even in parallel) But announcement test does nothing, even tested each on their own.

I have "Create Multiroom Devices" set to on, but under Devices Installed they all have Text-to-speach = True" but Everywhere  has that as False. How can I change that so I can use it in webcore?

**Comment by bdenner51** [comment]
All,

New to the forum.  I'm a refugee from iris and new Hubitat user.  Here is my issue: 

I have imported the latest app and driver code. Enabled oauth in the inport app. I have created the Heroku virtual server and, I think, correctly imported the cookies. I see the "no signature of method" in the error statement below, but I thought I enabled oauth when I imported the apps code. I've tried to Google "MissingMethodException: No signature of method" but this is way over my head and I get pretty lost pretty quick.

In summary, the App is loaded, Settings are all visible. My Echo Show is detected and available. All looks good. Then, when I attempt the "broadcast test" and slide the blue switch to the left, it slides itself back. Not a peep out of the Echo Show. The error log reads;

" 2019-04-25 23:42:38.467
[error (http://192.168.1.225/installedapp/configure/114)groovy.lang.MissingMethodException: No signature of method: user_app_tonesto7_Echo_Speaks_67.setAuthState() is applicable for argument types: (java.lang.Boolean) values: [false] on line 1096 (amazonCommandResp)"

Hubitat Device Error Log: 
dev:1972019-04-26 18:53:53.098 warndoSequenceCmd Error | You are missing one of the following... SerialNumber: null**

Currently at a standstill.

Thanks.

Bruce

**Comment by tonesto7** [comment]
@bdenner51 this is happening because the authentication is not receiving a cookie when you perform the amazon login under the heroku server

**Comment by tonesto7** [comment]
> > **Update** The test feature in the smart app setup worked two times total. (That was when I posted that it was working.) Unfortunately, it stopped working immediately after I posted that. Today, the test in the app still does not work, BUT the functionality of the app DOES work. I went into smartthings, found the Echo devices then clicked on one. It comes up with a screen that shows several voice commands that can be given. When I touch one of those, the device speaks that command every time. I also set up an automation using Webcore with the speak text function and it works flawlessly. SO, all that to be said, if you have not already, try the app by creating an automation or got to the smartthings device and try the functions. You may find that they work even though the test does not just like I did. I still have no clue why the test function doesn't work. Hope that helps!
> 
> Yes, I was able to add the devices, they are active and live in Smartthings, and the commands work (like Announcement Test), however none of the "speaking/dictating smart apps" seems to dictate/relay voice when I select echo devices (although my sonos works fine when selected in these scenarios). I've tried LanNouncer, Big Talker and Speaker Companion.

The issue is that the native apps and automations don't actually support sending the speech to the device as text and instead try to send it as an MP3 which Amazon will not allow us to play.
I can't speak for LANouncers methods but I do know that BigTalker need to be installed and configured to in Speech Synthesis mode when it's first installed.

**Comment by KronosMarauder** [comment]
> > > **Update** The test feature in the smart app setup worked two times total. (That was when I posted that it was working.) Unfortunately, it stopped working immediately after I posted that. Today, the test in the app still does not work, BUT the functionality of the app DOES work. I went into smartthings, found the Echo devices then clicked on one. It comes up with a screen that shows several voice commands that can be given. When I touch one of those, the device speaks that command every time. I also set up an automation using Webcore with the speak text function and it works flawlessly. SO, all that to be said, if you have not already, try the app by creating an automation or got to the smartthings device and try the functions. You may find that they work even though the test does not just like I did. I still have no clue why the test function doesn't work. Hope that helps!
> > 
> > 
> > Yes, I was able to add the devices, they are active and live in Smartthings, and the commands work (like Announcement Test), however none of the "speaking/dictating smart apps" seems to dictate/relay voice when I select echo devices (although my sonos works fine when selected in these scenarios). I've tried LanNouncer, Big Talker and Speaker Companion.
> 
> The issue is that the native apps and automations don't actually support sending the speech to the device as text and instead try to send it as an MP3 which Amazon will not allow us to play.
> I can't speak for LANouncers methods but I do know that BigTalker need to be installed and configured to in Speech Synthesis mode when it's first installed.

Thanks for the reply, this is good to know. I figured the main reason to use 'echo-speaks' was to use the echo devices as speakers for automation's (which is my case). Can you detail more how to setup BigTalker to get it to dictate the commands? I'd like to use echo devices (which I have in every room), as opposed to my single sonos device. Thanks.

**Comment by KronosMarauder** [comment]
Never mind my last post. As indicated when I removed BigTalker, and when I re-added I saw the option to configure it to use dictation. That worked like a charm, however I would not recommend using any dictation commands on multiple speakers, as they are not in sync (its not like they all say the same thing at the same time like they do when playing multi room music), so I had 5 speakers speaking at different times, which was horrible. Anyhow, it works. Thank you.

**Comment by KronosMarauder** [comment]
Never mind my last post. As indicated when I removed BigTalker, and when I re-added I saw the option to configure it to use dictation. That worked like a charm, however I would not recommend using any dictation commands on multiple speakers, as they are not in sync (its not like they all say the same thing at the same time like they do when playing multi room music), so I had 5 speakers speaking at different times, which was horrible. Anyhow, it works. Thank you.

**Comment by bdenner51** [comment]
Tonesto and Kronos,

I think Kronos and I are working separate problems.  Mine is still broken.

If I should open a new thread/bug, please let me know.

My configuration:
*  Hubitat version 2.0.9.132
*  Echo Show: config: Gen (1), Knight, type: A1NL4BVLQ4L3N3, volume control (true), TTS (true), music player (true), music providers {amazon music, my library, pandora, tunein, iheart )

Condition observed:  Broadcast and announcement tests fail.

Steps taken:
1. I have deleted the app from my system.  
2. Loaded the app in Hubitat and reloaded the Heroku server.  Connected the Heroku to Amazon.  Tested and found that the test feature in IN THE APP WILL NOT SEND TTS to the Echo Show.  I can send TTS through the device configuration page as well as trigger jokes, interesting facts, and calendar summary. 
3. 1. I have deleted the app from my system.  
4 Rebooted Hubitat. 
5. Loaded the app in Hubitat and reloaded the Heroku server.  Connected the Heroku to Amazon.  Tested and found that the test feature in IN THE APP WILL NOT SEND TTS to the Echo Show. Essentially, same behavior as above.

Please see error log.

![3 May 19 - Echo Speaks_Error Log](https://user-images.githubusercontent.com/50034229/57152278-fd194f00-6da0-11e9-8261-c2be9d759965.jpg)

Thanks for the help.

Bruce

**Comment by josephsyracuse** [comment]
Sorry im new to all of this. I have installed echo speaks and seams to work good but i cant find a way to search for music from amazon music on the smartthings app for the selected echo device.

**Comment by tonesto7** [comment]
Use the the built in actions inside the smartapp. It will help you do exactly what you are looking for.

**Comment by josephsyracuse** [comment]
Thanks for the reply. I see that now. Is there some way I can just add a button that asks echo dot to “search so and so genre” in amazon music?

Thank You,

Joseph D. Syracuse
(239) 707-3351

**Comment by Tccshenkes** [comment]
Not sure if this is the right place for this, But I am having issues installing Echo Speaks. I have reinstalled it 3 times now and I get these errors in Hubitat when it tries to create devices.
app:4532020-06-13 07:41:32.980 pm errorEchoApp (v3.6.2.0) | AddDevice Error! | com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Echo Speaks Device' in namespace 'tonesto7' not found
app:4532020-06-13 07:41:32.976 pm info EchoApp (v3.6.2.0) | Creating NEW Echo Speaks Device!!! | Device Label: (Echo - Living Room)
So the only thing showing up under "Devices" is the Echo Speaks WebSocket. It says it found 7 devices but won't create them. 
Anybody out there that can help me?
