### ISSUE TITLE
(BUG) hubitat package manager update

### ISSUE THREAD

**Issue by GonzRon** [tonesto7/echo-speaks#767]
Error Downloading File
An error occured downloading
https://raw.githubusercontent.com/tonesto7/echo-speaks/master/smartapps/tonesto7/echo-speaks.src/echo-speaks.groovy

**Comment by tonesto7** [comment]
Sorry about that oversight... Just pushed out the updated manifest

**Comment by GonzRon** [comment]
worked, thanks!
