### ISSUE TITLE
[Feature Request] Security & Privacy Documentation

### ISSUE THREAD

**Issue by ucdscott** [tonesto7/echo-speaks#773]
**Is your feature request related to a problem? Please describe.**
If I'm not mistaken, this project's code consumes the user's Amazon credentials. Where is the documentation that describes the steps taken to protect those credentials?

**Describe the solution you'd like**
Please publish documentation that clearly describes how user's credentials are being used, stored, and protected.

**Describe alternatives you've considered**
Has the code been audited by an independent third party? If so, has their report been published? 

**Additional context**

**Comment by tonesto7** [comment]
Thanks for your suggestions. 

I'm going to be blunt I don't have the free time to write a proper security paper. 

I’m genuinely thankful for security-minded individuals like yourself. This is a free community software with publically available code. While I take every prevention to make this as safe as possible I'm only human and this integration is a workaround to access Amazon's APIs.

I can tell you that your actual Amazon credentials are not stored at any point and all we are doing is collecting your Alexa session cookie to make a request to Amazon for your Alexa devices. 
This cookie is only valid for Alexa.amazon.com URL and is stored in your Hubitat database and is only valid for <7.

The Heroku server is stateless so it looses its memory after 30 minutes of activity.

**Comment by ucdscott** [comment]
A good start would be describing how the user's Amazon credentials are consumed and then used obtain the Alexa session cookie.

If you care about security, surely you'd take the time to describe how the cookie is obtained, in-lieu of a proper security whitepaper, so that others could scrutinize and possibly offer suggestions to better protect your users.
