### ISSUE TITLE
[Add Device Support] 9th Gen Fire Tablet 7

### ISSUE THREAD

**Issue by mike-oconnor** [tonesto7/echo-speaks#777]
**Required Info is the following (Found under Echo Speaks app under devices page):

Family: TABLET
Type: A1Q7QCGNMXAKYW

* Model and/or Generation of device: Fire Tablet (9th Gen Fire 7, specifically)

**Have you tested the device for announcement/speech support using Alexa Routine? Yes

**Comment by mike-oconnor** [comment]
I went into the Echo Speaks App code and changed line 7214 to be:
`"A1Q7QCGNMXAKYW": [ caps: ["t", "a"], image: "amazon_tablet", name: "Fire Tablet" ],`

It works in every respect I can find.

**Comment by tonesto7** [comment]
I've added support in the latest code today
