### ISSUE TITLE
(BUG) Connect to Bluetooth is not Working

### ISSUE THREAD

**Issue by rontalley** [tonesto7/echo-speaks#79]
Disconnect to Bluetooth works flawlessly however Connect to Bluetooth does nothing. Tested it on 4 different Echo Device Types.

Dot 2st Gen
Echo 2nd Gen
Dot 3rd Gen
Show 1st Gen

**Comment by tonesto7** [comment]
Are you sending the device to connect to in the command?
https://tonesto7.github.io/echo-speaks-docs/#/docs/devices/deviceCommands/actionCommands

Look specifically for the connectBlueTooth()

**Comment by rontalley** [comment]
Only difference I see is the caps in the T. 
![connect to bluetooth](https://user-images.githubusercontent.com/21116697/55399038-0734fd00-5518-11e9-9be7-637227f3e6b0.png)

The command that is populated in webCoRE is: 
![Command Screenshot](https://user-images.githubusercontent.com/21116697/55399196-73affc00-5518-11e9-8ac7-803661a500a5.jpg)

**Comment by tonesto7** [comment]
If you pass the bluetooth device name as a parameter with the connectBluetooth() command.
You can see the full name listed under the device attributes 
![image](https://user-images.githubusercontent.com/1835933/57034622-06c67980-6c1e-11e9-88ea-f3b718bf6bc5.png)
