### ISSUE TITLE
(BUG) setLevel() falls into recursion and triggers a stackOverflow exception if called on muted device

### ISSUE THREAD

**Issue by mike-oconnor** [tonesto7/echo-speaks#791]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Hubitat
-  How many devices are detected?: 13
-  iOS or Android?: iOS
-  Mobile App Version(Not required):
-  App/SmartApp Version: 4.1.1.1
-  Device Handler/Driver Version: 4.1.1.1
-  Heroku Server Version: 4.7.0

## Expected Behavior
Calling setLevel() on a muted Echo device should set the Volume to the indicated level

## Current Behavior
The volume is set to desired level and, then immediately set to the pre-mute volume and and a stackOverflow exception occurs

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Mute() the echo device
2. setLevel(50) on the device
3. 
4.

The problem can be fixed in the updateLevel function by replacing line 2689 of the Echo Speaks Driver:
`        if (res != 0) updateMute('unmuted') `
with:
```
        if(res != 0) {
            state.muteLevel = null
            updateMute('unmuted')
        }
```
This way the updateMute function won't try to restore the pre-mute level and make the call back into updateLevel.
And this makes natural sense too, because setting the level explicitly to a non-zero value means you can forget the pre-mute volume since you've unmuted by different means.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by imnotbob** [comment]
This is fixed in latest release
