### ISSUE TITLE
Search TuneIn

### ISSUE THREAD

**Issue by Frappawotsit** [tonesto7/echo-speaks#8]
I still can't get any positive result from the searchTuneIn command. I saw your response about generating JSON data in the browser, but as a "non programmer" I have absolutely no idea what to do with that JSON data once generated. 

Any help or ideas why the searchTuneIn function doesn't work, or how to get it working? Thanks.

**Comment by tonesto7** [comment]
Not sure how i can help with this.  I don't have any control over the results.
