### ISSUE TITLE
Changelog Not Found

### ISSUE THREAD

**Issue by walksonair** [tonesto7/echo-speaks#812]
Looked for changelog by traversing links to it from main EchoSpeaks Github page and by going to https://raw.githubusercontent.com/tonesto7/echo-speaks/master/resources/changelog.txt. 

Has it been moved somewhere else?

**Comment by neeravmodi** [comment]
Had the same problem. Found it here:

https://raw.githubusercontent.com/tonesto7/echo-speaks/master/CHANGELOG.md
