### ISSUE TITLE
(BUG) - currentAlbum and currentStation are wrong

### ISSUE THREAD

**Issue by ryanbarrows** [tonesto7/echo-speaks#83]
echo-speaks-device.groovy has a bug from lines 809-815.  Your code for "currentAlbum" actually returns currentArtist (that's not a variable you currently have, but it's what is returned).  currentStation actually returns the currentAlbum.  Sorry that I didn't package this up as an official pull request, but it should be easy to fix.

**Comment by tonesto7** [comment]
I have to disagree with this one because I everything that I’ve used it works correctly maybe it just depends on the content you’re using
