### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by lynerin** [tonesto7/echo-speaks#86]
Hello. I'm using WebCore to fire pistons which, using Echo Speaks, send speak text requests to my Echo dot.  Everything works really well for anything up to 12 hours and then just stops.  Nothing is spoken even though the pistons fired.  In ST IDE the requests are visible and no error messages. The test broadcasts and announcement work from the app. I went through the support docs and followed the steps for removing and redeploying the server and it worked again.  Then after about 3 hours it stopped again.  This time I went into the app and cleared stored cookie data and went through the procedure to get a new cookie and it worked, pistons were producing speech on my dot.  Then it stopped working again.  What have I done wrong or where should I look for a solution?

**Comment by lynerin** [comment]
Thought it was working, cookie lasted 36 hours before I had to clear it and get a new one

**Comment by tonesto7** [comment]
Make sure you were running the latest server version it allows for automatic refresh the cookies

**Comment by cloudedturtle** [comment]
@lynerin - I recently had to do this as I didn't realize that it needed to be updated.. 
Please refer to the documentation link for [Updating the Server](https://tonesto7.github.io/echo-speaks-docs/#/docs/updates/serverUpdate).
