### ISSUE TITLE
Command Ignored... Device is current in OFFLINE State

### ISSUE THREAD

**Issue by tojannaon** [tonesto7/echo-speaks#865]
Echo Dot 3rd Gen shows that is in OFFLINE state while the Alexa app shows it ONLINE. As a result, when "speak text" is used the error in the title appears. All other local functions of the Dot work just fine during the time that Echo Speaks thinks it's OFFLINE. For example, I can turn on devices via Hubitat during that time and ask Alexa to do other things without any problem, Rebooting Hubitat reliably solves the problem but it is only temporary. If 24 hours go by before another "speak text" is sent it will likely have fallen back into OFFLINE mode and only rebooting Hubitat restores communication. The WebSocket is initialized and connected during this time.

**Comment by imnotbob** [comment]
Please list your versions in use of ES.  Are you running the latest version?  if not please update.
