### ISSUE TITLE
[ADD DEVICE SUPPORT] (1) Devices

### ISSUE THREAD

**Issue by robf17** [tonesto7/echo-speaks#869]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, siriusXm, spotify, isMultiroomMember, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
name: Echo Dot Sphere Blue
description: What kind of device/model? Echo Dot Gen-4 (sphere)
family: ECHO
type: A2U21SRK4QGSE1

**Comment by tonesto7** [comment]
The signature for this device is already in the app.  Make sure you are running the latest version of all app and device code (v4.1.8.0)
