### ISSUE TITLE
[Feature Request] - Provide Universal Announcement Pause / Mute

### ISSUE THREAD

**Issue by GonzRon** [tonesto7/echo-speaks#872]
**Is your feature request related to a problem? Please describe.**
I have many many alerts and notifications configured.  Sometimes I want to pause all alerts for a period of time.  There's no way currently to temporarily pause everything without configuring a switch condition in each alert.

**Describe the solution you'd like**
I would like a universal bypass.  Here's how it would work:
1. Configure alexa voice routine as so:  "Alexa, pause all notifications", this routine enables a Virtual Switch called VS-Pause Alexa Notifications
2. Inside Alexa Speaks, if this switch is enabled, all notifications are paused.  
3. The pause delay is configurable inside the new function. 
4. once the alert delay has been reached, alerts are continued, and VS Pause Alexa Notifications Switch can be "turned off" or reset.

**Describe alternatives you've considered**
Currently, the same VS-Pause Alexa Notification switch can be configured individually for each alert in the ECHO Speaks "Actions" section.

**Additional context**
A universal Bypass would pause all Active Actions that make announcements without having to configure the same virtual switch in all alerts.

**Comment by Lcstyle** [comment]
this is a duplicate of #855
