### ISSUE TITLE
Enable support for Vobot [Feature Request]

### ISSUE THREAD

**Issue by markcanup** [tonesto7/echo-speaks#89]
I am using Echo Speaks with Hubitat. I have three Echo Dot (Gen 2) devices that work great. I also have two Alexa-enabled digital clock devices called VOBOT that are recognized by Echo Speaks, but Echo Speaks doesn't they support Text-To-Speech. I have used the Device Test Page and the Sequence Creator Test to test getting the devices to speak arbitrary text, and it works just like the Echo devices do. But, when I try to use a text-related command from the Device page in Hubitat, it doesn't work. Also, the metadata for the devices show the field ttsSupported: false. This suggests to me that Echo Speaks believes they don't support Text-To-Speech even though they do.

One of the devices is https://getvobot.com/clock and the other is https://getvobot.com/vobot-bunny. The info above is true for both devices. They both show up with the device type A10L5JEZTKKCZ8.

**Comment by tonesto7** [comment]
@markcanup All set... Just update the device code to v2.5.2 and open the smartapp and hit done.
