### ISSUE TITLE
Incorrect Device type

### ISSUE THREAD

**Issue by holdestmade** [tonesto7/echo-speaks#9]
I have a Gen1 and a Gen2 echo dot.

The Gen1 is recognised correctly but the gen2 shows it as a gen 1 echo with an echo icon (not dot).

Device page on IDE below, notice the deviceStatus shows gen2 but the deviceStyle shows Echo (Gen1)

> status: stopped
> level: 24
> trackDescription:
> mute: muted
> volume: 24
> lastUpdated: Nov 19, 2018 - 4:28:14 PM
> deviceStatus: stopped_echo_gen2
> deviceType: A32DOYMUN6DTXA
> deviceStyle: Echo (Gen1)
> doNotDisturb: false
> firmwareVer: 1577509252
> onlineStatus: online
> currentStation: Idle
> currentAlbum: Idle
> lastSpeakCmd: I said a hip hop, Hippie to the hippie, The hip, hip a hop, and you don't stop, a rock it out, Bubba to the bang bang boogie, boobie to the boogie To the rhythm of the boogie the beat, Now, what you hear is not a test, I'm rappin' to the beat
> lastCmdSentDt: Mon Nov 19 10:47:50 GMT 2018
> trackImage:
> alarmVolume: 50
> alexaWakeWord: ALEXA
> wakeWords: ["ALEXA","ECHO","COMPUTER","AMAZON"]
> alexaPlaylists:

![screenshot_20181119-163426](https://user-images.githubusercontent.com/13977244/48721105-1f674800-ec19-11e8-8225-0aec68db1801.jpg)

**Comment by tonesto7** [comment]
@holdestmade Thanks for reporting this so to confirm your GEN1 echo_dot is showing a gen2 image?
I only ask because I have a table i've been building and this deviceType is not related to any known dot
![image](https://user-images.githubusercontent.com/1835933/48724969-bcfe4f80-ebf8-11e8-9642-004cbc023cf0.png)

**Comment by tonesto7** [comment]
That's a 3rd GEN.
Does it look like this?
![image](https://user-images.githubusercontent.com/1835933/48725187-5f1e3780-ebf9-11e8-8138-826319963adb.png)

**Comment by holdestmade** [comment]
Yes sorry it's a gen3 dot. It's showing as an echo

**Comment by tonesto7** [comment]
I'm overhauling the whole device detection and support right now.  To allow more devices

**Comment by holdestmade** [comment]
Ok great thanks

**Comment by tonesto7** [comment]
This is corrected in v1.3.0 so i'm closing this out
