### ISSUE TITLE
"Only alert once a day" toggle for actions INOP

### ISSUE THREAD

**Issue by dbennett3321** [tonesto7/echo-speaks#906]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):
-  How many devices are detected?:
-  iOS or Android?:
-  Mobile App Version(Not required):
-  App/SmartApp Version:
-  Device Handler/Driver Version:
-  Heroku Server Version:

## Expected Behavior
**Action should run once a day**

## Current Behavior
**Action will only run once after initialization. Does not reset.**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Create action
2. Set "Only alert once a day" toggle to "on"
3.
4.

## Context
**This will not allow an action to run after its first time. 
**Currently I have this set without any other conditions and it is initializing an Alexa routine. I tested this without the toggle on and it works perfectly**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by imnotbob** [comment]
It would be good to show full logs.  I have pushed an update with improved logging to Tony.

I ran a test or two and did not see any issues.
