### ISSUE TITLE
Adjust changelog URL to render HTML

### ISSUE THREAD

**Issue by callit** [tonesto7/echo-speaks#907]
When viewing the changelog URL that is shown in the Hubitat Package Manager, we are directed to https://raw.githubusercontent.com/tonesto7/echo-speaks/master/CHANGELOG.html which displays raw HTML and is difficult to parse.

Can I suggest using a renderer like this as the link in the changelog: https://htmlpreview.github.io/?https://raw.githubusercontent.com/tonesto7/echo-speaks/master/CHANGELOG.html

That will render the HTML for us and make the changelog much easier to read.

Thanks!

**Comment by tonesto7** [comment]
thanks... I will just change it to target the markdown file
