### ISSUE TITLE
Device support for Echo Show 5 (2nd Gen, 2021 release)

### ISSUE THREAD

**Issue by jlupien** [tonesto7/echo-speaks#911]
Requesting device support from the following device(s):
permissions: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, spotify, isMultiroomMember, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, isEchoDevice
name: Kitchen
description: What kind of device/model? Echo Show 5 (2nd Gen, 2021 release)
family: KNIGHT
type: A1XWJRHALS1REP

**Comment by tonesto7** [comment]
I will be releasing an update with support today...  Check for an update this afternoon
