### ISSUE TITLE
(ACTIONS BUG) “Test this Action” option is not working

### ISSUE THREAD

**Issue by Felipetomaz** [tonesto7/echo-speaks#916]
“Test this Action” option is not working.

I am using the last version.

In the logs I have:

app:9772021-09-14 14:48:03.418 traceAction (v4.1.9.9) | executeActTest ENDING
app:9772021-09-14 14:48:03.388 warn Action (v4.1.9.9) | TEST of Action type sequence SKIPPED
app:9772021-09-14 14:48:03.385 traceAction (v4.1.9.9) | executeActTest STARTING
app:9772021-09-14 14:48:03.378 debugAction (v4.1.9.9) | getOk2Notify() RESULT: true | notifDevsOk: true |smsOk: null | pushOk: null | pushOver: null | alexaMsg: false || daysOk: true | timeOk: true | modesOk: true
app:9772021-09-14 14:48:03.297 traceAction (v4.1.9.9) | conditionsStatus | ok: true | RequireAll: false | Found: (0) | Skipped: [time, date, location, device] | Passed: [] | Failed: []
app:9772021-09-14 14:48:03.294 traceAction (v4.1.9.9) | deviceCondOk | null | Found: (0) | Skipped: [switch, motion, presence, contact, acceleration, lock, securityKeypad, door, windowShade, valve, water, thermostatMode, thermostatOperatingState, thermostatFanMode, temperature, humidity, illuminance, level, power, battery, coolingSetpoint, heatingSetpoint, thermostatTemperature] | Passed: [] | Failed: []
app:9772021-09-14 14:48:03.292 traceAction (v4.1.9.9) | locationCondOk | null | modeOk: null | alarmOk: null
app:9772021-09-14 14:48:03.289 traceAction (v4.1.9.9) | dateCondOk | null | monthOk: null | daysOk: null
app:9772021-09-14 14:48:03.286 traceAction (v4.1.9.9) | timeCondOk | (null)

**Comment by Lcstyle** [comment]
not sure why this was closed, test actions isn't working @tonesto7
