### ISSUE TITLE
[DEVICE SUPPORT] | A15996VY63BQ2D

### ISSUE THREAD

**Issue by zuhairmahd** [tonesto7/echo-speaks#919]
Requesting device support for the following device(s):
**permissions**: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, appleMusic, spotify, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
**name**: Zuhair's Echo Show 8 2nd Gen
**description**: What kind of device/model?(PLEASE UPDATE THIS)
**family**: KNIGHT
**type**: A15996VY63BQ2D

**Comment by tonesto7** [comment]
thanks for reporting. This will be added to the next release.
