### ISSUE TITLE
Amazon Cookie not saving(BUG) 

### ISSUE THREAD

**Issue by brentokeeffe** [tonesto7/echo-speaks#92]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ X ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ X ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ X ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ X ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): SmartThings
-  How many devices are detected?: 0 
-  iOS or Android?: IOS
-  Mobile App Version(Not required):
-  App/SmartApp Version: 2.5.0
-  Device Handler/Driver Version: 2.5.2
-  Heroku Server Version: 2.2.1

## Expected Behavior
**tell us what should happen**  After entering Amazon credentials, I should see Authentication Good on the page

## Current Behavior
**What happens instead of the expected behavior?**  After entering credentials, I see the "Amazon Alexa Cookie Retrieved Successfully
You will be redirected back to the config page in 5 seconds", then I am presented with the same page asking for "Amazon Login - Go to the Login Page" option.  It may be worth noting that I do not have the option to "Keep me signed in" that the instructions shows.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.Click Manage App
2.Click "Go to Login Page"
3.Enter credentials
4.Returns to screen to click on Go to Login Page.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**
There are no logs to provide.
---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by brentokeeffe** [comment]
Is it possible to generate and install a manual cookie?

**Comment by jszust** [comment]
How do you generate a cookie manually? I tried using EditThisCookie with Chrome and pulled both the CSRF and A2S_CSRF but no combination of the values and strings made things work correctly. I am having the same issue where the cookie is not being saved.

**Comment by cloudedturtle** [comment]
Hey guys, I noticed today that my Echo wasn't announcing activities like it was. I attempted to get a new Cookie, and got this same behavior. I noticed this little guy in the LOG from Heroku app: 
`2019-06-20T13:23:23.628714+00:00 app[web.1]: 6-20-2019 - 1:23:23pm debug: 	Alexa Login Status: There was an error`
I attempted to login to the Amazon Alexa web app, and when I logged in I was prompted to "Reenter my password AND the security code show... 
![image](https://user-images.githubusercontent.com/12900081/59853914-d5c21580-933f-11e9-96e6-c1a3049c6498.png)
I'm wondering if this security code aspect is what may be causing the problems.

**Comment by cloudedturtle** [comment]
..To add a little more, I attempted to "Add Cookie Manually" using the Session token and CSRF values from Chrome Dev Tools (after logging into the Alexa Service.) I now see this screen, but my services still don't work.
![image](https://user-images.githubusercontent.com/12900081/59854593-3bfb6800-9341-11e9-9b0d-57105c65c8e6.png)

**Comment by robertgoron88** [comment]
Can you explain it how add the cookie manually?
Thanks

**Comment by LukeRuppSr** [comment]
Apparently I have the same issue as brentokeeffe. Alexa stopped announcing. I deleted the Heroku app several times and recreated the Heroku app. I always end up back at the Amazon Login page presenting "GOTO LOGIN PAGE" and the "Autthentication Good!" is not displayed. I wonder if Amazon changed something on their side that is making the Amazon cookie refresh fail.

**Comment by johnlietzke** [comment]
I also experienced the same issue where "GOTO LOGIN PAGE" appears on the redirect page.  I have tried everything from manually entering the token to uninstalling the APP.

**Comment by mattmoo44** [comment]
Experiencing the same issue. 

Keeps asking for login, and says Amazon Alexa Cookie Retrieved Successfully
You will be redirected back to the config page in 5 seconds", then back to the same login page. 

Getting the cookie from chrome developer tools did result in 'authentication good' and now I'm up and running again.

**Comment by robertgoron88** [comment]
I never used chrome developer tools.
Could you please write down the steps what to follow.
I'm struggling for almost a week with it.
Thanks

**Comment by mattmoo44** [comment]
I was unsure how to do it manually as well but managed to find instructions after a bit of googling! 

Copied below, hopefully it will help. 

1. Open Chrome and Login to alexa.amazon.com
2. Open the Chrome menu at the top-right of your browser window, then select Tools (More Tools) &gt; Developer Tools (or click F12)
3. On top row of developer tools you will see several tabs: Elements, Console, Sources, Network, etc. Click Network.
4. Just below the tabs you will see a red circle, below that you will see a filter box, and below that you will see sub tabs: All, XHR, JS, etc. Click XHR
5. Click Smart Home in the left navigation
6. The developer tools XHR list should populate with several items, one called "featureaccess-v3", right-click on it and choose Copy, Copy Request Headers. This will place it into your clipboard.
7. Paste the cookie into the app

**Comment by robertgoron88** [comment]
I don´t see smart home in the left navigation :|
This is what i have:
![cookie](https://user-images.githubusercontent.com/50329049/59925059-d8367500-93fc-11e9-93cf-d953ba529a39.png)

**Comment by mattmoo44** [comment]
It's on the alexa website to the very left. The three bars in top left, menu drops down. You should find it there

**Comment by cloudedturtle** [comment]
Click the menu on the Top Left (the 3 lines) and select Smart Home from that menu... 

The directions above didn't EXACTLY work for me.. I found that pasting the Request Header into Notepad and then copying everything after "Cookie: " and below was the appropriate action. (The CSRF value is also in the header information.)

Here is what I get in notepad++ when I paste the "Request Headers" and what I copied respectively. 
![image](https://user-images.githubusercontent.com/12900081/59926119-9959ec80-9407-11e9-80e1-101a8baec808.png)

This did work for me!

**Comment by robertgoron88** [comment]
Yaaay!
Thank you guys!
It looks like working again.
The copying to notepad worked.
Pasted the cookie and the csrf, saved it and the smartthings app shows everything good.
big thank you!

**Comment by cloudedturtle** [comment]
It does seem to be something that Amazon has changed; hopefully @tonesto7 or another team member can get resolved so that we don't have to manually enter the cookie.

**Comment by LukeRuppSr** [comment]
Copying the cookie and csrf worked for me as well. Thanks for the guide. I wonder how often it expires and we have to manually do again.

**Comment by mattmoo44** [comment]
That was my concern, how often does it expire!

**Comment by jszust** [comment]
Thanks CloudedTurtle, your write-up worked for me.

**Comment by tonesto7** [comment]
Please update to server v2.2.2 for cookie fixes.

**Comment by LukeRuppSr** [comment]
Thanks for server 2.2.2 for the cookie fix. It works for me.

**Comment by brentokeeffe** [comment]
Yep. Mine works now. Awesome response. Thanks all.

**Comment by DGBQ** [comment]
Hi can I have some help with this please.
I not clear on step "7. Paste the cookie into the app".  What app and where am I pasting to?
Thanks

**Comment by gads83** [comment]
I have tried all of the above and I'm still having the same issue. Any ideas?

**Comment by thesploog** [comment]
Hi, I've tried all of the above. I'm having the same issues. Does anybody have any new advice, this seems to be a UK thing?

**Comment by thesploog** [comment]
@tonesto7 how do I update the server. This problem seems to be happening again. I'm in the UK and have set Amazon region and locale to UK? Hope you can help please, this is driving me crazy

**Comment by Jmarcos13** [comment]
> @tonesto7 how do I update the server. This problem seems to be happening again. I'm in the UK and have set Amazon region and locale to UK? Hope you can help please, this is driving me crazy

U can try this guide to update the server:

https://tonesto7.github.io/echo-speaks-docs/updates/server_update/
