### ISSUE TITLE
[DEVICE SUPPORT] | A15996VY63BQ2D

### ISSUE THREAD

**Issue by kginfla** [tonesto7/echo-speaks#935]
Requesting device support for the following device(s):
**permissions**: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, pandoraRadio, appleMusic, spotify, isMultiroomMember, alarms, reminders, doNotDisturb, wakeWord, flashBriefing, microphone, followUpMode, bluetoothControl, guardSupported, isEchoDevice
**name**: Echo Show
**description**: What kind of device/model?(PLEASE UPDATE THIS)
**family**: KNIGHT
**type**: A15996VY63BQ2D

**Comment by tonesto7** [comment]
Thanks for reporting this will be included in the next public release￼
