### ISSUE TITLE
Another Amazon Domain Option

### ISSUE THREAD

**Issue by SatoruPA** [tonesto7/echo-speaks#936]
Dear Developers.
I appreciate what you have been doing for us and it seems really nice to use!
I would like you to add 'amazon.co.jp' for Amazon Domain in the server setup if it's possible.

Best regards,

**Comment by tonesto7** [comment]
sure. i will try to get it out today

**Comment by SatoruPA** [comment]
Wow, I didn't expect that quick reply!
Thank you so much ;)
I can't wait to use your marvelous app!
