### ISSUE TITLE
(BUG) Alexa Guard enable (Away) fails

### ISSUE THREAD

**Issue by SANdood** [tonesto7/echo-speaks#947]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ x ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Hubitat
-  How many devices are detected?: N/A
-  iOS or Android?: iOS
-  Mobile App Version(Not required):
-  App/SmartApp Version: 
- 

App: | v4.1.9.9
Device: | v4.1.9.9
Server: | v2.7.0

-  Device Handler/Driver Version:
-  Heroku Server Version:

## Expected Behavior
**tell us what should happen**
Alexa Guard should change to Stay when mode changes to Away

## Current Behavior
**What happens instead of the expected behavior?**
Nothing happens, but the following is logged by Echo Speaks:

app:882021-10-25 05:36:52.247 pm warn EchoApp (v4.1.9.9) | Setting Alexa Guard Mode to Away...
app:882021-10-25 05:36:52.200 pm errorEchoApp (v4.1.9.9) | Failed to set Alexa Guard to (ARMED_AWAY) | Reason: [[entity:[entityId:AAA_OnGuardSmartHomeBridgeService_9f1e2178-ba73-3f90-aa3e-c2ee90103bb6, entityType:APPLIANCE], code:ERROR_BUILDING_REQUEST, message:An error occurred while applying request adapter in sdp, data:null]]

I suspect the same thing happens when trying to turn off Guard (change to Stay), but since it doesn’t change to Away, the change to Stay is skipped…

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by SANdood** [comment]
Any idea if/when you can fix this?

**Comment by tonesto7** [comment]
My understanding is that it started working again

**Comment by SANdood** [comment]
Indeed, it works again…

Thanks!
       Barry
