### ISSUE TITLE
(BUG) Triggers based on Switch States do not Trigger for Devices already in those states

### ISSUE THREAD

**Issue by Lcstyle** [tonesto7/echo-speaks#950]
## Expected Behavior
Triggers that are based on on/off switch states should trigger automatically if those devices are already in that state

## Current Behavior
Currently Devices that are already off for example, won't trigger the announcement because the trigger is looking for an event transition to the required trigger state, rather than for the actual current state.

## Steps to Reproduce (for bugs)
1. Create a rule that triggers when a switch is off (notice here it's a bit confusing, do we want the switch to be off, or do we want to monitor for the switch to go from on to off (an event)).
2. Create restrictions that only let the announcement trigger during certain times, e.g. 5PM to 6PM
3. Notice that if the device is already off when entering the time period that satisfies the restriction, nothing happens.
4. during the example time period, e.g. at 5:30 PM, turn the device on, then turn the device off and the rule will trigger.

## Context
**How has this issue affected you? What are you trying to accomplish?**

i need the trigger to be satisfied when the device or switch state is off, not when a device is *TURNED* off.
The trigger "device "turns" off" (as opposed to device is off) imposes a hidden requirement, it is monitoring for a "device state change event".  However, a device state change event should be a different kind of trigger, a STATE change trigger, rather than a current state trigger.   That is the distinction that is important here.  My device will enter the restricted time period already in an off state, but from a certain time lets say 6PM to 7PM the device should not be off, it should be on.  Currently, if the device turns off during 6-7PM then the announcement trigger will fire, because an OFF event occurred, but if the device never goes to on and back to off, then the announcement never fires, and the device stays off, and the user is never notified (i.e. the announcement never runs).

**Providing context helps us come up with a solution that is most useful in the real world**

BTW, this was working perfectly around this same time period last year (Oct-Nov), and because the use case for this announcement is based on seasonal usage (i.e. Winter Heating device), I did not notice that the behavior had changed until now.

**Comment by GonzRon** [comment]
@tonesto7 have you had a chance to review this issue?  Any idea whether you would consider this issue a defect or working as designed?

**Comment by tonesto7** [comment]
shouldn't you be using a condition instead of a switch event?

**Comment by GonzRon** [comment]
@tonesto7 thanks for the response, a triggering event is required, what would be my trigger event for the use case described?

**Comment by imnotbob** [comment]
This may be better in the forum.

It seems you want two triggers - scheduled by the start of your timeframe, and switch change (any).

Then in conditions, you can check if things match what you want to do the ES action or not.

**Comment by GonzRon** [comment]
thank you, and you're right, that's how I fixed it, two triggers, however, this was working previously without the additional trigger previously.
