### ISSUE TITLE
turning off "Show Info/Warning Logs" doesn't stop logging (BUG) 

### ISSUE THREAD

**Issue by scottdog123** [tonesto7/echo-speaks#953]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):  Hubitat 2.2.9.146
-  How many devices are detected?: 9
-  iOS or Android?: iOS
-  Mobile App Version(Not required):
-  App/SmartApp Version:
-  Device Handler/Driver Version: Device:	v4.1.9.9
-  Heroku Server Version: Server:	v2.7.0

## Expected Behavior
Under "Manage Logging, and Metrics", when the switches for "Show Info Logs?" and "Show Warning Logs" are disabled, there should not be info and warning level logs in the Hubitat log.

## Current Behavior
I see info and warning level messages in the Hubitat log.

## Steps to Reproduce (for bugs)
Turn off "Show Info Logs?" and "Show Warning Logs" then watch Hubitat log.

1.
2.
3.
4.

## Context
This causes my log to cycle quickly and makes it difficult to see real problems.

---
dev:32092021-11-10 11:21:39.125 am warn Socket (v4.1.9.9) | WebSocket connection closing.
dev:32092021-11-10 11:21:39.082 am info Socket (v4.1.9.9) | Alexa WS Connection is Open
dev:32092021-11-10 11:21:36.492 am info Socket (v4.1.9.9) | close() called
dev:32092021-11-10 11:21:35.477 am info Socket (v4.1.9.9) | initialize() called
dev:32092021-11-10 11:21:35.467 am info Socket (v4.1.9.9) | updated() called
dev:32092021-11-10 11:06:39.217 am warn Socket (v4.1.9.9) | WebSocket connection closing.
dev:32092021-11-10 11:06:39.168 am info Socket (v4.1.9.9) | Alexa WS Connection is Open
dev:32092021-11-10 11:06:36.609 am info Socket (v4.1.9.9) | close() called
dev:32092021-11-10 11:06:35.593 am info Socket (v4.1.9.9) | initialize() called
dev:32092021-11-10 11:06:35.581 am info Socket (v4.1.9.9) | updated() called
dev:32092021-11-10 10:51:39.463 am warn Socket (v4.1.9.9) | WebSocket connection closing.
dev:32092021-11-10 10:51:39.418 am info Socket (v4.1.9.9) | Alexa WS Connection is Open
dev:32092021-11-10 10:51:36.836 am info Socket (v4.1.9.9) | close() called
dev:32092021-11-10 10:51:35.820 am info Socket (v4.1.9.9) | initialize() called
dev:32092021-11-10 10:51:35.810 am info Socket (v4.1.9.9) | updated() called
dev:32092021-11-10 10:36:39.195 am warn Socket (v4.1.9.9) | WebSocket connection closing.
dev:32092021-11-10 10:36:39.144 am info Socket (v4.1.9.9) | Alexa WS Connection is Open
dev:32092021-11-10 10:36:36.539 am info Socket (v4.1.9.9) | close() called
dev:32092021-11-10 10:36:35.525 am info Socket (v4.1.9.9) | initialize() called
dev:32092021-11-10 10:36:35.513 am info Socket (v4.1.9.9) | updated() called
dev:32092021-11-10 10:21:39.163 am warn Socket (v4.1.9.9) | WebSocket connection closing.
dev:32092021-11-10 10:21:39.120 am info Socket (v4.1.9.9) | Alexa WS Connection is Open
dev:32092021-11-10 10:21:36.529 am info Socket (v4.1.9.9) | close() called
dev:32092021-11-10 10:21:35.515 am info Socket (v4.1.9.9) | initialize() called
dev:32092021-11-10 10:21:35.505 am info Socket (v4.1.9.9) | updated() called
dev:32092021-11-10 10:06:39.780 am warn Socket (v4.1.9.9) | WebSocket connection closing.

**Comment by imnotbob** [comment]
Can you show the device settings for the web socket device?

HE console -> devices -> Echo Speaks - WebSocket ?

This may be easier in the forum to set your screen shot.

**Comment by scottdog123** [comment]
I was looking at the settings in:
Apps -> Echo Speaks -> Manage Logging, and Metrics

But I should have noticed that the log messages were created by a device "dev:3209", after changing the setting in the device websocket (the path you pointed out above), I no longer see the log messages.

thank you for your help!
