### ISSUE TITLE
[DEVICE SUPPORT] | A132LT22WVG6X5

### ISSUE THREAD

**Issue by EdStevens1957** [tonesto7/echo-speaks#958]
Requesting device support for the following device(s):
**permissions**: volumeControl, mediaPlayer, amazonMusic, tuneInRadio, iHeartRadio, spotify, alarms, reminders, doNotDisturb, microphone, followUpMode
**name**: Ed's Samsung Soundbar Q700A
**description**: What kind of device/model?(PLEASE UPDATE THIS)
**family**: UNKNOWN
**type**: A132LT22WVG6X5

**Comment by tonesto7** [comment]
this will be added to the upcoming release
