### ISSUE TITLE
(BUG) Can't install APP

### ISSUE THREAD

**Issue by aismen69** [tonesto7/echo-speaks#96]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub: SmartThings
-  How many devices are detected?: 0
-  iOS or Android?: iOS
-  Mobile App Version(Not required):
-  App/SmartApp Version: 2.6.0
-  Device Handler/Driver Version: 2.6.0
-  Heroku Server Version: 

## Expected Behavior
App Installation

## Current Behavior
When install App from My Apps load continuously and nothings appears.
Reopening Smartthings App and click to Echo Speaks App installed loading 1 seconds and remain on my installed app list. I've never been see a config app screen and I can't uninstall app because smartthings IDE tell me that app is installed by user.

## Steps to Reproduce (for bugs)
Try to add App from My Apps

This is Output of Echo Speaks Installed App from my location's apps
<img width="989" alt="Schermata 2019-07-14 alle 19 24 49" src="https://user-images.githubusercontent.com/16617969/61187124-4245e100-a66e-11e9-9e38-c304527d972a.png">

**Comment by rich110** [comment]
I am also having a problem with Echo Speaks loading in my mobile app. I tried installing Echo Speaks with Community Installer and GetHub but neither one worked.

**Comment by bradpinkston** [comment]
Same issue it seems.  iOS screenshot attached.
![IMG_0954](https://user-images.githubusercontent.com/21313445/61257722-e34c9e80-a737-11e9-9250-7e4f11421f0c.png)
