### ISSUE TITLE
(BUG) Echo Speaks not functioning in App or Pistons

### ISSUE THREAD

**Issue by toddbecker19** [tonesto7/echo-speaks#98]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [X] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [X] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): SmartThings
-  How many devices are detected?: 7
-  iOS or Android?: Android
-  Mobile App Version(Not required): Classic
-  App/SmartApp Version: v2.6.0
-  Device Handler/Driver Version: v2.6.0
-  Heroku Server Version: v2.2.1?

## Expected Behavior
Echo Speaks is not working at all. I have multiple Pistons that use Echo Speaks that were working in the past but have stopped working.

## Current Behavior
Nothing, no errors are reported during execution. I have found two issues while troubleshooting.

I see this in the smart apps log - CODE UPDATES REQUIRED: Echo Speaks Integration may not function until the following items are ALL Updated [Echo Speaks Server]

I encounter this error when trying to refresh my Heroku cookie - HTTP Status 500 - org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: Locale part “US/proxy” contains invalid characters

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

All use of Echo Speaks is in Pistons related to alerts in my home (water leak, open garage, etc.) there are no public ways to test this. My code has two different instances, one using setVolumeSpeakAndRestore and the other using playAnnouncementAll.

The test functionality within the smart app does not work as well. There are no errors produced.
1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

I utilize these Pistons to provide an alert within my house of an issue that needs immediate attention. I also push a notification to the SmartThings app, but that is less effective as I may not be home. This functionality has been effective in the past at identifying a water leak in my basement and notifying everyone through the Echos in the house at 4 AM so the issue was resolved without damage to the basement.

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
Had to update the server to v2.2.2 and it started working.
